# Generated by Django 2.1.5 on 2019-03-25 21:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("orgs", "0052_populate_org_uuid"), ("channels", "0117_auto_20190227_2137")]

    operations = [
        migrations.CreateModel(
            name="ChannelTemplate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.CharField(max_length=1280)),
                ("status", models.CharField(choices=[("A", "approved"), ("P", "pending")], default="P", max_length=1)),
                ("language", models.CharField(max_length=3)),
                ("external_id", models.CharField(max_length=64, null=True)),
                ("channel", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="channels.Channel")),
            ],
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64)),
                ("modified_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("org", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="orgs.Org")),
            ],
        ),
        migrations.AddField(
            model_name="channeltemplate",
            name="template",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="templates.Template"),
        ),
        migrations.AlterUniqueTogether(name="template", unique_together={("org", "name")}),
    ]
