# Generated by Django 2.1.8 on 2019-05-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("templates", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="templatetranslation",
            name="status",
            field=models.CharField(
                choices=[("A", "approved"), ("P", "pending"), ("R", "rejected")], default="P", max_length=1
            ),
        )
    ]
