# Generated by Django 2.2.4 on 2020-05-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("templates", "0004_initial")]

    operations = [migrations.AlterField(model_name="template", name="name", field=models.CharField(max_length=512))]
