# Generated by Django 2.2.4 on 2020-05-25 18:01

import django_countries.fields

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("templates", "0005_auto_20200518_1227")]

    operations = [
        migrations.AddField(
            model_name="templatetranslation",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        )
    ]
