# Generated by Django 2.2.20 on 2021-05-13 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0010_populate_namespaces"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatetranslation",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="template_translations",
                to="channels.Channel",
            ),
        ),
    ]
