# Generated by Django 4.2.3 on 2023-11-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0014_templatetranslation_components_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatetranslation",
            name="external_locale",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="templatetranslation",
            name="locale",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
