# Generated by Django 4.2.3 on 2023-11-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0016_backfill_locale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatetranslation",
            name="status",
            field=models.CharField(
                choices=[("A", "approved"), ("P", "pending"), ("R", "rejected"), ("X", "unsupported_components")],
                default="P",
                max_length=1,
            ),
        ),
    ]
