# Generated by Django 4.2.8 on 2024-03-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0022_alter_templatetranslation_params_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="templatetranslation",
            name="content",
        ),
        migrations.RemoveField(
            model_name="templatetranslation",
            name="params",
        ),
        migrations.RemoveField(
            model_name="templatetranslation",
            name="variable_count",
        ),
        migrations.AddField(
            model_name="templatetranslation",
            name="comps_as_dict",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="templatetranslation",
            name="components",
            field=models.JSONField(default=list),
        ),
    ]
