# Generated by Django 5.0.3 on 2024-04-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0026_alter_templatetranslation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatetranslation",
            name="variables",
            field=models.JSONField(default=list),
        ),
    ]
