# Generated by Django 5.0.4 on 2024-06-27 18:49

from django.db import migrations


def remove_duplicate_translations(apps, schema_editor):  # pragma: no cover
    Template = apps.get_model("templates", "Template")

    for template in Template.objects.all():
        seen_channel_and_locale = set()

        # prefer active and newer translations when duplicates are found
        for trans in template.translations.select_related("channel").order_by("-is_active", "-id"):
            if (trans.channel, trans.locale) in seen_channel_and_locale:
                trans.delete()
                print(
                    f"Deleted duplicate '{trans.locale}'@'{trans.channel.name}' translation for template {template.uuid}"
                )

            seen_channel_and_locale.add((trans.channel, trans.locale))


class Migration(migrations.Migration):

    dependencies = [("templates", "0030_alter_templatetranslation_locale")]

    operations = [migrations.RunPython(remove_duplicate_translations, migrations.RunPython.noop)]
