# Generated by Django 5.0.4 on 2024-06-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0185_alter_channel_name"),
        ("templates", "0031_remove_duplicate_translations"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="templatetranslation",
            name="templatetranslations_by_ext",
        ),
        migrations.AddConstraint(
            model_name="templatetranslation",
            constraint=models.UniqueConstraint(
                fields=("template", "channel", "locale"), name="templatetranslations_unique"
            ),
        ),
    ]
