# Generated by Django 5.0.6 on 2024-07-05 19:38

from django.db import migrations


def backfill_template_fields(apps, schema_editor):  # pragma: no cover
    Template = apps.get_model("templates", "Template")

    for tpl in Template.objects.filter(created_by=None).select_related("org__created_by"):
        tpl.created_by = tpl.org.created_by
        tpl.modified_by = tpl.org.created_by
        tpl.save(update_fields=("created_by", "modified_by"))


class Migration(migrations.Migration):

    dependencies = [("templates", "0033_template_created_by_template_is_active_and_more")]

    operations = [migrations.RunPython(backfill_template_fields, migrations.RunPython.noop)]
