# Generated by Django 5.0.6 on 2024-07-08 14:56

from django.db import migrations


def delete_inactive_translations(apps, schema_editor):  # pragma: no cover
    TemplateTranslation = apps.get_model("templates", "TemplateTranslation")
    num_deleted = 0

    while True:
        batch_ids = TemplateTranslation.objects.filter(is_active=False).values_list("id", flat=True)[:1000]
        if not batch_ids:
            break

        TemplateTranslation.objects.filter(id__in=batch_ids).delete()
        num_deleted += len(batch_ids)

    if num_deleted:
        print(f"Deleted {num_deleted} inactive template translations")


class Migration(migrations.Migration):

    dependencies = [("templates", "0035_alter_template_created_by_alter_template_modified_by")]

    operations = [migrations.RunPython(delete_inactive_translations, migrations.RunPython.noop)]
