# Generated by Django 5.0.6 on 2024-07-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0037_alter_templatetranslation_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="templatetranslation",
            name="is_active",
        ),
    ]
