# Generated by Django 5.0.6 on 2024-07-10 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("templates", "0038_remove_templatetranslation_is_active")]

    operations = [
        migrations.AddField(
            model_name="template",
            name="base_translation",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="base_template",
                to="templates.templatetranslation",
            ),
        ),
    ]
