# Generated by Django 5.0.6 on 2024-07-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0042_populate_translation_is_supported_compatible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatetranslation",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("A", "Approved"),
                    ("R", "Rejected"),
                    ("U", "Paused"),
                    ("D", "Disabled"),
                    ("I", "In Appeal"),
                    ("X", "Unsupported"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
