# Generated by Django 5.0.6 on 2024-07-12 21:21

from django.db import migrations, models


def unsupported_to_pending(apps, schema_editor):  # pragma: no cover
    TemplateTranslation = apps.get_model("templates", "TemplateTranslation")

    TemplateTranslation.objects.filter(status="X").update(status="P")


class Migration(migrations.Migration):

    dependencies = [("templates", "0043_alter_templatetranslation_status")]

    operations = [
        migrations.RunPython(unsupported_to_pending, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="templatetranslation",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("A", "Approved"),
                    ("R", "Rejected"),
                    ("U", "Paused"),
                    ("D", "Disabled"),
                    ("I", "In Appeal"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
