# Generated by Django 2.2.4 on 2020-04-09 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orgs", "0059_auto_20200409_1428"), ("two_factor", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="backuptoken", name="profile"),
        migrations.AddField(
            model_name="backuptoken",
            name="settings",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="backups",
                to="orgs.UserSettings",
                verbose_name="Settings",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="Profile"),
    ]
