# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 09:25
from __future__ import unicode_literals

from django.db import migrations

SQL = """
CREATE INDEX values_value_field_string_value_concat
ON values_value((contact_field_id || '|' || UPPER(string_value)));
"""


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0009_install_indexes'),
    ]

    operations = [
        migrations.RunSQL(SQL)
    ]
