# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 16:22
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('values', '0010_value_indexes'),
    ]

    operations = [
        migrations.RunSQL("""
                CREATE INDEX CONCURRENTLY values_value_field_string_value_concat_new
                ON values_value((contact_field_id || '|' || UPPER(SUBSTRING(string_value, 1, 32))));
        """),
        migrations.RunSQL("DROP INDEX values_value_field_string_value_concat;"),
        migrations.RunSQL("ANALYZE values_value;"),
    ]
