# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 13:26
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0011_new_string_value_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='string_value',
            field=models.TextField(help_text='The string value or string representation of this value'),
        ),
    ]
