# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-15 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0013_remove_nones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='value',
            name='contact_field',
        ),
        migrations.RemoveField(
            model_name='value',
            name='location_value',
        ),
        migrations.RemoveField(
            model_name='value',
            name='org',
        ),
        migrations.RemoveField(
            model_name='value',
            name='ruleset',
        ),
        migrations.RemoveField(
            model_name='value',
            name='run',
        ),
        migrations.DeleteModel(
            name='Value',
        ),
    ]
