# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 22:38
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airtime', '0005_reset_3'),
        ('orgs', '0029_reset_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtimetransfer',
            name='org',
            field=models.ForeignKey(help_text=b'The organization that this airtime was triggered for', on_delete=django.db.models.deletion.CASCADE, to='orgs.Org'),
        ),
    ]
