# Generated by Django 2.1.8 on 2019-07-02 20:05
#
# This is a dummy migration which will be implemented in 5.1
#

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("airtime", "0010_initial")]

    operations = []
