# Generated by Django 5.0.4 on 2024-06-11 17:21

from django.db import migrations, models

import temba.utils.uuid


class Migration(migrations.Migration):

    dependencies = [
        ("airtime", "0027_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="airtimetransfer",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="airtimetransfer",
            name="uuid",
            field=models.UUIDField(default=temba.utils.uuid.uuid4, null=True),
        ),
    ]
