# Generated by Django 5.0.4 on 2024-06-11 17:25

from django.db import migrations

from temba.utils.uuid import uuid4


def populate_uuid(apps, schema_editor):  # pragma: no cover
    AirtimeTransfer = apps.get_model("airtime", "AirtimeTransfer")

    tranfers = AirtimeTransfer.objects.filter(uuid=None)
    for elt in tranfers:
        elt.uuid = uuid4()
        elt.save(update_fields=("uuid",))


class Migration(migrations.Migration):

    dependencies = [
        ("airtime", "0029_airtimetransfer_external_id"),
    ]

    operations = [migrations.RunPython(populate_uuid, migrations.RunPython.noop)]
