# Generated by Django 4.0.8 on 2023-01-11 15:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orgs", "0118_squashed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active, use this instead of deleting"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was originally created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was last modified",
                    ),
                ),
                (
                    "repeat_period",
                    models.CharField(
                        choices=[("O", "Never"), ("D", "Daily"), ("W", "Weekly"), ("M", "Monthly")], max_length=1
                    ),
                ),
                ("repeat_hour_of_day", models.IntegerField(null=True)),
                ("repeat_minute_of_hour", models.IntegerField(null=True)),
                ("repeat_day_of_month", models.IntegerField(null=True)),
                ("repeat_days_of_week", models.CharField(max_length=7, null=True)),
                ("next_fire", models.DateTimeField(null=True)),
                ("last_fire", models.DateTimeField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user which originally created this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="The user which last modified this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_modifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="schedules", to="orgs.org"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                condition=models.Q(("is_active", True), ("next_fire__isnull", False)),
                fields=["next_fire"],
                name="schedules_next_fire_active",
            ),
        ),
    ]
