# Generated by Django 4.2.3 on 2023-11-07 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schedules", "0021_delete_inactive"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="schedule",
            name="schedules_next_fire_active",
        ),
        migrations.AlterField(
            model_name="schedule",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schedules_schedule_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="created_on",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="is_active",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schedules_schedule_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="modified_on",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="next_fire",
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(fields=["next_fire"], name="schedules_due"),
        ),
    ]
