# Generated by Django 4.2.3 on 2023-11-08 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schedules", "0022_remove_schedule_schedules_next_fire_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="modified_on",
        ),
    ]
