# Generated by Django 4.2.3 on 2023-11-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedules", "0023_remove_schedule_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="schedule",
            name="schedules_due",
        ),
        migrations.AddField(
            model_name="schedule",
            name="is_paused",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(condition=models.Q(("is_paused", False)), fields=["next_fire"], name="schedules_due"),
        ),
    ]
