# Generated by Django 4.2.3 on 2023-11-09 18:04

from django.db import migrations


def pause_schedules_of_archived_triggers(apps, schema_editor):  # pragma: no cover
    Schedule = apps.get_model("schedules", "Schedule")

    num_updated = 0

    while True:
        id_batch = list(
            Schedule.objects.filter(is_paused=False, trigger__is_archived=True).values_list("id", flat=True)[:500]
        )
        if not id_batch:
            break

        Schedule.objects.filter(id__in=id_batch).update(is_paused=True)
        num_updated += len(id_batch)

    if num_updated:
        print(f"Paused {num_updated} schedules attached to archived triggers")


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):
    dependencies = [("schedules", "0024_remove_schedule_schedules_due_schedule_is_paused_and_more")]

    operations = [migrations.RunPython(pause_schedules_of_archived_triggers, reverse)]
