# Generated by Django 4.2.3 on 2023-11-13 20:41

from django.db import migrations


def fix_deleted_schedules(apps, schema_editor):
    Schedule = apps.get_model("schedules", "Schedule")

    num_deleted = 0

    ghost_schedules = Schedule.objects.filter(trigger__is_active=False, trigger__trigger_type="S").select_related(
        "trigger"
    )
    for schedule in ghost_schedules:
        trigger = schedule.trigger
        trigger.schedule = None
        trigger.save(update_fields=("schedule",))

        schedule.delete()

        num_deleted += 1

    if num_deleted:
        print(f"Deleted {num_deleted} schedules with deleted triggers")


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [("schedules", "0025_pause_archived_triggers")]

    operations = [migrations.RunPython(fix_deleted_schedules, reverse)]
