# Generated by Django 2.1.5 on 2019-02-13 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apk",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "apk_type",
                    models.CharField(
                        choices=[("R", "Relayer Application APK"), ("M", "Message Pack Application APK")], max_length=1
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Descriptive label for this application APK",
                        max_length=64,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                ("apk_file", models.FileField(upload_to="apks")),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("description", models.TextField(blank=True, default="", null=True)),
            ],
        )
    ]
