# Generated by Django 2.1.8 on 2019-07-02 20:06
#
# This is a dummy migration which will be implemented in 5.1
#

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("apks", "0002_auto_20190319_2109")]

    operations = []
