# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 23:35
from __future__ import unicode_literals

from django.db import migrations
from temba.sql import InstallSQL


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0029_reset_1'),
    ]

    operations = [
        InstallSQL('0030_orgs')
    ]
