# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 23:35
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations
from temba.sql import InstallSQL


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0029_reset_1'),
        ('channels', '0053_reset_4'),
        ('msgs', '0076_install_triggers')
    ]

    operations = [
        InstallSQL('0030_orgs')
    ]
