# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 09:45
from __future__ import unicode_literals

from django.db import migrations, models
from temba.sql import InstallSQL


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0030_install_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='debit',
            name='is_squashed',
            field=models.BooleanField(default=False, help_text='Whether this row was created by squashing'),
        ),
        migrations.AddField(
            model_name='topupcredits',
            name='is_squashed',
            field=models.BooleanField(default=False, help_text='Whether this row was created by squashing'),
        ),
        migrations.RunSQL(
            "CREATE INDEX orgs_debit_unsquashed_purged "
            "ON orgs_debit(topup_id) WHERE NOT is_squashed AND debit_type = 'P'"
        ),
        migrations.RunSQL(
            'CREATE INDEX orgs_topupcredits_unsquashed '
            'ON orgs_topupcredits(topup_id) WHERE NOT is_squashed'
        ),
        InstallSQL('0031_orgs')
    ]
