# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0036_ensure_anon_user_exists'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='flow_user_token',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
