# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 20:46
from __future__ import unicode_literals

from django.db import migrations
from temba.utils.text import random_string


def populate_flow_user_token(apps, schema_editor):
    Org = apps.get_model('orgs', 'Org')
    for org in Org.objects.all():
        org.flow_user_token = random_string(128)
        org.save(update_fields=('flow_user_token',))


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0037_org_flow_user_token'),
    ]

    operations = [
        migrations.RunPython(populate_flow_user_token)
    ]
