# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 16:09
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0037_iso639-3_language_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='flows_last_viewed',
        ),
        migrations.RemoveField(
            model_name='org',
            name='msg_last_viewed',
        ),
    ]
