# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import temba.orgs.models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0038_populate_flow_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='flow_user_token',
            field=models.CharField(default=temba.orgs.models.generate_flow_user_token, help_text='A token that allows requests to authenticate as the flow user', max_length=128, unique=True),
        ),
    ]
