# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 15:38
from __future__ import unicode_literals

from django.db import migrations
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0039_auto_20180124_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='webhook',
            field=temba.utils.models.JSONAsTextField(help_text='Webhook endpoint and configuration', null=True, verbose_name='Webhook'),
        ),
    ]
