# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 19:51
from __future__ import unicode_literals

from django.db import migrations, models


def delete_purge_debits(apps, schema_editor):
    Debit = apps.get_model("orgs", "Debit")
    Debit.objects.filter(debit_type="P").delete()


class Migration(migrations.Migration):

    dependencies = [("orgs", "0039_auto_20180202_1234")]

    operations = [
        migrations.RemoveField(model_name="debit", name="is_squashed"),
        migrations.AlterField(
            model_name="debit",
            name="debit_type",
            field=models.CharField(choices=[("A", "Allocation")], help_text="What caused this debit", max_length=1),
        ),
        migrations.RunPython(delete_purge_debits),
    ]
