# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-22 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0039_auto_20180202_1234'),
        ('orgs', '0037_auto_20170918_1916'),
    ]

    operations = [
    ]
