# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0040_auto_20180130_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='org',
            old_name='webhook',
            new_name='webhook_config',
        ),
    ]
