# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-05 15:46
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orgs", "0040_auto_20180529_1951")]

    operations = [
        migrations.AlterField(
            model_name="creditalert",
            name="org",
            field=models.ForeignKey(
                help_text="The organization this alert was triggered for",
                on_delete=django.db.models.deletion.PROTECT,
                to="orgs.Org",
            ),
        ),
        migrations.AlterField(
            model_name="debit",
            name="beneficiary",
            field=models.ForeignKey(
                help_text="Optional topup that was allocated with these credits",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations",
                to="orgs.TopUp",
            ),
        ),
        migrations.AlterField(
            model_name="debit",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="debits_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="debit",
            name="topup",
            field=models.ForeignKey(
                help_text="The topup these credits are applied against",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="debits",
                to="orgs.TopUp",
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="org",
            field=models.ForeignKey(
                help_text="The organization to which the account is invited to view",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invitations",
                to="orgs.Org",
                verbose_name="Org",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="languages",
                to="orgs.Org",
                verbose_name="Org",
            ),
        ),
        migrations.AlterField(
            model_name="org",
            name="country",
            field=models.ForeignKey(
                blank=True,
                help_text="The country this organization should map results for.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.AdminBoundary",
            ),
        ),
        migrations.AlterField(
            model_name="org",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The parent org that manages this org",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="orgs.Org",
            ),
        ),
        migrations.AlterField(
            model_name="org",
            name="primary_language",
            field=models.ForeignKey(
                blank=True,
                help_text="The primary language will be used for contacts with no language preference.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orgs",
                to="orgs.Language",
            ),
        ),
        migrations.AlterField(
            model_name="topup",
            name="org",
            field=models.ForeignKey(
                help_text="The organization that was toppped up",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="topups",
                to="orgs.Org",
            ),
        ),
        migrations.AlterField(
            model_name="topupcredits",
            name="topup",
            field=models.ForeignKey(
                help_text="The topup these credits are being used against",
                on_delete=django.db.models.deletion.PROTECT,
                to="orgs.TopUp",
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="settings", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
