# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-15 16:40
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

DEBIT_TRIGGER = """
----------------------------------------------------------------------------------
-- Updates our topup credits for the topup being assigned to a Debit
----------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION temba_update_topupcredits_for_debit() RETURNS TRIGGER AS $$
BEGIN
  -- Debit is being created
  IF TG_OP = 'INSERT' THEN
    -- If we are an allocation and have a topup, increment our # of used credits
    IF NEW.topup_id IS NOT NULL AND NEW.debit_type = 'A' THEN
      PERFORM temba_insert_topupcredits(NEW.topup_id, NEW.amount);
    END IF;
  END IF;

  RETURN NULL;
END;
$$ LANGUAGE plpgsql;
"""


class Migration(migrations.Migration):

    dependencies = [("orgs", "0042_auto_20180615_2040")]

    operations = [
        migrations.RunSQL(DEBIT_TRIGGER),
        migrations.AlterField(
            model_name="debit",
            name="topup",
            field=models.ForeignKey(
                help_text="The topup these credits are applied against",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="debits",
                to="orgs.TopUp",
            ),
        ),
    ]
