# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-21 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("orgs", "0042_auto_20180615_2040")]

    operations = [migrations.RemoveField(model_name="org", name="is_purgeable")]
