# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-29 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0044_auto_20180616_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='apply_notification',
            field=models.BooleanField(default=False, help_text='Whether this organization auto_accepted the migration of staging to production'),
        ),
        migrations.AlterField(
            model_name='org',
            name='brand',
            field=models.CharField(default='rapidpro.datos.gob.mx', help_text='The brand used in emails', max_length=128, verbose_name='Brand'),
        ),
    ]
