# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0048_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='brand',
            field=models.CharField(default='rapidpro.datos.gob.mx', help_text='The brand used in emails', max_length=128, verbose_name='Brand'),
        ),
    ]
