# Generated by Django 2.0.8 on 2018-10-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orgs", "0048_triggers")]

    operations = [
        migrations.AddField(
            model_name="org",
            name="flow_server_enabled",
            field=models.BooleanField(
                default=False, help_text="Whether flows and messages should be handled by the flow server"
            ),
        )
    ]
