# Generated by Django 2.0.8 on 2018-10-22 13:44

from urllib.parse import urlencode

from django.db import migrations


def populate_smtp_server_config(apps, schema_editor):
    Org = apps.get_model("orgs", "Org")

    orgs = Org.objects.filter(config__icontains="smtp")
    for org in orgs:
        config = org.config

        smtp_from_email = config.get("SMTP_FROM_EMAIL", "")
        smtp_host = config.get("SMTP_HOST", "")
        smtp_username = config.get("SMTP_USERNAME", "")
        smtp_password = config.get("SMTP_PASSWORD", "")
        smtp_port = config.get("SMTP_PORT", "")
        use_tls = config.get("SMTP_ENCRYPTION", "") == "T"

        query = urlencode({"from": smtp_from_email, "tls": str(use_tls).lower()})

        org.config["smtp_server"] = f"smtp://{smtp_username}:{smtp_password}@{smtp_host}:{smtp_port}/?{query}"
        del org.config["SMTP_ENCRYPTION"]
        del org.config["SMTP_FROM_EMAIL"]
        del org.config["SMTP_HOST"]
        del org.config["SMTP_PORT"]
        del org.config["SMTP_USERNAME"]
        del org.config["SMTP_PASSWORD"]

        org.save()


class Migration(migrations.Migration):

    dependencies = [("orgs", "0049_org_flow_server_enabled")]

    operations = [migrations.RunPython(populate_smtp_server_config)]
