# Generated by Django 2.0.8 on 2018-11-08 15:03

import uuid

from django.db import migrations, models


def populate_org_uuid(apps, schema_editor):
    Org = apps.get_model("orgs", "Org")
    for org in Org.objects.all():
        org.uuid = uuid.uuid4()
        org.save(update_fields=("uuid",))


class Migration(migrations.Migration):

    dependencies = [("orgs", "0051_org_uuid")]

    operations = [
        migrations.RunPython(populate_org_uuid),
        migrations.AlterField(model_name="org", name="uuid", field=models.UUIDField(default=uuid.uuid4, unique=True)),
    ]
