# Generated by Django 2.1.8 on 2019-06-11 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("orgs", "0053_migrate_all_orgs")]

    operations = [
        migrations.RemoveField(model_name="org", name="webhook"),
        migrations.RemoveField(model_name="org", name="webhook_events"),
    ]
