# Generated by Django 2.1.8 on 2019-07-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orgs", "0055_initial")]

    operations = [
        migrations.AlterField(model_name="org", name="flow_server_enabled", field=models.BooleanField(null=True))
    ]
