# Generated by Django 2.1.9 on 2020-05-04 14:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orgs", "0058_auto_20190723_2129")]

    operations = [
        migrations.AddField(
            model_name="creditalert",
            name="admin_emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                default=list,
                help_text="Emails of administrators who will be alerted",
                size=None,
            ),
        )
    ]
