# Generated by Django 2.2.4 on 2020-04-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orgs", "0058_auto_20190723_2129")]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="otp_secret",
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name="OTP Secret"),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="two_factor_enabled",
            field=models.BooleanField(default=False, verbose_name="Two Factor Enabled"),
        ),
    ]
