# Generated by Django 2.2.4 on 2020-12-01 13:35

from django.db import migrations
from django.db.migrations import RunPython


def add_parent_org_admins(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Org = apps.get_model("orgs", "Org")
    nested_orgs = Org.objects.using(db_alias).exclude(parent__isnull=True)
    for org in nested_orgs:
        org.administrators.add(*org.parent.administrators.all())


def remove_parent_org_admins(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Org = apps.get_model("orgs", "Org")
    nested_orgs = Org.objects.using(db_alias).exclude(parent__isnull=True)
    for org in nested_orgs:
        org.administrators.clear()
        if org.created_by not in org.administrators.all():
            org.administrators.add(org.created_by)


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0060_merge_20200510_1733'),
    ]

    operations = [
        RunPython(add_parent_org_admins, remove_parent_org_admins)
    ]
