# Generated by Django 2.2.4 on 2020-05-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orgs", "0060_backuptoken")]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en-us", "English"),
                    ("pt-br", "Portuguese"),
                    ("fr", "French"),
                    ("es", "Spanish"),
                    ("ru", "Russian"),
                ],
                help_text="The main language used by this organization",
                max_length=64,
                null=True,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="language",
            field=models.CharField(
                choices=[
                    ("en-us", "English"),
                    ("pt-br", "Portuguese"),
                    ("fr", "French"),
                    ("es", "Spanish"),
                    ("ru", "Russian"),
                ],
                default="en-us",
                help_text="Your preferred language",
                max_length=8,
            ),
        ),
    ]
