# Generated by Django 2.2.4 on 2020-06-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orgs", "0062_orgactivity")]

    operations = [
        migrations.RemoveField(model_name="org", name="plan_start"),
        migrations.AddField(
            model_name="org",
            name="is_flagged",
            field=models.BooleanField(help_text="Whether this organization is currently flagged.", null=True),
        ),
        migrations.AddField(
            model_name="org",
            name="is_suspended",
            field=models.BooleanField(help_text="Whether this organization is currently suspended.", null=True),
        ),
        migrations.AddField(
            model_name="org",
            name="uses_topups",
            field=models.BooleanField(help_text="Whether this organization uses topups.", null=True),
        ),
        migrations.AlterField(
            model_name="org",
            name="plan",
            field=models.CharField(
                default="topups", help_text="What plan your organization is on", max_length=16, verbose_name="Plan"
            ),
        ),
        migrations.AlterField(
            model_name="org",
            name="is_flagged",
            field=models.BooleanField(
                default=False, help_text="Whether this organization is currently flagged.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="org",
            name="is_suspended",
            field=models.BooleanField(
                default=False, help_text="Whether this organization is currently suspended.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="org",
            name="uses_topups",
            field=models.BooleanField(default=True, help_text="Whether this organization uses topups.", null=True),
        ),
    ]
