# Generated by Django 2.2.4 on 2020-06-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orgs", "0064_populate_new_org_fields")]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="is_flagged",
            field=models.BooleanField(default=False, help_text="Whether this organization is currently flagged."),
        ),
        migrations.AlterField(
            model_name="org",
            name="is_suspended",
            field=models.BooleanField(default=False, help_text="Whether this organization is currently suspended."),
        ),
        migrations.AlterField(
            model_name="org",
            name="uses_topups",
            field=models.BooleanField(default=True, help_text="Whether this organization uses topups."),
        ),
    ]
