# Generated by Django 2.2.4 on 2020-09-25 18:41

from dateutil.relativedelta import relativedelta

from django.db import migrations


def populate_plan_start(apps, schema_editor):  # pragma: no cover
    Org = apps.get_model("orgs", "Org")

    for org in Org.objects.exclude(plan_end=None):
        org.plan_start = org.plan_end - relativedelta(months=1)
        org.save(update_fields=["plan_start"])


def reverse(apps, schema_editor):  # pragma: no cover
    pass


def apply_manual():  # pragma: no cover
    from django.apps import apps

    populate_plan_start(apps, None)


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0069_plan_start"),
    ]

    operations = [migrations.RunPython(populate_plan_start, reverse)]
