# Generated by Django 2.2.4 on 2020-12-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0059_squashed_ccl_0059_0061'),
        ('orgs', '0072_squashed'),
    ]

    operations = [
    ]
