# Generated by Django 2.2.10 on 2021-02-04 16:43

from django.db import migrations


def populate_backup_token_user(apps, schema_editor):
    BackupToken = apps.get_model("orgs", "BackupToken")
    for token in BackupToken.objects.all():
        token.user = token.settings.user
        token.save(update_fields=("user",))


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0075_auto_20210204_1638"),
    ]

    operations = [
        migrations.RunPython(populate_backup_token_user),
    ]
