# Generated by Django 2.2.10 on 2021-02-04 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0076_populate_backup_token_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backuptoken",
            name="settings",
        ),
        migrations.AlterField(
            model_name="backuptoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="backup_tokens", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
