# Generated by Django 2.2.10 on 2021-02-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0077_auto_20210204_1654"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="tel",
        ),
        migrations.AddField(
            model_name="usersettings",
            name="last_auth_on",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="language",
            field=models.CharField(
                choices=[
                    ("en-us", "English"),
                    ("pt-br", "Portuguese"),
                    ("fr", "French"),
                    ("es", "Spanish"),
                    ("ru", "Russian"),
                ],
                default="en-us",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="two_factor_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
