# Generated by Django 2.2.19 on 2021-03-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0079_org_limits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="date_format",
            field=models.CharField(
                choices=[("D", "DD-MM-YYYY"), ("M", "MM-DD-YYYY"), ("Y", "YYYY-MM-DD")],
                default="D",
                help_text="Whether day comes first or month comes first in dates",
                max_length=1,
                verbose_name="Date Format",
            ),
        ),
    ]
