# Generated by Django 2.2.10 on 2021-05-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0080_auto_20210325_1059'),
        ('orgs', '0073_merge_20201214_1542'),
    ]

    operations = [
    ]
