# Generated by Django 2.2.10 on 2021-04-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0080_auto_20210325_1059"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="released_on",
            field=models.DateTimeField(null=True),
        ),
    ]
