# Generated by Django 2.2.20 on 2021-04-20 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0082_org_released_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="languages", to="orgs.Org"
            ),
        ),
    ]
