# Generated by Django 2.2.20 on 2021-05-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0083_auto_20210420_2230"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="deleted_on",
            field=models.DateTimeField(null=True),
        ),
    ]
