# Generated by Django 2.2.20 on 2021-06-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0086_populate_org_flow_languages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="org",
            name="primary_language",
        ),
        migrations.DeleteModel(
            name="Language",
        ),
    ]
