# Generated by Django 2.2.20 on 2021-07-15 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0087_auto_20210621_1642"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topupcredits",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="topupcredits",
            name="is_squashed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="topupcredits",
            name="topup",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="orgs.TopUp"),
        ),
        migrations.AlterField(
            model_name="topupcredits",
            name="used",
            field=models.IntegerField(),
        ),
    ]
