# Generated by Django 3.2.8 on 2021-11-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0088_auto_20210715_1825"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="language",
            field=models.CharField(
                choices=[
                    ("en-us", "English"),
                    ("cs", "Czech"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("mn", "Mongolian"),
                    ("pt-br", "Portuguese"),
                    ("ru", "Russian"),
                ],
                default="en-us",
                help_text="The default website language for new users.",
                max_length=64,
                null=True,
                verbose_name="Default Language",
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="language",
            field=models.CharField(
                choices=[
                    ("en-us", "English"),
                    ("cs", "Czech"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("mn", "Mongolian"),
                    ("pt-br", "Portuguese"),
                    ("ru", "Russian"),
                ],
                default="en-us",
                max_length=8,
            ),
        ),
    ]
