# Generated by Django 4.0.2 on 2022-02-14 11:13

from django.db import migrations

import temba.utils.json
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0091_alter_creditalert_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="api_rates",
            field=temba.utils.models.JSONField(
                decoder=temba.utils.json.TembaDecoder, default=dict, encoder=temba.utils.json.TembaEncoder
            ),
        ),
    ]
