# Generated by Django 4.0.3 on 2022-03-17 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0093_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="parent",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="children", to="orgs.org"
            ),
        ),
    ]
