# Generated by Django 4.0.4 on 2022-05-05 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0031_team_ticketdailycount_and_more"),
        ("orgs", "0094_alter_org_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="team",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="tickets.team"),
        ),
    ]
