# Generated by Django 4.0.4 on 2022-05-19 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0096_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backuptoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="backup_tokens", to="orgs.user"
            ),
        ),
        migrations.AlterField(
            model_name="org",
            name="administrators",
            field=models.ManyToManyField(related_name="org_admins", to="orgs.user"),
        ),
        migrations.AlterField(
            model_name="org",
            name="agents",
            field=models.ManyToManyField(related_name="org_agents", to="orgs.user"),
        ),
        migrations.AlterField(
            model_name="org",
            name="editors",
            field=models.ManyToManyField(related_name="org_editors", to="orgs.user"),
        ),
        migrations.AlterField(
            model_name="org",
            name="surveyors",
            field=models.ManyToManyField(related_name="org_surveyors", to="orgs.user"),
        ),
        migrations.AlterField(
            model_name="org",
            name="viewers",
            field=models.ManyToManyField(related_name="org_viewers", to="orgs.user"),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="usersettings", to="orgs.user"
            ),
        ),
    ]
