# Generated by Django 4.0.4 on 2022-06-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0100_alter_org_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="org",
            name="administrators",
        ),
        migrations.RemoveField(
            model_name="org",
            name="agents",
        ),
        migrations.RemoveField(
            model_name="org",
            name="editors",
        ),
        migrations.RemoveField(
            model_name="org",
            name="surveyors",
        ),
        migrations.RemoveField(
            model_name="org",
            name="viewers",
        ),
    ]
