# Generated by Django 4.0.7 on 2022-11-01 18:30

from django.conf import settings
from django.db import migrations


def get_branding(host: str) -> dict:  # pragma: no cover
    """
    Returns the branding for the given host
    """
    for brand in settings.BRANDS:
        # in case it's already a slug
        if host == brand["slug"]:
            return brand

        if host in brand["hosts"]:
            return brand

    return get_branding(settings.DEFAULT_BRAND)


def convert_org_brands_to_slugs(apps, schema_editor):  # pragma: no cover
    Org = apps.get_model("orgs", "Org")
    for org in Org.objects.all():
        org.brand = get_branding(org.brand)["slug"]
        org.save(update_fields=("brand",))


def reverse(apps, schewma_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0102_alter_org_brand_alter_org_plan"),
    ]

    operations = [migrations.RunPython(convert_org_brands_to_slugs, reverse)]
