# Generated by Django 4.0.7 on 2022-11-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("orgs", "0106_update_db_triggers"), ("msgs", "0200_remove_msg_topup")]

    operations = [
        migrations.RemoveField(
            model_name="topup",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="topup",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="topup",
            name="org",
        ),
        migrations.DeleteModel(
            name="Debit",
        ),
        migrations.DeleteModel(
            name="TopUp",
        ),
        migrations.RemoveField(
            model_name="org",
            name="uses_topups",
        ),
    ]
