# Generated by Django 4.0.7 on 2022-11-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0108_simplify_org_hierarchies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="plan",
            field=models.CharField(default="rapidpro", max_length=16, verbose_name="Plan"),
        ),
    ]
