# Generated by Django 4.0.7 on 2022-11-22 21:53

from django.db import migrations

FEATURE_USERS = "users"
FEATURE_NEW_ORGS = "new_orgs"
FEATURE_CHILD_ORGS = "child_orgs"


def populate_features(apps, schema_editor):  # pragma: no cover
    Org = apps.get_model("orgs", "Org")
    for org in Org.objects.all():
        org.features = []
        if org.is_multi_user:
            org.features.append(FEATURE_USERS)
        if org.is_multi_org:
            org.features.append(FEATURE_NEW_ORGS)
            org.features.append(FEATURE_CHILD_ORGS)

        org.save(update_fields=("features",))


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0112_alter_org_is_multi_org_alter_org_is_multi_user"),
    ]

    operations = [migrations.RunPython(populate_features)]
