# Generated by Django 4.0.7 on 2022-11-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0114_remove_org_is_multi_org_remove_org_is_multi_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="plan",
            field=models.CharField(max_length=16, null=True, verbose_name="Plan", blank=True),
        ),
    ]
