# Generated by Django 4.0.8 on 2023-01-03 16:51

import django.contrib.postgres.fields
import django.contrib.postgres.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0116_default_flow_languages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="flow_languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=3),
                default=list,
                size=None,
                validators=[django.contrib.postgres.validators.ArrayMinLengthValidator(1)],
            ),
        ),
    ]
