# Generated by Django 4.1.7 on 2023-03-13 18:52

from django.db import migrations


def backfill_empty_configs(apps, schema_editor):  # pragma: no cover
    Org = apps.get_model("orgs", "Org")
    Org.objects.filter(config=None).update(config={})


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):
    dependencies = [("orgs", "0119_squashed")]

    operations = [migrations.RunPython(backfill_empty_configs, reverse)]
