# Generated by Django 4.2.3 on 2023-08-01 19:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("orgs", "0125_orgimport")]

    operations = [migrations.RemoveField(model_name="org", name="brand")]
