# Generated by Django 4.2.3 on 2023-08-17 14:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0126_remove_org_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="input_cleaners",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32), default=list, size=None
            ),
        ),
    ]
