# Generated by Django 4.2.3 on 2023-08-21 18:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0127_org_input_cleaners"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="input_collation",
            field=models.CharField(default="default", max_length=32),
        ),
        migrations.AlterField(
            model_name="org",
            name="input_cleaners",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32), null=True, size=None
            ),
        ),
    ]
