# Generated by Django 4.2.3 on 2023-10-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0129_remove_org_input_cleaners"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="email_status",
            field=models.CharField(
                choices=[("U", "Unverified"), ("V", "Verified"), ("F", "Failing")], default="U", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="email_verification_secret",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
