# Generated by Django 4.2.8 on 2024-01-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0135_export"),
    ]

    operations = [
        migrations.AddField(
            model_name="export",
            name="path",
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
