# Generated by Django 4.2.8 on 2024-02-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0136_export_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="flow_smtp",
            field=models.CharField(null=True),
        ),
    ]
