# Generated by Django 4.2.8 on 2024-02-08 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0139_usersettings_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, related_name="usersettings", to="orgs.user"
            ),
        ),
    ]
