# Generated by Django 5.0.3 on 2024-04-05 16:34

from django.db import migrations


def backfill_user_settings(apps, schema_editor):
    User = apps.get_model("orgs", "User")
    UserSettings = apps.get_model("orgs", "UserSettings")

    num_created = 0
    for user in User.objects.filter(usersettings=None):
        UserSettings.objects.create(user=user)
        num_created += 1

    if num_created:
        print(f"Backfilled {num_created} missing user settings")


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [("orgs", "0140_alter_usersettings_user")]

    operations = [migrations.RunPython(backfill_user_settings, reverse)]
