# Generated by Django 5.0.3 on 2024-04-05 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0141_backfill_user_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, related_name="settings", to="orgs.user"
            ),
        ),
    ]
