# Generated by Django 5.0.4 on 2024-06-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0143_backfill_email_verification_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="email_verification_secret",
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
