# Generated by Django 5.0.7 on 2024-08-07 15:48

from django.db import migrations


def remove_surveyor_users(apps, schema_editor):  # pragma: no cover
    OrgMembership = apps.get_model("orgs", "OrgMembership")

    num_deleted, _ = OrgMembership.objects.filter(role_code="S").delete()
    if num_deleted:
        print(f"Removed {num_deleted} surveyor users from workspaces")


class Migration(migrations.Migration):

    dependencies = [("orgs", "0144_alter_usersettings_email_verification_secret")]

    operations = [migrations.RunPython(remove_surveyor_users, migrations.RunPython.noop)]
