# Generated by Django 5.0.7 on 2024-08-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0146_alter_invitation_user_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="org",
            name="surveyor_password",
        ),
    ]
