# Generated by Django 5.0.7 on 2024-08-07 19:22

from django.db import migrations


def remove_viewers_feature(apps, schema_editor):  # pragma: no cover
    Org = apps.get_model("orgs", "Org")

    num_removed = 0

    for org in Org.objects.filter(features__contains=["viewers"]):
        org.features.remove("viewers")
        org.save(update_fields=["features"])
        num_removed += 1

    if num_removed:
        print(f"Removed 'viewers' feature from {num_removed} orgs")


class Migration(migrations.Migration):

    dependencies = [("orgs", "0147_remove_org_surveyor_password")]

    operations = [migrations.RunPython(remove_viewers_feature, migrations.RunPython.noop)]
