# Generated by Django 5.0.8 on 2024-08-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0148_remove_viewers_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="prometheus_token",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
