# Generated by Django 5.0.8 on 2024-08-07 20:20

from django.db import migrations


def backfill_prometheus_token(apps, schema_editor):  # pragma: no cover
    APIToken = apps.get_model("api", "APIToken")

    for token in APIToken.objects.filter(is_active=True, role__name="Prometheus"):
        token.org.prometheus_token = token.key
        token.org.save(update_fields=("prometheus_token",))


class Migration(migrations.Migration):

    dependencies = [("orgs", "0149_org_prometheus_token")]

    operations = [migrations.RunPython(backfill_prometheus_token, migrations.RunPython.noop)]
