# Generated by Django 5.0.8 on 2024-08-13 19:49

import storages.backends.s3

from django.db import migrations, models

import temba.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0150_backfill_org_prometheus_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="avatar",
            field=models.ImageField(
                null=True,
                storage=storages.backends.s3.S3Storage(
                    bucket_name="temba-default",
                    default_acl="public-read",
                    querystring_auth=False,
                    signature_version="s3v4",
                ),
                upload_to=temba.utils.fields.UploadToIdPathAndRename("avatars/"),
            ),
        ),
    ]
