# Generated by Django 5.1 on 2024-10-16 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0152_alter_invitation_user_group"),
        ("tickets", "0064_shortcut"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="role_code",
            field=models.CharField(
                choices=[("A", "Administrator"), ("E", "Editor"), ("T", "Agent")], default="E", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="team",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="tickets.team"),
        ),
        migrations.AddField(
            model_name="orgmembership",
            name="team",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="tickets.team"),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="user_group",
            field=models.CharField(
                choices=[("A", "Administrator"), ("E", "Editor"), ("T", "Agent")], default="E", max_length=1
            ),
        ),
    ]
