# Generated by Django 5.1 on 2024-10-16 22:10

from django.db import migrations


def backfill_invitation_role(apps, schema_editor):  # pragma: no cover
    Invitation = apps.get_model("orgs", "Invitation")

    for invitation in Invitation.objects.all():
        invitation.role_code = invitation.user_group
        invitation.save(update_fields=("role_code",))


class Migration(migrations.Migration):

    dependencies = [("orgs", "0153_invitation_role_code_invitation_team_and_more")]

    operations = [migrations.RunPython(backfill_invitation_role, migrations.RunPython.noop)]
