# Generated by Django 5.1.2 on 2024-11-05 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0156_itemcount"),
        ("tickets", "0072_drop_old_triggers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="team",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="invitations", to="tickets.team"
            ),
        ),
    ]
