# Generated by Django 5.1.2 on 2024-11-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0157_alter_invitation_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="suspended_on",
            field=models.DateTimeField(null=True),
        ),
    ]
