# Generated by Django 5.1.2 on 2024-11-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0158_org_suspended_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
    ]
