# Generated by Django 5.1.2 on 2024-12-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0160_alter_itemcount_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcount",
            name="count",
            field=models.IntegerField(),
        ),
    ]
