# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 17:43
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170228_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookresult',
            name='request_time',
            field=models.IntegerField(help_text='Time it took to process this request', null=True),
        ),
    ]
