# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-15 20:40
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0017_auto_20180129_1533")]

    operations = [
        migrations.AlterField(
            model_name="apitoken",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="api_tokens", to="orgs.Org"
            ),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="role",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="auth.Group"),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="api_tokens", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="resthook",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="api_resthook_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="resthook",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="api_resthook_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="resthook",
            name="org",
            field=models.ForeignKey(
                help_text="The organization this resthook belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resthooks",
                to="orgs.Org",
            ),
        ),
        migrations.AlterField(
            model_name="resthooksubscriber",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="api_resthooksubscriber_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="resthooksubscriber",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="api_resthooksubscriber_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="resthooksubscriber",
            name="resthook",
            field=models.ForeignKey(
                help_text="The resthook being subscribed to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscribers",
                to="api.Resthook",
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                help_text="The channel that this event is relating to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="channels.Channel",
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="api_webhookevent_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="api_webhookevent_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="org",
            field=models.ForeignKey(
                help_text="The organization that this event was triggered for",
                on_delete=django.db.models.deletion.PROTECT,
                to="orgs.Org",
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="resthook",
            field=models.ForeignKey(
                help_text="The associated resthook to this event. (optional)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.Resthook",
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="run",
            field=models.ForeignKey(
                help_text="The flow run that triggered this event",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="flows.FlowRun",
            ),
        ),
        migrations.AlterField(
            model_name="webhookresult",
            name="contact",
            field=models.ForeignKey(
                help_text="The contact that generated this result",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="webhook_results",
                to="contacts.Contact",
            ),
        ),
        migrations.AlterField(
            model_name="webhookresult",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="api_webhookresult_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="webhookresult",
            name="event",
            field=models.ForeignKey(
                help_text="The event that this result is tied to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="results",
                to="api.WebHookEvent",
            ),
        ),
        migrations.AlterField(
            model_name="webhookresult",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="api_webhookresult_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
