# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-19 17:22
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0018_auto_20180615_2040")]

    operations = [
        migrations.AlterField(
            model_name="webhookevent",
            name="run",
            field=models.ForeignKey(
                help_text="The flow run that triggered this event",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="webhook_events",
                to="flows.FlowRun",
            ),
        )
    ]
