# Generated by Django 2.1.5 on 2019-01-29 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orgs", "0052_populate_org_uuid"), ("api", "0021_indexes")]

    operations = [
        migrations.AddField(
            model_name="webhookresult",
            name="org",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="webhook_results", to="orgs.Org"
            ),
        )
    ]
