# Generated by Django 2.1.5 on 2019-01-29 20:20

import django.db.models.deletion
from django.db import migrations, models


def populate_org_id(apps, schema_editor):
    WebHookResult = apps.get_model("api", "WebHookResult")

    for res in WebHookResult.objects.all().select_related("event"):
        res.org_id = res.event.org_id
        res.save(update_fields=["org_id"])


class Migration(migrations.Migration):

    dependencies = [("api", "0022_webhookresult_org")]

    operations = [
        migrations.RunPython(populate_org_id),
        migrations.AlterField(
            model_name="webhookresult",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="webhook_results", to="orgs.Org"
            ),
        ),
    ]
