# Generated by Django 2.1.5 on 2019-02-08 21:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [("api", "0026_auto_20190129_2156")]

    operations = [
        migrations.RemoveField(model_name="webhookevent", name="created_by"),
        migrations.RemoveField(model_name="webhookevent", name="is_active"),
        migrations.RemoveField(model_name="webhookevent", name="modified_by"),
        migrations.RemoveField(model_name="webhookevent", name="modified_on"),
        migrations.AlterField(
            model_name="webhookevent", name="action", field=models.CharField(default="POST", max_length=8)
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="channel",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="channels.Channel"
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="created_on",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name="webhookevent", name="data", field=temba.utils.models.JSONAsTextField(default=dict)
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("mo_sms", "Incoming SMS Message"),
                    ("mt_sent", "Outgoing SMS Sent"),
                    ("mt_dlvd", "Outgoing SMS Delivered to Recipient"),
                    ("mt_fail", "Outgoing SMS Failed to be Delivered to Recipient"),
                    ("mt_call", "Outgoing Call"),
                    ("mt_miss", "Missed Outgoing Call"),
                    ("mo_call", "Incoming Call"),
                    ("mo_miss", "Missed Incoming Call"),
                    ("alarm", "Channel Alarm"),
                    ("flow", "Flow Step Reached"),
                    ("categorize", "Flow Categorization"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent", name="next_attempt", field=models.DateTimeField(blank=True, null=True)
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="org",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="orgs.Org"),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="resthook",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="api.Resthook"),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="run",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="webhook_events",
                to="flows.FlowRun",
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("C", "Complete"), ("E", "Errored"), ("F", "Failed")],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AlterField(model_name="webhookevent", name="try_count", field=models.IntegerField(default=0)),
    ]
