# Generated by Django 2.1.8 on 2019-06-06 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0027_auto_20190208_2126")]

    operations = [
        migrations.RemoveField(model_name="webhookevent", name="channel"),
        migrations.RemoveField(model_name="webhookevent", name="next_attempt"),
        migrations.RemoveField(model_name="webhookevent", name="run"),
        migrations.RemoveField(model_name="webhookevent", name="try_count"),
    ]
