# Generated by Django 2.2.10 on 2020-12-04 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0032_squashed"),
        ("auth", "0011_update_proxy_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orgs", "0072_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookresult",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="webhook_results", to="orgs.Org"
            ),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="org",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="orgs.Org"),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="resthook",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="api.Resthook"),
        ),
        migrations.AddField(
            model_name="resthooksubscriber",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="api_resthooksubscriber_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resthooksubscriber",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="api_resthooksubscriber_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resthooksubscriber",
            name="resthook",
            field=models.ForeignKey(
                help_text="The resthook being subscribed to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscribers",
                to="api.Resthook",
            ),
        ),
        migrations.AddField(
            model_name="resthook",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="api_resthook_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resthook",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="api_resthook_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resthook",
            name="org",
            field=models.ForeignKey(
                help_text="The organization this resthook belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resthooks",
                to="orgs.Org",
            ),
        ),
        migrations.AddField(
            model_name="apitoken",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="api_tokens", to="orgs.Org"
            ),
        ),
        migrations.AddField(
            model_name="apitoken",
            name="role",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="auth.Group"),
        ),
        migrations.AddField(
            model_name="apitoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="api_tokens", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
