# Generated by Django 4.0.3 on 2022-03-10 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orgs", "0093_squashed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("api", "0036_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookevent",
            name="org",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="orgs.org"),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="resthook",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="api.resthook"),
        ),
        migrations.AddField(
            model_name="resthooksubscriber",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resthooksubscriber",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resthooksubscriber",
            name="resthook",
            field=models.ForeignKey(
                help_text="The resthook being subscribed to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscribers",
                to="api.resthook",
            ),
        ),
        migrations.AddField(
            model_name="resthook",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resthook",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resthook",
            name="org",
            field=models.ForeignKey(
                help_text="The organization this resthook belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resthooks",
                to="orgs.org",
            ),
        ),
        migrations.AddField(
            model_name="apitoken",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="api_tokens", to="orgs.org"
            ),
        ),
        migrations.AddField(
            model_name="apitoken",
            name="role",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="auth.group"),
        ),
        migrations.AddField(
            model_name="apitoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="api_tokens", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
