# Generated by Django 4.0.4 on 2022-05-24 21:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_alter_apitoken_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitoken",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
