# Generated by Django 5.0.8 on 2024-08-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_delete_surveyor_and_prometheus_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="last_used_on",
            field=models.DateTimeField(null=True),
        ),
    ]
