# Generated by Django 2.2.4 on 2019-11-11 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("classifiers", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="classifier",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="classifiers", to="orgs.Org"
            ),
        )
    ]
