# Generated by Django 4.0.3 on 2022-03-10 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classifiers", "0006_squashed"),
        ("orgs", "0093_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="classifier",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="classifiers", to="orgs.org"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="intent",
            unique_together={("classifier", "external_id")},
        ),
    ]
