# Generated by Django 4.0.8 on 2023-01-11 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classifiers", "0010_squashed"),
        ("orgs", "0118_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="classifier",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="classifiers", to="orgs.org"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="intent",
            unique_together={("classifier", "external_id")},
        ),
    ]
