# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-16 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_auto_20180515_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='archive_size',
            field=models.BigIntegerField(default=0, help_text='The size of this archive in bytes (after gzipping)'),
        ),
    ]
