# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-17 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_auto_20180515_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='period',
            field=models.CharField(choices=[('D', 'Day'), ('M', 'Month')], default='D', help_text='The period category for this archive since the start date', max_length=1),
        ),
        migrations.AddField(
            model_name='archive',
            name='rollup',
            field=models.ForeignKey(help_text='The rollup archive for this month', null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.Archive'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='archive_size',
            field=models.BigIntegerField(default=0, help_text='The size of this archive in bytes (after gzipping)'),
        ),
    ]
