# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-17 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def populate_archive_period(apps, schema_editor):
        Archive = apps.get_model('archives', 'Archive')
        archives = Archive.objects.all()
        for archive in archives:
            if (archive.end_date - archive.start_date).days > 1:
                archive.period = 'M'
            else:
                archive.period = 'D'
            archive.save()

    dependencies = [
        ('archives', '0003_auto_20180517_1528'),
    ]

    operations = [
        migrations.RunPython(populate_archive_period)
    ]
