# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-01 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("archives", "0004_auto_20180522_1502")]

    operations = [
        migrations.RemoveField(model_name="archive", name="is_purged"),
        migrations.AddField(
            model_name="archive",
            name="needs_deletion",
            field=models.BooleanField(
                default=False, help_text="Whether the records in this archive need to be deleted"
            ),
        ),
    ]
