# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-17 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_populate_archive_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='end_date',
        ),
    ]
