# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-05 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orgs", "0040_auto_20180529_1951"), ("archives", "0005_auto_20180601_1836")]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="deletion_date",
            field=models.DateTimeField(help_text="When this archive's records where deleted (if any)", null=True),
        ),
        migrations.AlterUniqueTogether(
            name="archive", unique_together=set([("org", "archive_type", "start_date", "period")])
        ),
    ]
