# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-15 20:40
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("archives", "0007_auto_20180611_1542")]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="org",
            field=models.ForeignKey(
                db_constraint=False,
                help_text="The org this archive is for",
                on_delete=django.db.models.deletion.PROTECT,
                to="orgs.Org",
            ),
        ),
        migrations.AlterField(
            model_name="archive",
            name="rollup",
            field=models.ForeignKey(
                help_text="The archive we were rolled up into, if any",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="archives.Archive",
            ),
        ),
    ]
