# Generated by Django 4.0.8 on 2023-01-11 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archive_type", models.CharField(choices=[("message", "Message"), ("run", "Run")], max_length=16)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("period", models.CharField(choices=[("D", "Day"), ("M", "Month")], default="D", max_length=1)),
                ("start_date", models.DateField()),
                ("record_count", models.IntegerField(default=0)),
                ("size", models.BigIntegerField(default=0)),
                ("hash", models.TextField()),
                ("url", models.URLField()),
                ("needs_deletion", models.BooleanField(default=False)),
                ("build_time", models.IntegerField()),
                ("deleted_on", models.DateTimeField(null=True)),
            ],
        ),
    ]
