# Generated by Django 4.2.8 on 2024-01-05 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orgs", "0133_squashed"),
        ("archives", "0019_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="archives",
                to="orgs.org",
            ),
        ),
        migrations.AddField(
            model_name="archive",
            name="rollup",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="archives.archive",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="archive",
            unique_together={("org", "archive_type", "start_date", "period")},
        ),
    ]
