name: rapidpro
user: ubuntu
buildscript: sideloader/deploy.sh
postinstall: sideloader/postinstall.sh
pip:
  - gunicorn
dependencies:
  - postgresql-9.3
  - postgresql-9.3-postgis-2.1
  - libpq-dev
  - build-essential
  - nodejs
  - npm
