version: '2'
services:
  rapidpro:
    image: rapidpro/rapidpro:master
    depends_on:
      - redis
      - postgresql
    ports:
      - '8000:8000'
    environment:
      - DOMAIN_NAME=localhost
      - ALLOWED_HOSTS=localhost
      - TEMBA_HOST=localhost
      - DJANGO_DEBUG=off
      - DATABASE_URL=postgresql://postgres:postgres@postgresql/rapidpro
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=super-secret-key
      - MANAGEPY_COLLECTSTATIC=on
      - MANAGEPY_COMPRESS=on
      - MANAGEPY_INIT_DB=off
      - MANAGEPY_MIGRATE=off
  celery:
    image: rapidpro/rapidpro:master
    depends_on:
      - rapidpro
    links:
      - redis
      - postgresql
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgresql/rapidpro
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=super-secret-key
    command: ["celery", "--beat", "--app=temba", "worker", "--loglevel=INFO", "--queues=celery,msgs,flows,handler"]
  redis:
    image: redis:alpine
  postgresql:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_DB=rapidpro
  mage:
   image: rapidpro/mage
   depends_on:
     - rapidpro
   links:
     - redis
     - postgresql
   environment:
     - DATABASE_URL=postgresql://postgres:postgres@postgresql/rapidpro
     - REDIS_URL=redis://redis/
     - REDIS_DATABASE=8