# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 15:05
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_campaignevent_message_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignevent',
            name='message',
        ),
        migrations.RenameField(
            model_name='campaignevent',
            old_name='message_new',
            new_name='message',
        ),
    ]
