# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-02 23:16
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("campaigns", "0022_auto_20180315_2023")]

    operations = [
        migrations.AlterField(
            model_name="campaignevent",
            name="campaign",
            field=models.ForeignKey(
                help_text="The campaign this event is part of",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="campaigns.Campaign",
            ),
        ),
        migrations.AlterField(
            model_name="campaignevent",
            name="flow",
            field=models.ForeignKey(
                help_text="The flow that will be triggered",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="flows.Flow",
            ),
        ),
        migrations.AlterField(
            model_name="campaignevent",
            name="relative_to",
            field=models.ForeignKey(
                help_text="The field our offset is relative to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaigns",
                to="contacts.ContactField",
            ),
        ),
        migrations.AlterField(
            model_name="eventfire",
            name="contact",
            field=models.ForeignKey(
                help_text="The contact that is scheduled to have an event run",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fire_events",
                to="contacts.Contact",
            ),
        ),
        migrations.AlterField(
            model_name="eventfire",
            name="event",
            field=models.ForeignKey(
                help_text="The event that will be fired",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_fires",
                to="campaigns.CampaignEvent",
            ),
        ),
    ]
