# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-11 17:31
from __future__ import unicode_literals

from django.db import migrations

ADD_INDEX = """
CREATE INDEX CONCURRENTLY campaigns_eventfire_fired_not_null_idx on campaigns_eventfire(fired) WHERE fired IS NOT NULL;
"""


class Migration(migrations.Migration):
    atomic = False

    dependencies = [("campaigns", "0023_auto_20180602_2316")]

    operations = [migrations.RunSQL(ADD_INDEX)]
