# Generated by Django 2.0.8 on 2018-10-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("campaigns", "0027_indexes")]

    operations = [
        migrations.AddField(
            model_name="campaignevent",
            name="exec_mode",
            field=models.CharField(
                choices=[("F", "Force interruption"), ("S", "Skip"), ("P", "Send in background, No interruption")],
                default="F",
                help_text="The execution mode of this event",
                max_length=1,
            ),
        )
    ]
