# Generated by Django 2.1.9 on 2019-11-22 01:54

from django.db import migrations
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [("campaigns", "0030_initial")]

    operations = [
        migrations.AlterField(
            model_name="campaignevent",
            name="message",
            field=temba.utils.models.TranslatableField(max_length=2000, null=True),
        )
    ]
