# Generated by Django 2.2.4 on 2019-08-20 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("campaigns", "0030_initial")]

    operations = [
        migrations.AlterField(model_name="campaign", name="is_archived", field=models.BooleanField(default=False)),
        migrations.AlterField(
            model_name="campaign",
            name="org",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="orgs.Org"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="group",
            field=models.ForeignKey(
                help_text="The group this campaign operates on",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaigns",
                to="contacts.ContactGroup",
            ),
        ),
        migrations.AlterField(
            model_name="campaignevent",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="events", to="campaigns.Campaign"
            ),
        ),
        migrations.AlterField(model_name="campaignevent", name="delivery_hour", field=models.IntegerField(default=-1)),
        migrations.AlterField(
            model_name="campaignevent",
            name="event_type",
            field=models.CharField(choices=[("F", "Flow Event"), ("M", "Message Event")], default="F", max_length=1),
        ),
        migrations.AlterField(
            model_name="campaignevent",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="campaign_events", to="flows.Flow"
            ),
        ),
        migrations.AlterField(model_name="campaignevent", name="offset", field=models.IntegerField(default=0)),
        migrations.AlterField(
            model_name="campaignevent",
            name="relative_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="campaign_events", to="contacts.ContactField"
            ),
        ),
        migrations.AlterField(
            model_name="campaignevent",
            name="start_mode",
            field=models.CharField(
                choices=[("I", "Interrupt"), ("S", "Skip"), ("P", "Passive")], default="I", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="campaignevent",
            name="unit",
            field=models.CharField(
                choices=[("M", "Minutes"), ("H", "Hours"), ("D", "Days"), ("W", "Weeks")], default="D", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="eventfire",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="campaign_fires", to="contacts.Contact"
            ),
        ),
        migrations.AlterField(
            model_name="eventfire",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="fires", to="campaigns.CampaignEvent"
            ),
        ),
        migrations.AlterField(model_name="eventfire", name="fired", field=models.DateTimeField(null=True)),
        migrations.AlterField(
            model_name="eventfire",
            name="fired_result",
            field=models.CharField(choices=[("F", "Fired"), ("S", "Skipped")], max_length=1, null=True),
        ),
        migrations.AlterField(model_name="eventfire", name="scheduled", field=models.DateTimeField()),
    ]
