# Generated by Django 2.1.9 on 2019-11-23 23:28

from django.db import migrations
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [("campaigns", "0031_auto_20191122_0154")]

    operations = [
        migrations.AlterField(
            model_name="campaignevent",
            name="message",
            field=temba.utils.models.TranslatableField(max_length=640, null=True),
        )
    ]
