# Generated by Django 2.2.4 on 2019-11-12 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("campaigns", "0032_migrate_msg_events")]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="campaigns", to="orgs.Org"
            ),
        )
    ]
