# Generated by Django 2.2.4 on 2020-03-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("campaigns", "0033_auto_20191112_1623"), ("campaigns", "0031_auto_20191122_0154")]

    operations = []
