# Generated by Django 2.2.10 on 2020-12-04 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0128_squashed"),
        ("campaigns", "0036_squashed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("flows", "0243_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignevent",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="campaign_events", to="flows.Flow"
            ),
        ),
        migrations.AddField(
            model_name="campaignevent",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaigns_campaignevent_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campaignevent",
            name="relative_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="campaign_events", to="contacts.ContactField"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaigns_campaign_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="group",
            field=models.ForeignKey(
                help_text="The group this campaign operates on",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaigns",
                to="contacts.ContactGroup",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaigns_campaign_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
