# Generated by Django 2.2.4 on 2020-12-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0038_squashed'),
        ('campaigns', '0035_squashed_ccl_0035_0038'),
    ]

    operations = [
    ]
