# Generated by Django 4.0.3 on 2022-03-10 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0043_squashed"),
        ("flows", "0278_squashed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contacts", "0152_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignevent",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="campaign_events", to="flows.flow"
            ),
        ),
        migrations.AddField(
            model_name="campaignevent",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campaignevent",
            name="relative_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="campaign_events", to="contacts.contactfield"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="campaigns", to="contacts.contactgroup"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
