# Generated by Django 4.0.4 on 2022-05-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0047_alter_campaign_uuid_alter_campaignevent_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
    ]
