# Generated by Django 4.0.8 on 2023-01-11 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campaigns", "0051_squashed"),
        ("orgs", "0118_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="campaigns", to="orgs.org"
            ),
        ),
    ]
