# Generated by Django 4.2.8 on 2023-12-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0054_cleanup_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="eventfire",
            index=models.Index(condition=models.Q(("fired", None)), fields=["scheduled"], name="eventfires_unfired"),
        ),
    ]
