# Generated by Django 4.2.8 on 2024-01-05 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contacts", "0183_squashed"),
        ("campaigns", "0056_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventfire",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaign_fires",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="eventfire",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fires",
                to="campaigns.campaignevent",
            ),
        ),
        migrations.AddField(
            model_name="campaignevent",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="campaigns.campaign",
            ),
        ),
        migrations.AddField(
            model_name="campaignevent",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
