# Generated by Django 4.2.8 on 2024-01-05 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orgs", "0133_squashed"),
        ("campaigns", "0058_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaigns",
                to="orgs.org",
            ),
        ),
        migrations.AddIndex(
            model_name="eventfire",
            index=models.Index(
                condition=models.Q(("fired", None)),
                fields=["scheduled"],
                name="eventfires_unfired",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventfire",
            constraint=models.UniqueConstraint(
                condition=models.Q(("fired", None)),
                fields=("event_id", "contact_id"),
                name="eventfires_unfired_unique",
            ),
        ),
    ]
