# Generated by Django 5.0.3 on 2024-04-04 19:38

from django.db import migrations
from django.utils import timezone


def archive_campaigns_with_deleted_groups(apps, schema_editor):  # pragma: no cover
    Campaign = apps.get_model("campaigns", "Campaign")

    num_archived = 0
    for campaign in Campaign.objects.filter(is_active=True, is_archived=False, group__is_active=False):
        campaign.is_archived = True
        campaign.modified_by = campaign.created_by
        campaign.modified_on = timezone.now()
        campaign.save(update_fields=("is_archived", "modified_by", "modified_on"))
        num_archived += 1

    if num_archived:
        print(f"Archived {num_archived} campaigns with deleted groups.")


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [("campaigns", "0059_squashed")]

    operations = [migrations.RunPython(archive_campaigns_with_deleted_groups, reverse)]
