# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-16 17:02
from __future__ import unicode_literals

from django.db import migrations

SQL = """
-- index for fast fetching of unsquashed rows
CREATE INDEX channels_channelcount_unsquashed
ON channels_channelcount(channel_id, count_type, day) WHERE NOT is_squashed;

CREATE INDEX channels_channelevent_api_view
ON channels_channelevent(org_id, created_on DESC, id DESC)
WHERE is_active = TRUE;

CREATE INDEX channels_channelevent_calls_view
ON channels_channelevent(org_id, "time" DESC)
WHERE is_active = TRUE AND event_type IN ('mt_call', 'mt_miss', 'mo_call', 'mo_miss');

CREATE INDEX channels_channellog_channel_created_on
ON channels_channellog(channel_id, created_on desc);
"""


class Migration(migrations.Migration):

    dependencies = [("channels", "0003_auto_20180716_1623")]

    operations = [migrations.RunSQL(SQL)]
