# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 08:12
from __future__ import unicode_literals

from django.db import migrations, models
from temba.sql import InstallSQL


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0058_add_junebug_channel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelcount',
            name='is_squashed',
            field=models.BooleanField(default=False, help_text='Whether this row was created by squashing'),
        ),
        migrations.RunSQL(
            'CREATE INDEX channels_channelcount_unsquashed '
            'ON channels_channelcount(channel_id, count_type, day) WHERE NOT is_squashed'
        ),
        InstallSQL('0059_channels')
    ]
