# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 12:41
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0068_junebug_ussd_channel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelsession',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('Q', 'Queued'), ('R', 'Ringing'), ('I', 'In Progress'), ('D', 'Complete'), ('B', 'Busy'), ('F', 'Failed'), ('N', 'No Answer'), ('C', 'Canceled'), ('X', 'Interrupted'), ('T', 'Triggered'), ('A', 'Initiated'), ('E', 'Ending')], default='P', help_text='The status of this session', max_length=1),
        ),
    ]
