# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0071_auto_20170614_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(max_length=3, verbose_name='Channel Type'),
        ),
    ]
