# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0073_auto_20170623_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelsession',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
