# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0074_channel_tps'),
    ]

    def set_tps(apps, schema_editor):
        from temba.channels.models import Channel
        ChannelModel = apps.get_model('channels', 'Channel')

        # check each of our channel settings, set the max tps on any channel which has it
        for channel_type, settings in Channel.CHANNEL_SETTINGS.items():
            if 'max_tps' in settings:
                ChannelModel.objects.filter(channel_type=channel_type).update(tps=settings['max_tps'])

    operations = [
        migrations.RunPython(set_tps)
    ]
