# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0074_channel_schemes'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelsession',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channelsession',
            name='contact_urn',
            field=models.ForeignKey(blank=True, help_text='The URN this session is communicating with', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='contacts.ContactURN',
                                    verbose_name='Contact URN'),
        ),
        migrations.AlterField(
            model_name='channelsession',
            name='channel',
            field=models.ForeignKey(blank=True, help_text='The channel that created this session', null=True, on_delete=django.db.models.deletion.CASCADE, to='channels.Channel'),
        ),
    ]
