# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 20:36
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0075_auto_20170811_1511'),
    ]

    def set_tps(apps, schema_editor):
        from temba.channels.models import Channel
        ChannelModel = apps.get_model('channels', 'Channel')

        # check each of our channel settings, set the max tps on any channel which has it
        for channel_type, settings in Channel.CHANNEL_SETTINGS.items():
            if 'max_tps' in settings:
                ChannelModel.objects.filter(channel_type=channel_type).update(tps=settings['max_tps'])

    operations = [
        migrations.AddField(
            model_name='channel',
            name='tps',
            field=models.IntegerField(help_text='The max number of messages that will be sent per second', null=True, verbose_name='Maximum Transactions per Second'),
        ),
        migrations.RunPython(set_tps),
    ]
