# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0075_auto_20170628_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelsession',
            name='contact_urn',
            field=models.ForeignKey(blank=True, help_text='The URN this session is communicating with', null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.ContactURN', verbose_name='Contact URN'),
        ),
    ]
