# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 15:55
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0076_channel_tps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channellog',
            old_name='session',
            new_name='connection',
        ),
    ]
