# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 17:31
from __future__ import unicode_literals

from django.db import migrations


def populate_twilio_auth(apps, schema_editor):
    Channel = apps.get_model('channels', 'Channel')

    # copy our org level configs into our channel configs
    for channel in Channel.objects.filter(channel_type__in=['T', 'TMS'], is_active=True).select_related('org'):
        org_config = channel.org.config
        channel.config['account_sid'] = org_config.get('ACCOUNT_SID')
        channel.config['auth_token'] = org_config.get('ACCOUNT_TOKEN')
        channel.save(update_fields=['config'])

    # for consistency, remap TWIML keys as well
    for channel in Channel.objects.filter(channel_type='TW', is_active=True):
        channel.config['account_sid'] = channel.config.get('ACCOUNT_SID')
        channel.config['auth_token'] = channel.config.get('ACCOUNT_TOKEN')
        del channel.config['ACCOUNT_SID']
        del channel.config['ACCOUNT_TOKEN']
        channel.save(update_fields=['config'])


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0078_auto_20170831_1830'),
    ]

    operations = [
        migrations.RunPython(populate_twilio_auth)
    ]
