# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 14:45
from __future__ import unicode_literals

from django.db import migrations
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0084_auto_20180115_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='config',
            field=temba.utils.models.JSONAsTextField(default=dict, help_text='Any channel specific configuration, used for the various aggregators', null=True, verbose_name='Config'),
        ),
    ]
