# Generated by Django 1.11.6 on 2018-04-11 17:48

from django.db import migrations


def update_dart_hub9_schemes(apps, schema_editor):
    Channel = apps.get_model("channels", "Channel")
    Channel.objects.filter(channel_type__in=["DA", "H9"]).update(schemes=["tel", "ext"])


class Migration(migrations.Migration):

    dependencies = [("channels", "0085_auto_20180202_1225")]

    operations = [migrations.RunPython(update_dart_hub9_schemes)]
