# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 14:16
from __future__ import unicode_literals

from django.db import migrations
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0085_auto_20180124_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelevent',
            name='extra',
            field=temba.utils.models.JSONAsTextField(help_text='Any extra properties on this event as JSON', null=True, verbose_name='Extra'),
        ),
    ]
