# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-02 23:16
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("channels", "0089_auto_20180502_1643")]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="org",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization using this channel",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="channels",
                to="orgs.Org",
                verbose_name="Org",
            ),
        )
    ]
