# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-01 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("channels", "0089_auto_20180502_1643")]

    operations = [
        migrations.AddField(
            model_name="channelsession",
            name="next_attempt",
            field=models.DateTimeField(
                help_text="When we should next attempt to make this call", null=True, verbose_name="Next Attempt"
            ),
        ),
        migrations.AddField(
            model_name="channelsession",
            name="retry_count",
            field=models.IntegerField(
                default=0, help_text="The number of times this call has been retried", verbose_name="Retry Count"
            ),
        ),
    ]
