# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-05 15:48
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("channels", "0090_auto_20180602_2316")]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="channel",
            field=models.ForeignKey(
                help_text="The channel that this alert is for",
                on_delete=django.db.models.deletion.PROTECT,
                to="channels.Channel",
                verbose_name="Channel",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="sync_event",
            field=models.ForeignKey(
                help_text="The sync event that caused this alert to be sent (if any)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="channels.SyncEvent",
                verbose_name="Sync Event",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The channel this channel is working on behalf of",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="channels.Channel",
            ),
        ),
        migrations.AlterField(
            model_name="channelcount",
            name="channel",
            field=models.ForeignKey(
                help_text="The channel this is a daily summary count for",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="counts",
                to="channels.Channel",
            ),
        ),
        migrations.AlterField(
            model_name="channelevent",
            name="contact",
            field=models.ForeignKey(
                help_text="The contact associated with this event",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="channel_events",
                to="contacts.Contact",
                verbose_name="Contact",
            ),
        ),
        migrations.AlterField(
            model_name="channelevent",
            name="contact_urn",
            field=models.ForeignKey(
                help_text="The contact URN associated with this event",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="channel_events",
                to="contacts.ContactURN",
                verbose_name="URN",
            ),
        ),
        migrations.AlterField(
            model_name="channelevent",
            name="org",
            field=models.ForeignKey(
                help_text="The org this event is connected to",
                on_delete=django.db.models.deletion.PROTECT,
                to="orgs.Org",
                verbose_name="Org",
            ),
        ),
        migrations.AlterField(
            model_name="channellog",
            name="channel",
            field=models.ForeignKey(
                help_text="The channel the message was sent on",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="logs",
                to="channels.Channel",
            ),
        ),
        migrations.AlterField(
            model_name="channellog",
            name="connection",
            field=models.ForeignKey(
                help_text="The channel session for this log",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="channel_logs",
                to="channels.ChannelSession",
            ),
        ),
        migrations.AlterField(
            model_name="channellog",
            name="msg",
            field=models.ForeignKey(
                help_text="The message that was sent",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="channel_logs",
                to="msgs.Msg",
            ),
        ),
        migrations.AlterField(
            model_name="channelsession",
            name="channel",
            field=models.ForeignKey(
                help_text="The channel that created this session",
                on_delete=django.db.models.deletion.PROTECT,
                to="channels.Channel",
            ),
        ),
        migrations.AlterField(
            model_name="channelsession",
            name="contact",
            field=models.ForeignKey(
                help_text="Who this session is with",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="contacts.Contact",
            ),
        ),
        migrations.AlterField(
            model_name="channelsession",
            name="contact_urn",
            field=models.ForeignKey(
                help_text="The URN this session is communicating with",
                on_delete=django.db.models.deletion.PROTECT,
                to="contacts.ContactURN",
                verbose_name="Contact URN",
            ),
        ),
        migrations.AlterField(
            model_name="channelsession",
            name="org",
            field=models.ForeignKey(
                help_text="The organization this session belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="orgs.Org",
            ),
        ),
        migrations.AlterField(
            model_name="syncevent",
            name="channel",
            field=models.ForeignKey(
                help_text="The channel that synced to the server",
                on_delete=django.db.models.deletion.PROTECT,
                to="channels.Channel",
                verbose_name="Channel",
            ),
        ),
    ]
