# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-16 16:23
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0084_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("channels", "0094_initial"),
        ("orgs", "0045_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelsession",
            name="contact",
            field=models.ForeignKey(
                help_text="Who this session is with",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="contacts.Contact",
            ),
        ),
        migrations.AddField(
            model_name="channelsession",
            name="contact_urn",
            field=models.ForeignKey(
                help_text="The URN this session is communicating with",
                on_delete=django.db.models.deletion.PROTECT,
                to="contacts.ContactURN",
                verbose_name="Contact URN",
            ),
        ),
        migrations.AddField(
            model_name="channelsession",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="channels_channelsession_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="channelsession",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="channels_channelsession_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="channelsession",
            name="org",
            field=models.ForeignKey(
                help_text="The organization this session belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="orgs.Org",
            ),
        ),
        migrations.AddField(
            model_name="channellog",
            name="channel",
            field=models.ForeignKey(
                help_text="The channel the message was sent on",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="logs",
                to="channels.Channel",
            ),
        ),
        migrations.AddField(
            model_name="channellog",
            name="connection",
            field=models.ForeignKey(
                help_text="The channel session for this log",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="channel_logs",
                to="channels.ChannelSession",
            ),
        ),
    ]
