# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-16 17:02
from __future__ import unicode_literals

from django.db import migrations

SQL = """
-- index for fast fetching of unsquashed rows
CREATE INDEX channels_channelcount_unsquashed
ON channels_channelcount(channel_id, count_type, day) WHERE NOT is_squashed;

CREATE INDEX channels_channellog_channel_created_on
ON channels_channellog(channel_id, created_on desc);
"""


class Migration(migrations.Migration):

    dependencies = [("channels", "0096_auto_20180716_1623")]

    operations = [migrations.RunSQL(SQL)]
