# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-16 16:23
from __future__ import unicode_literals

import django_countries.fields

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import temba.utils.models


SQL = """
-- index for fast fetching of unsquashed rows
CREATE INDEX channels_channelcount_unsquashed
ON channels_channelcount(channel_id, count_type, day) WHERE NOT is_squashed;

CREATE INDEX channels_channellog_channel_created_on
ON channels_channellog(channel_id, created_on desc);
"""


class Migration(migrations.Migration):

    dependencies = [("channels", "0096_auto_20180716_1623")]

    operations = [

    migrations.AddField(
        model_name='ChannelSession',
        name='retry_count',
        field=models.IntegerField(
            default=0,
            help_text="The number of times this call has been retried",
            verbose_name="Retry Count",
        ),
    ),
    migrations.AddField(
        model_name='ChannelSession',
        name='next_attempt',
        field=models.DateTimeField(
            help_text="When we should next attempt to make this call",
            null=True,
            verbose_name="Next Attempt",
        ),
    ),
    ]
