# Generated by Django 2.0.8 on 2018-10-18 14:03

from django.db import migrations

SQL = """
CREATE INDEX IF NOT EXISTS channels_channelsession_pending_events
  ON channels_channelsession (created_on ASC NULLS LAST) WHERE status = 'P' and direction = 'O' and is_active = True;
"""


class Migration(migrations.Migration):

    dependencies = [("channels", "0102_channelsession_error_count")]

    operations = [migrations.RunSQL(SQL)]
