# Generated by Django 2.0.9 on 2018-10-24 09:59

from django.db import migrations

DROP_INDEX = """DROP INDEX channels_channelsession_pending_events;"""

CREATE_INDEX = """
CREATE INDEX IF NOT EXISTS channels_channelsession_pending_events
  ON channels_channelsession (modified_on ASC NULLS LAST) WHERE status = 'P' and direction = 'O' and is_active = True;
"""


class Migration(migrations.Migration):

    dependencies = [("channels", "0103_auto_20181018_1403")]

    operations = [migrations.RunSQL(DROP_INDEX), migrations.RunSQL(CREATE_INDEX)]
