# Generated by Django 2.1.3 on 2018-12-05 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("channels", "0106_auto_20181128_1347")]

    operations = [migrations.RemoveField(model_name="channel", name="gcm_id")]
