# Generated by Django 2.1.3 on 2018-12-12 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("channels", "0108_channel_android_last_seen_index")]

    operations = [
        migrations.AlterField(
            model_name="channelsession",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="channels_channelsession_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="channelsession",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="channels_channelsession_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
