# Generated by Django 2.1.3 on 2019-01-10 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("channels", "0109_auto_20181212_1620")]

    operations = [
        migrations.RemoveField(model_name="channelsession", name="modified_by"),
        migrations.AlterField(
            model_name="channelsession",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this connection",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
