# Generated by Django 2.1.3 on 2019-01-11 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("channels", "0111_rename_channelsession")]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="channel",
            field=models.ForeignKey(
                help_text="The channel we're connected to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connections",
                to="channels.Channel",
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="contact",
            field=models.ForeignKey(
                help_text="Who this connection is with",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connections",
                to="contacts.Contact",
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="contact_urn",
            field=models.ForeignKey(
                help_text="The URN we're communicating with",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connections",
                to="contacts.ContactURN",
                verbose_name="Contact URN",
            ),
        ),
    ]
