# Generated by Django 2.1.5 on 2019-01-16 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("channels", "0112_auto_20190111_1718")]

    operations = [
        migrations.RenameField(model_name="channelconnection", old_name="session_type", new_name="connection_type")
    ]
