# Generated by Django 2.1.5 on 2019-01-23 16:20

from django.db import migrations


def deactivate_ussd_channels(apps, schema_editor):
    Channel = apps.get_model("channels", "Channel")

    num_deactivated = 0
    for channel in Channel.objects.filter(channel_type="JNU"):
        channel.triggers.all().delete()

        channel.is_active = False
        channel.save(update_fields=("is_active",))
        num_deactivated += 1

    if num_deactivated:
        print(f"Deactivated {num_deactivated} USSD channels")


class Migration(migrations.Migration):

    dependencies = [("channels", "0113_rename_session_type")]

    operations = [migrations.RunPython(deactivate_ussd_channels)]
