# Generated by Django 2.1.5 on 2019-01-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("channels", "0114_deactivate_ussd")]

    operations = [
        migrations.AlterField(
            model_name="channelconnection",
            name="connection_type",
            field=models.CharField(choices=[("V", "Voice")], max_length=1),
        )
    ]
