# Generated by Django 2.1.5 on 2019-01-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("channels", "0115_auto_20190130_1543")]

    operations = [
        migrations.AlterField(
            model_name="channelconnection",
            name="is_active",
            field=models.BooleanField(
                help_text="Whether this item is active, use this instead of deleting", null=True
            ),
        )
    ]
