# Generated by Django 2.1.5 on 2019-02-27 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("channels", "0116_auto_20190131_2013")]

    operations = [
        migrations.RemoveField(model_name="channelconnection", name="created_by"),
        migrations.RemoveField(model_name="channelconnection", name="is_active"),
    ]
