# Generated by Django 2.1.8 on 2019-07-01 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("msgs", "0132_initial"), ("channels", "0119_initial")]

    operations = [
        migrations.AddField(
            model_name="channellog",
            name="msg",
            field=models.ForeignKey(
                help_text="The message that was sent",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="channel_logs",
                to="msgs.Msg",
            ),
        )
    ]
