# Generated by Django 2.2.4 on 2020-07-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0122_populate_allow_international"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="channelconnection",
            index=models.Index(fields=["channel", "status"], name="channels_conn_ch_id_status_idx"),
        ),
        migrations.AddIndex(
            model_name="channelconnection",
            index=models.Index(
                fields=["channel", "connection_type", "external_id"], name="channels_conn_external_id_idx"
            ),
        ),
    ]
