# Generated by Django 2.2.24 on 2021-10-13 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0126_auto_20210916_1247'),
        ('channels', '0126_auto_20210105_1444'),
    ]

    operations = [
    ]
