# Generated by Django 3.2.6 on 2021-08-10 22:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0128_populate_wa_api_version"),
        ("sql", "0003_bigint_m2ms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelconnection",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="channelconnection",
            name="duration",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="channelconnection",
            name="ended_on",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="channelconnection",
            name="error_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="channelconnection",
            name="external_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="channelconnection",
            name="modified_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="channelconnection",
            name="next_attempt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="channelconnection",
            name="retry_count",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="channelconnection",
            name="started_on",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="channelconnection",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("W", "Wired"),
                    ("Q", "Queued"),
                    ("I", "In Progress"),
                    ("B", "Busy"),
                    ("N", "No Answer"),
                    ("C", "Canceled"),
                    ("D", "Complete"),
                    ("F", "Failed"),
                    ("E", "Errored"),
                ],
                max_length=1,
            ),
        ),
        migrations.AddIndex(
            model_name="channelconnection",
            index=models.Index(
                condition=models.Q(
                    ("connection_type", "V"), ("next_attempt__isnull", False), ("status__in", ("Q", "N", "B", "E"))
                ),
                fields=["next_attempt"],
                name="channelconnection_ivr_to_retry",
            ),
        ),
        migrations.RunSQL("DROP INDEX channels_channelsession_pending_events;"),
    ]
