# Generated by Django 3.2.6 on 2021-08-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0128_populate_wa_api_version"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="channellog",
            index=models.Index(fields=["channel", "is_error", "-created_on"], name="channels_log_error_created"),
        ),
    ]
