# Generated by Django 3.2.6 on 2021-08-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0130_channellog_channels_log_error_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelconnection",
            name="error_reason",
            field=models.CharField(
                choices=[
                    ("P", "Provider"),
                    ("B", "Busy"),
                    ("N", "No Answer"),
                    ("M", "Answering Machine"),
                    ("T", "Throttled"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="channelconnection",
            name="retry_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="channelconnection",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("W", "Wired"),
                    ("I", "In Progress"),
                    ("D", "Complete"),
                    ("E", "Errored"),
                    ("F", "Failed"),
                ],
                max_length=1,
            ),
        ),
    ]
