# Generated by Django 2.2.27 on 2022-03-22 14:47

from django.db import migrations, models

remove_trigger = """
DROP TRIGGER IF EXISTS temba_channellog_update_segments_channelcount ON channels_channellog;
DROP FUNCTION IF EXISTS temba_update_channel_segments_count;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0132_auto_20220316_1338"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelcount",
            name="count_type",
            field=models.CharField(
                choices=[
                    ("IM", "Incoming Message"),
                    ("OM", "Outgoing Message"),
                    ("IV", "Incoming Voice"),
                    ("OV", "Outgoing Voice"),
                    ("LS", "Success Log Record"),
                    ("LE", "Error Log Record"),
                ],
                max_length=2,
            ),
        ),
        migrations.RunSQL(remove_trigger),
    ]
