# Generated by Django 3.2.6 on 2021-08-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0132_auto_20210813_2153"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelconnection",
            name="error_reason",
            field=models.CharField(
                choices=[("P", "Provider"), ("B", "Busy"), ("N", "No Answer"), ("M", "Answering Machine")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="channelconnection",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("Q", "Queued"),
                    ("W", "Wired"),
                    ("I", "In Progress"),
                    ("D", "Complete"),
                    ("E", "Errored"),
                    ("F", "Failed"),
                ],
                max_length=1,
            ),
        ),
    ]
