# Generated by Django 3.2.7 on 2021-09-24 19:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0134_alter_channel_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channellog",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
