# Generated by Django 4.0.7 on 2022-09-08 16:33

from django.db import migrations


def drop_legacy_logs(apps, schema_editor):  # pragma: no cover
    ChannelLog = apps.get_model("channels", "ChannelLog")

    num_deleted = 0
    while True:
        batch_ids = ChannelLog.objects.filter(log_type=None).values_list("id", flat=True)[:1000]
        if not batch_ids:
            break

        ChannelLog.objects.filter(id__in=batch_ids).delete()
        num_deleted += len(batch_ids)
        print(f" > Deleted {num_deleted} legacy channel logs")


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0144_channelconnection_log_uuids"),
    ]

    operations = [migrations.RunPython(drop_legacy_logs, reverse)]
