# Generated by Django 4.0.7 on 2022-09-16 16:07

from django.db import migrations


def remove_non_ivr_connections(apps, schema_editor):  # pragma: no cover
    ChannelConnection = apps.get_model("channels", "ChannelConnection")

    num_deleted = 0
    while True:
        batch_ids = list(
            ChannelConnection.objects.exclude(connection_type__in=("V", "F")).values_list("id", flat=True)[:1000]
        )
        if not batch_ids:
            break

        ChannelConnection.objects.filter(id__in=batch_ids).delete()
        num_deleted += len(batch_ids)

        print(f"Deleted {num_deleted} non-IVR channel connections")


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [("channels", "0146_alter_channellog_elapsed_ms_and_more")]

    operations = [migrations.RunPython(remove_non_ivr_connections, reverse)]
