# Generated by Django 4.0.7 on 2022-09-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0147_remove_non_ivr_connections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelconnection",
            name="connection_type",
            field=models.CharField(default="V", max_length=1, null=True),
        ),
    ]
