# Generated by Django 4.0.7 on 2022-09-19 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0148_alter_channelconnection_connection_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channellog",
            name="description",
        ),
        migrations.RemoveField(
            model_name="channellog",
            name="method",
        ),
        migrations.RemoveField(
            model_name="channellog",
            name="request",
        ),
        migrations.RemoveField(
            model_name="channellog",
            name="request_time",
        ),
        migrations.RemoveField(
            model_name="channellog",
            name="response",
        ),
        migrations.RemoveField(
            model_name="channellog",
            name="response_status",
        ),
        migrations.RemoveField(
            model_name="channellog",
            name="url",
        ),
    ]
