# Generated by Django 4.0.7 on 2022-09-28 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0297_remove_flowsession_connection_and_more"),
        ("channels", "0152_remove_channelconnection_channelconnection_to_retry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channellog",
            name="connection",
        ),
        migrations.DeleteModel(
            name="ChannelConnection",
        ),
    ]
