# Generated by Django 4.0.8 on 2023-01-11 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("channels", "0155_squashed"),
        ("ivr", "0022_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="channellog",
            name="call",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="channel_logs", to="ivr.call"
            ),
        ),
        migrations.AddField(
            model_name="channellog",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="logs", to="channels.channel"
            ),
        ),
    ]
