# Generated by Django 4.1.7 on 2023-03-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0159_alter_channel_claim_code_alter_channel_device_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(
                choices=[("P", "Power"), ("D", "Disconnected")],
                help_text="The type of alert the channel is sending",
                max_length=1,
                verbose_name="Alert Type",
            ),
        ),
    ]
