# Generated by Django 4.1.7 on 2023-03-13 18:52

from django.db import migrations


def backfill_empty_configs(apps, schema_editor):  # pragma: no cover
    Channel = apps.get_model("channels", "Channel")
    Channel.objects.filter(config=None).update(config={})


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):
    dependencies = [("channels", "0160_alter_alert_alert_type")]

    operations = [migrations.RunPython(backfill_empty_configs, reverse)]
