# Generated by Django 4.1.9 on 2023-05-30 21:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0163_alter_channel_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channellog",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, db_index=True),
        ),
    ]
