# Generated by Django 4.1.9 on 2023-06-02 21:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0164_alter_channellog_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channellog",
            name="call",
        ),
        migrations.RemoveField(
            model_name="channellog",
            name="msg",
        ),
    ]
