# Generated by Django 4.1.9 on 2023-06-27 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0166_remove_channellog_channels_log_error_created_and_more"),
        ("sql", "0005_squashed"),
    ]

    operations = [migrations.RunSQL("DROP INDEX channels_channellog_channel_created_on")]
