# Generated by Django 4.2.3 on 2023-07-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0170_remove_channel_bod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channellog",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("unknown", "Other Event"),
                    ("msg_send", "Message Send"),
                    ("msg_status", "Message Status"),
                    ("msg_receive", "Message Receive"),
                    ("event_receive", "Event Receive"),
                    ("multi_receive", "Events Receive"),
                    ("ivr_start", "IVR Start"),
                    ("ivr_incoming", "IVR Incoming"),
                    ("ivr_callback", "IVR Callback"),
                    ("ivr_status", "IVR Status"),
                    ("ivr_hangup", "IVR Hangup"),
                    ("attachment_fetch", "Attachment Fetch"),
                    ("token_refresh", "Token Refresh"),
                    ("page_subscribe", "Page Subscribe"),
                    ("webhook_verify", "Webhook Verify"),
                ],
                max_length=16,
            ),
        ),
    ]
