# Generated by Django 4.2.3 on 2023-09-11 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0171_alter_channellog_log_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channel",
            name="parent",
        ),
    ]
