# Generated by Django 4.2.3 on 2023-09-27 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0173_alter_alert_alert_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="alert",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="alerts", to="channels.channel"
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="ended_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="alert",
            name="sync_event",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="alerts", to="channels.syncevent"
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="alert_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
