# Generated by Django 4.2.3 on 2023-09-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0174_alter_alert_alert_type_alter_alert_channel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown Call Type"),
                    ("mt_call", "Outgoing Call"),
                    ("mt_miss", "Missed Outgoing Call"),
                    ("mo_call", "Incoming Call"),
                    ("mo_miss", "Missed Incoming Call"),
                    ("stop_contact", "Stop Contact"),
                    ("new_conversation", "New Conversation"),
                    ("referral", "Referral"),
                    ("welcome_message", "Welcome Message"),
                    ("optin", "Opt In"),
                    ("optout", "Opt Out"),
                ],
                max_length=16,
            ),
        ),
    ]
