# Generated by Django 4.2.3 on 2023-09-27 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0174_alter_alert_alert_type_alter_alert_channel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channel",
            name="alert_email",
        ),
        migrations.DeleteModel(
            name="Alert",
        ),
    ]
