# Generated by Django 4.2.3 on 2023-12-06 19:17

from django.db import migrations, models

SQL = """
DROP INDEX channels_channelcount_unsquashed;
DROP INDEX channels_channel_android_last_seen_active;
"""


class Migration(migrations.Migration):
    dependencies = [("channels", "0177_channelevent_optin")]

    operations = [
        migrations.RunSQL(SQL),
        migrations.AlterIndexTogether(
            name="channelcount",
            index_together=set(),
        ),
        migrations.AddIndex(
            model_name="channelcount",
            index=models.Index(
                fields=["channel", "count_type", "day", "is_squashed"], name="channels_ch_channel_cf3039_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="channel",
            index=models.Index(
                condition=models.Q(("channel_type", "A"), ("is_active", True), ("last_seen__isnull", False)),
                fields=["last_seen"],
                name="channels_android_last_seen",
            ),
        ),
    ]
