# Generated by Django 4.2.8 on 2024-01-05 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orgs", "0133_squashed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("channels", "0181_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelevent",
            name="org",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="orgs.org"),
        ),
        migrations.AddField(
            model_name="channelcount",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="counts",
                to="channels.channel",
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="channels",
                to="orgs.org",
            ),
        ),
        migrations.AddIndex(
            model_name="channellog",
            index=models.Index(fields=["channel", "-created_on"], name="channellogs_by_channel"),
        ),
        migrations.AddIndex(
            model_name="channelcount",
            index=models.Index(
                fields=["channel", "count_type", "day", "is_squashed"],
                name="channels_ch_channel_cf3039_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="channel",
            index=models.Index(
                condition=models.Q(
                    ("channel_type", "A"),
                    ("is_active", True),
                    ("last_seen__isnull", False),
                ),
                fields=["last_seen"],
                name="channels_android_last_seen",
            ),
        ),
    ]
