# Generated by Django 5.0.3 on 2024-04-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0182_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelevent",
            name="status",
            field=models.CharField(choices=[("P", "Pending"), ("H", "Handled")], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="channelevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("mt_call", "Outgoing Call"),
                    ("mt_miss", "Missed Outgoing Call"),
                    ("mo_call", "Incoming Call"),
                    ("mo_miss", "Missed Incoming Call"),
                    ("stop_contact", "Stop Contact"),
                    ("new_conversation", "New Conversation"),
                    ("referral", "Referral"),
                    ("welcome_message", "Welcome Message"),
                    ("optin", "Opt In"),
                    ("optout", "Opt Out"),
                ],
                max_length=16,
            ),
        ),
    ]
