# Generated by Django 5.0.3 on 2024-04-03 16:13

from django.db import migrations
from django.db.models import Q

DEFAULT_NAMES = {
    "JC": lambda c: "JioChat",
    "TQ": lambda c: c.address or "Thinq",
    "EX": lambda c: c.address or "External",
    "WC": lambda c: "WeChat",
    "NX": lambda c: c.address or "Vonage",
    "A": lambda c: c.device or c.address or "Android",
}


def backfill_empty_names(apps, schema_editor):  # pragma: no cover
    Channel = apps.get_model("channels", "Channel")

    num_updated = 0
    for channel in Channel.objects.filter(Q(name="") | Q(name=None)):
        name_func = DEFAULT_NAMES.get(channel.channel_type)
        channel.name = name_func(channel) if name_func else (channel.address or channel.channel_type)
        channel.save(update_fields=("name",))
        num_updated += 1

    if num_updated:
        print(f"Updated {num_updated} channels with empty names")


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [("channels", "0183_channelevent_status_alter_channelevent_event_type")]

    operations = [migrations.RunPython(backfill_empty_names, reverse)]
