# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-16 16:41
from __future__ import unicode_literals

from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [HStoreExtension()]
