# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-16 16:41
from __future__ import unicode_literals

from django.db import migrations

from temba.sql import InstallSQL


class Migration(migrations.Migration):

    dependencies = [
        ("airtime", "0001_initial"),
        ("api", "0001_initial"),
        ("archives", "0001_initial"),
        ("campaigns", "0001_initial"),
        ("channels", "0003_auto_20180716_1623"),
        ("contacts", "0001_initial"),
        ("flows", "0001_initial"),
        ("ivr", "0001_initial"),
        ("locations", "0002_auto_20180716_1622"),
        ("msgs", "0001_initial"),
        ("orgs", "0001_initial"),
        ("policies", "0001_initial"),
        ("public", "0001_initial"),
        ("schedules", "0001_initial"),
        ("triggers", "0001_initial"),
        ("ussd", "0001_initial"),
    ]

    operations = [
        InstallSQL("current_indexes.sql"),
        InstallSQL("current_functions.sql"),
        InstallSQL("current_triggers.sql"),
    ]
