# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 09:15
from __future__ import unicode_literals

from django.db import migrations, models
from temba.sql import InstallSQL


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0077_install_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlabel',
            name='is_squashed',
            field=models.BooleanField(default=False, help_text='Whether this row was created by squashing'),
        ),
        migrations.RunSQL(
            'CREATE INDEX msgs_systemlabel_unsquashed '
            'ON msgs_systemlabel(org_id, label_type) WHERE NOT is_squashed'
        ),
        InstallSQL('0078_msgs')
    ]
