# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 06:57
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Case, Value, When


def populate_export_status(apps, schema_editor):
    ExportMessagesTask = apps.get_model('msgs', 'ExportMessagesTask')
    ExportMessagesTask.objects.update(status=Case(When(is_finished=True, then=Value('C')), default=Value('O')))


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0081_baseexporttask_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportmessagestask',
            name='is_finished',
        ),
    ]
