# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 14:57
from __future__ import unicode_literals

from django.db import migrations


def apply_as_migration(apps, schema_editor):
    Broadcast = apps.get_model('msgs', 'Broadcast')
    Broadcast.objects.all().update(send_all=False)


def apply_manual():
    from temba.msgs.models import Broadcast
    Broadcast.objects.all().update(send_all=False)


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0086_broadcast_send_all'),
    ]

    operations = [
        migrations.RunPython(apply_as_migration)
    ]
