# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 20:17
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0089_populate_broadcast_send_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='send_all',
            field=models.BooleanField(default=False, help_text='Whether this broadcast should send to all URNs for each contact'),
        ),
    ]
