# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0093_populate_translatables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='base_language',
            field=models.CharField(help_text='The language used to send this to contacts without a language',
                                   max_length=4),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='translations',
            field=temba.utils.models.TranslatableField(help_text='The localized versions of the message text',
                                                       max_length=640, verbose_name='Translations'),
        ),
        migrations.RemoveField(
            model_name='broadcast',
            name='language_dict',
        ),
        migrations.RemoveField(
            model_name='broadcast',
            name='media_dict',
        ),
        migrations.RemoveField(
            model_name='broadcast',
            name='text',
        ),
        migrations.RenameField(
            model_name='broadcast',
            old_name='translations',
            new_name='text',
        ),
    ]
