# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 17:04
from __future__ import absolute_import, division, print_function, unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0094_auto_20170501_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='attachments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=255), help_text='The media attachments on this message if any', null=True, size=None),
        ),
    ]
