# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 17:10
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0098_auto_20170606_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='text',
            field=temba.utils.models.TranslatableField(help_text='The localized versions of the message text', max_length=640, verbose_name='Translations'),
        ),
    ]
