# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0100_auto_20170614_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='additionalParams',
            field=models.TextField(help_text='The additional params for any type msgs', null=True),
        ),
    ]
