# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0101_msg_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='metadata',
            field=models.TextField(help_text='The metadata for any type msgs', null=True),
        ),
    ]
