# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0101_msg_additionalparams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msg',
            old_name='additionalParams',
            new_name='additional_params',
        ),
    ]
