# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 21:29
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0101_msg_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='The UUID for this message', null=True),
        ),
    ]
