# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 17:45
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    CREATE_SQL = """
    CREATE INDEX CONCURRENTLY msgs_msg_channel_external_id_not_null
    ON msgs_msg (channel_id, external_id)
    WHERE external_id IS NOT NULL;
    """

    DROP_SQL = """
    DROP INDEX CONCURRENTLY msgs_msg_external_id_where_nonnull;
    """

    dependencies = [
        ('msgs', '0103_auto_20170824_1553'),
    ]

    operations = [
        migrations.RunSQL(CREATE_SQL),
        migrations.RunSQL(DROP_SQL),
    ]
