# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0105_msg_high_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msg',
            name='priority',
        ),
    ]
