# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-18 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0107_auto_20171017_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='metadata',
            field=models.TextField(help_text='The metadata for any type msgs', null=True),
        ),
        migrations.AddField(
            model_name='msg',
            name='metadata',
            field=models.TextField(help_text='The metadata for any type msgs', null=True),
        ),
    ]
