# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 15:16
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0111_auto_20171116_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msg',
            options={},
        ),
    ]
