# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0113_auto_20171128_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='action_uuid',
            field=models.UUIDField(blank=True, help_text='Optional action that created this broadcast', null=True),
        ),
    ]
