# Generated by Django 1.11.6 on 2018-02-02 12:31

from django.db import migrations
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [("msgs", "0114_auto_20180126_1452")]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="metadata",
            field=temba.utils.models.JSONAsTextField(
                help_text="The metadata for messages of this broadcast", null=True, default=dict
            ),
        ),
        migrations.AlterField(
            model_name="msg",
            name="metadata",
            field=temba.utils.models.JSONAsTextField(help_text="The metadata for this msg", null=True, default=dict),
        ),
    ]
