# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-15 20:36
from __future__ import unicode_literals

from django.db import migrations


SQL = """
CREATE INDEX CONCURRENTLY msgs_msg_uuid_not_null ON msgs_msg (response_to_id) WHERE uuid IS NOT NULL;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0116_auto_20180502_1620'),
    ]

    operations = [
        migrations.RunSQL(SQL)
    ]
