# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-02 23:16
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("msgs", "0120_msg_delete_reason")]

    operations = [
        migrations.AlterField(
            model_name="msg",
            name="contact",
            field=models.ForeignKey(
                db_index=False,
                help_text="The contact this message is communicating with",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="msgs",
                to="contacts.Contact",
                verbose_name="Contact",
            ),
        ),
        migrations.AlterField(
            model_name="msg",
            name="contact_urn",
            field=models.ForeignKey(
                help_text="The URN this message is communicating with",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="msgs",
                to="contacts.ContactURN",
                verbose_name="Contact URN",
            ),
        ),
    ]
