# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-19 20:03
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("msgs", "0122_auto_20180618_2044")]

    operations = [
        migrations.CreateModel(
            name="BroadcastMsgCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_squashed",
                    models.BooleanField(default=False, help_text="Whether this row was created by squashing"),
                ),
                ("count", models.IntegerField(default=0)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="counts", to="msgs.Broadcast"
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
