# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-16 16:23
from __future__ import unicode_literals

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import temba.utils.models

SQL = """

CREATE INDEX IF NOT EXISTS msgs_msg_org_id_created_on_id_idx on msgs_msg(org_id, created_on, id);

CREATE INDEX msgs_msg_uuid_not_null ON msgs_msg (uuid) WHERE uuid IS NOT NULL;

"""


class Migration(migrations.Migration):

    dependencies = [("msgs", "0126_initial")]

    operations = [
        migrations.CreateModel(
            name="BroadcastMsgCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_squashed",
                    models.BooleanField(default=False, help_text="Whether this row was created by squashing"),
                ),
                ("count", models.IntegerField(default=0)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="counts", to="msgs.Broadcast"
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name='SystemLabelCount',
            name='is_archived',
            field=models.BooleanField(default=False, help_text="Whether this count is for archived messages"),
        ),
        migrations.AddField(
            model_name='LabelCount',
            name='is_archived',
            field=models.BooleanField(default=False, help_text="Whether this count is for archived messages"),

        ),
        migrations.AddField(
            model_name='Msg',
            name='delete_reason',
            field=models.CharField(
                choices=[(("A", "Archive delete"), ("U", "User delete"))],
                help_text="Why the message is being deleted",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterIndexTogether(name="systemlabelcount", index_together=set([("org", "label_type")])),
        migrations.AlterUniqueTogether(name="label", unique_together=set([("org", "name")])),
        migrations.RunSQL(SQL)]
