# Generated by Django 2.1.8 on 2019-04-22 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("msgs", "0130_auto_20181128_1226")]

    operations = [
        migrations.RemoveField(model_name="broadcastrecipient", name="broadcast"),
        migrations.RemoveField(model_name="broadcastrecipient", name="contact"),
        migrations.RemoveField(model_name="broadcast", name="recipients"),
        migrations.DeleteModel(name="BroadcastRecipient"),
    ]
