# Generated by Django 2.1.8 on 2019-07-02 20:12
#
# This is a dummy migration which will be implemented in 5.1
#

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("msgs", "0131_auto_20190422_2045")]

    operations = []
