# Generated by Django 2.1.9 on 2019-11-23 23:28

from django.db import migrations
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [("msgs", "0133_auto_20191122_0154")]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="text",
            field=temba.utils.models.TranslatableField(
                help_text="The localized versions of the message text", max_length=640, verbose_name="Translations"
            ),
        )
    ]
