# Generated by Django 2.2.3 on 2019-07-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("msgs", "0133_auto_20190717_1516")]

    operations = [migrations.RemoveField(model_name="broadcast", name="purged")]
