# Generated by Django 2.2.4 on 2019-09-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("msgs", "0134_remove_broadcast_purged")]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="label_type",
            field=models.CharField(
                choices=[("F", "Folder of labels"), ("L", "Regular label")], default="L", max_length=1
            ),
        ),
        migrations.AlterUniqueTogether(name="label", unique_together=set()),
    ]
