# Generated by Django 2.2.4 on 2019-09-26 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("msgs", "0136_auto_20190925_1727")]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="msgs_labels", to="orgs.Org"
            ),
        )
    ]
