# Generated by Django 2.2.4 on 2020-03-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0138_remove_broadcast_recipient_count'),
        ('msgs', '0133_auto_20191122_0154'),
    ]

    operations = [
    ]
