# Generated by Django 2.2.4 on 2020-09-08 17:22

from datetime import timedelta

from django.db import migrations
from django.utils import timezone


def fail_msg_without_topup(apps, schema_editor):  # pragma: no cover
    Msg = apps.get_model("msgs", "Msg")

    now = timezone.now()
    day_ago = now - timedelta(hours=24)

    msgs = Msg.objects.filter(direction="O", status__in=["Q", "E"], topup=None, created_on__lte=day_ago)

    num_updated = 0
    max_id = -1
    while True:
        batch = list(msgs.filter(id__gt=max_id).order_by("id")[:5000].values_list("id", flat=True))
        if not batch:
            break

        Msg.objects.filter(id__in=batch).update(status="F")

        num_updated += len(batch)
        print(f" > Updated {num_updated} msgs")

        max_id = batch[-1]


def reverse(apps, schema_editor):  # pragma: no cover
    pass


def apply_manual():  # pragma: no cover
    from django.apps import apps

    fail_msg_without_topup(apps, None)


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0139_auto_20200727_1723"),
    ]

    operations = [migrations.RunPython(fail_msg_without_topup, reverse)]
