# Generated by Django 2.2.10 on 2020-09-29 17:14

import django.db.models.deletion
from django.db import migrations, models

import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0140_fail_msgs_missing_topups"),
    ]

    operations = [
        migrations.AlterField(model_name="broadcast", name="base_language", field=models.CharField(max_length=4),),
        migrations.AlterField(
            model_name="broadcast",
            name="channel",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="channels.Channel"),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="contacts",
            field=models.ManyToManyField(related_name="addressed_broadcasts", to="contacts.Contact"),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="groups",
            field=models.ManyToManyField(related_name="addressed_broadcasts", to="contacts.ContactGroup"),
        ),
        migrations.AlterField(model_name="broadcast", name="is_active", field=models.BooleanField(default=True),),
        migrations.AlterField(
            model_name="broadcast",
            name="media",
            field=temba.utils.models.TranslatableField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="broadcast", name="metadata", field=temba.utils.models.JSONAsTextField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="org",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="orgs.Org"),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="parent",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="children", to="msgs.Broadcast"
            ),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="schedule",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="broadcast",
                to="schedules.Schedule",
            ),
        ),
        migrations.AlterField(model_name="broadcast", name="send_all", field=models.BooleanField(default=False),),
        migrations.AlterField(
            model_name="broadcast",
            name="status",
            field=models.CharField(
                choices=[
                    ("I", "Initializing"),
                    ("P", "Pending"),
                    ("Q", "Queued"),
                    ("W", "Wired"),
                    ("S", "Sent"),
                    ("D", "Delivered"),
                    ("H", "Handled"),
                    ("E", "Error Sending"),
                    ("F", "Failed Sending"),
                    ("R", "Resent message"),
                ],
                default="I",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="broadcast", name="text", field=temba.utils.models.TranslatableField(max_length=640),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="urns",
            field=models.ManyToManyField(related_name="addressed_broadcasts", to="contacts.ContactURN"),
        ),
        migrations.AlterField(
            model_name="msg",
            name="attachments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(max_length=2048), null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="msg",
            name="broadcast",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="msgs",
                to="msgs.Broadcast",
            ),
        ),
        migrations.AlterField(
            model_name="msg",
            name="channel",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="msgs", to="channels.Channel"
            ),
        ),
        migrations.AlterField(
            model_name="msg",
            name="connection",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="msgs",
                to="channels.ChannelConnection",
            ),
        ),
        migrations.AlterField(
            model_name="msg",
            name="contact",
            field=models.ForeignKey(
                db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name="msgs", to="contacts.Contact"
            ),
        ),
        migrations.AlterField(
            model_name="msg",
            name="contact_urn",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="msgs", to="contacts.ContactURN"
            ),
        ),
        migrations.AlterField(model_name="msg", name="created_on", field=models.DateTimeField(db_index=True),),
        migrations.AlterField(
            model_name="msg",
            name="delete_reason",
            field=models.CharField(choices=[("A", "Archive delete"), ("U", "User delete")], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="msg",
            name="direction",
            field=models.CharField(choices=[("I", "Incoming"), ("O", "Outgoing")], max_length=1),
        ),
        migrations.AlterField(model_name="msg", name="error_count", field=models.IntegerField(default=0),),
        migrations.AlterField(
            model_name="msg", name="external_id", field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(model_name="msg", name="high_priority", field=models.BooleanField(null=True),),
        migrations.AlterField(
            model_name="msg", name="labels", field=models.ManyToManyField(related_name="msgs", to="msgs.Label"),
        ),
        migrations.AlterField(
            model_name="msg", name="metadata", field=temba.utils.models.JSONAsTextField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="msg", name="modified_on", field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(model_name="msg", name="msg_count", field=models.IntegerField(default=1),),
        migrations.AlterField(
            model_name="msg",
            name="msg_type",
            field=models.CharField(
                choices=[("I", "Inbox Message"), ("F", "Flow Message"), ("V", "IVR Message"), ("U", "USSD Message")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(model_name="msg", name="next_attempt", field=models.DateTimeField(auto_now_add=True),),
        migrations.AlterField(
            model_name="msg",
            name="org",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="msgs", to="orgs.Org"),
        ),
        migrations.AlterField(model_name="msg", name="queued_on", field=models.DateTimeField(blank=True, null=True),),
        migrations.AlterField(
            model_name="msg",
            name="response_to",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responses",
                to="msgs.Msg",
            ),
        ),
        migrations.AlterField(model_name="msg", name="sent_on", field=models.DateTimeField(blank=True, null=True),),
        migrations.AlterField(
            model_name="msg",
            name="status",
            field=models.CharField(
                choices=[
                    ("I", "Initializing"),
                    ("P", "Pending"),
                    ("Q", "Queued"),
                    ("W", "Wired"),
                    ("S", "Sent"),
                    ("D", "Delivered"),
                    ("H", "Handled"),
                    ("E", "Error Sending"),
                    ("F", "Failed Sending"),
                    ("R", "Resent message"),
                ],
                db_index=True,
                default="P",
                max_length=1,
            ),
        ),
        migrations.AlterField(model_name="msg", name="text", field=models.TextField(),),
        migrations.AlterField(
            model_name="msg", name="uuid", field=models.UUIDField(default=temba.utils.uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name="msg",
            name="visibility",
            field=models.CharField(
                choices=[("V", "Visible"), ("A", "Archived"), ("D", "Deleted")], default="V", max_length=1
            ),
        ),
    ]
