# Generated by Django 2.2.4 on 2020-04-02 15:34

from django.db import migrations
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0140_auto_20200317_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='text',
            field=temba.utils.models.TranslatableField(help_text='The localized versions of the message text', max_length=2000, verbose_name='Translations'),
        ),
    ]
