# Generated by Django 2.2.10 on 2020-12-04 17:21

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations, models

import temba.utils.models
import temba.utils.uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orgs", "0072_squashed"),
        ("contacts", "0129_squashed"),
        ("channels", "0124_squashed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schedules", "0014_squashed"),
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "raw_urns",
                    django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
                ),
                ("text", temba.utils.models.TranslatableField(max_length=640)),
                ("media", temba.utils.models.TranslatableField(max_length=2048, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("I", "Initializing"),
                            ("P", "Pending"),
                            ("Q", "Queued"),
                            ("W", "Wired"),
                            ("S", "Sent"),
                            ("D", "Delivered"),
                            ("H", "Handled"),
                            ("E", "Error Sending"),
                            ("F", "Failed Sending"),
                            ("R", "Resent message"),
                        ],
                        default="I",
                        max_length=1,
                    ),
                ),
                ("base_language", models.CharField(max_length=4)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this broadcast was created",
                    ),
                ),
                ("modified_on", models.DateTimeField(auto_now=True, help_text="When this item was last modified")),
                ("send_all", models.BooleanField(default=False)),
                ("metadata", temba.utils.models.JSONAsTextField(default=dict, null=True)),
                (
                    "channel",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="channels.Channel"),
                ),
                ("contacts", models.ManyToManyField(related_name="addressed_broadcasts", to="contacts.Contact")),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user which originally created this item",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="msgs_broadcast_creations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("groups", models.ManyToManyField(related_name="addressed_broadcasts", to="contacts.ContactGroup")),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="The user which last modified this item",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="msgs_broadcast_modifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("org", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="orgs.Org")),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="msgs.Broadcast",
                    ),
                ),
                (
                    "schedule",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="broadcast",
                        to="schedules.Schedule",
                    ),
                ),
                ("urns", models.ManyToManyField(related_name="addressed_broadcasts", to="contacts.ContactURN")),
            ],
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active, use this instead of deleting"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was originally created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was last modified",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        db_index=True,
                        default=temba.utils.models.generate_uuid,
                        help_text="The unique identifier for this object",
                        max_length=36,
                        unique=True,
                        verbose_name="Unique Identifier",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Choose a name for your label", max_length=64, verbose_name="Name"),
                ),
                (
                    "label_type",
                    models.CharField(
                        choices=[("F", "Folder of labels"), ("L", "Regular label")], default="L", max_length=1
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user which originally created this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="msgs_label_creations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="msgs.Label",
                        verbose_name="Folder",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="The user which last modified this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="msgs_label_modifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="msgs_labels", to="orgs.Org"
                    ),
                ),
            ],
            options={"abstract": False},
            managers=[("all_objects", django.db.models.manager.Manager())],
        ),
        migrations.CreateModel(
            name="Msg",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=temba.utils.uuid.uuid4, null=True)),
                ("text", models.TextField()),
                ("high_priority", models.BooleanField(null=True)),
                ("created_on", models.DateTimeField(db_index=True)),
                ("modified_on", models.DateTimeField(auto_now=True, null=True)),
                ("sent_on", models.DateTimeField(blank=True, null=True)),
                ("queued_on", models.DateTimeField(blank=True, null=True)),
                ("direction", models.CharField(choices=[("I", "Incoming"), ("O", "Outgoing")], max_length=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("I", "Initializing"),
                            ("P", "Pending"),
                            ("Q", "Queued"),
                            ("W", "Wired"),
                            ("S", "Sent"),
                            ("D", "Delivered"),
                            ("H", "Handled"),
                            ("E", "Error Sending"),
                            ("F", "Failed Sending"),
                            ("R", "Resent message"),
                        ],
                        db_index=True,
                        default="P",
                        max_length=1,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("V", "Visible"), ("A", "Archived"), ("D", "Deleted")], default="V", max_length=1
                    ),
                ),
                (
                    "msg_type",
                    models.CharField(
                        choices=[
                            ("I", "Inbox Message"),
                            ("F", "Flow Message"),
                            ("V", "IVR Message"),
                            ("U", "USSD Message"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("msg_count", models.IntegerField(default=1)),
                ("error_count", models.IntegerField(default=0)),
                ("next_attempt", models.DateTimeField(auto_now_add=True)),
                ("external_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "attachments",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(max_length=2048), null=True, size=None
                    ),
                ),
                ("metadata", temba.utils.models.JSONAsTextField(default=dict, null=True)),
                (
                    "delete_reason",
                    models.CharField(choices=[("A", "Archive delete"), ("U", "User delete")], max_length=1, null=True),
                ),
                (
                    "broadcast",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="msgs",
                        to="msgs.Broadcast",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="msgs",
                        to="channels.Channel",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="msgs",
                        to="channels.ChannelConnection",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="msgs",
                        to="contacts.Contact",
                    ),
                ),
                (
                    "contact_urn",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="msgs",
                        to="contacts.ContactURN",
                    ),
                ),
                ("labels", models.ManyToManyField(related_name="msgs", to="msgs.Label")),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="msgs", to="orgs.Org"),
                ),
                (
                    "response_to",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="msgs.Msg",
                    ),
                ),
                (
                    "topup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="msgs",
                        to="orgs.TopUp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabelCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_squashed",
                    models.BooleanField(default=False, help_text="Whether this row was created by squashing"),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, help_text="Whether this count is for archived messages"),
                ),
                ("count", models.IntegerField(default=0, help_text="Number of items with this system label")),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="counts", to="msgs.Label"
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ExportMessagesTask",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active, use this instead of deleting"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was originally created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was last modified",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        db_index=True,
                        default=temba.utils.models.generate_uuid,
                        help_text="The unique identifier for this object",
                        max_length=36,
                        unique=True,
                        verbose_name="Unique Identifier",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Pending"), ("O", "Processing"), ("C", "Complete"), ("F", "Failed")],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("system_label", models.CharField(max_length=1, null=True)),
                (
                    "start_date",
                    models.DateField(blank=True, help_text="The date for the oldest message to export", null=True),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, help_text="The date for the newest message to export", null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user which originally created this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="msgs_exportmessagestask_creations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("groups", models.ManyToManyField(to="contacts.ContactGroup")),
                ("label", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="msgs.Label")),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="The user which last modified this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="msgs_exportmessagestask_modifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="The organization of the user.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exportmessagestasks",
                        to="orgs.Org",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="BroadcastMsgCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_squashed",
                    models.BooleanField(default=False, help_text="Whether this row was created by squashing"),
                ),
                ("count", models.IntegerField(default=0)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="counts", to="msgs.Broadcast"
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="SystemLabelCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_squashed",
                    models.BooleanField(default=False, help_text="Whether this row was created by squashing"),
                ),
                (
                    "label_type",
                    models.CharField(
                        choices=[
                            ("I", "Inbox"),
                            ("W", "Flows"),
                            ("A", "Archived"),
                            ("O", "Outbox"),
                            ("S", "Sent"),
                            ("X", "Failed"),
                            ("E", "Scheduled"),
                            ("C", "Calls"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, help_text="Whether this count is for archived messages"),
                ),
                ("count", models.IntegerField(default=0, help_text="Number of items with this system label")),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="system_labels", to="orgs.Org"
                    ),
                ),
            ],
            options={"index_together": {("org", "label_type")}},
        ),
    ]
