# Generated by Django 2.2.4 on 2020-12-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0144_squashed'),
        ('msgs', '0139_squashed_ccl_139_141'),
    ]

    operations = [
    ]
