# Generated by Django 2.2.10 on 2021-01-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0144_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msg",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
