# Generated by Django 2.2.20 on 2021-05-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0145_auto_20210101_1559"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msg",
            name="next_attempt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="msg",
            name="queued_on",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="msg",
            name="sent_on",
            field=models.DateTimeField(null=True),
        ),
    ]
