# Generated by Django 2.2.19 on 2021-05-13 15:18

from django.db import migrations

from temba.utils import chunk_list


def clear_next_attempt(apps, schema_editor):  # pragma: no cover
    Msg = apps.get_model("msgs", "Msg")
    Channel = apps.get_model("channels", "Channel")

    android_ids = Channel.objects.filter(channel_type="A").values_list("id", flat=True)

    for android_chunk in chunk_list(android_ids, 100):
        Msg.objects.filter(channel_id__in=android_chunk).update(next_attempt=None)


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0146_auto_20210513_1516"),
    ]

    operations = [migrations.RunPython(clear_next_attempt, reverse)]
