# Generated by Django 2.2.20 on 2021-05-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0147_clear_next_attempt"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="msg",
            index=models.Index(
                condition=models.Q(("direction", "O"), ("next_attempt__isnull", False), ("status", "E")),
                fields=["next_attempt", "created_on", "id"],
                name="msgs_next_attempt_out_errored",
            ),
        ),
    ]
