# Generated by Django 2.2.20 on 2021-05-21 19:00

from django.db import migrations

NEXT_ATTEMPT_INDEX = """
CREATE INDEX IF NOT EXISTS msgs_next_attempt_outgoing_errored
ON msgs_msg(next_attempt, created_on, id)
WHERE direction = 'O' AND status = 'E' and next_attempt IS NOT NULL;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0147_clear_next_attempt"),
    ]

    operations = [
        migrations.RunSQL(
            NEXT_ATTEMPT_INDEX,
            "DROP INDEX msgs_next_attempt_outgoing_errored",
        ),
    ]
