# Generated by Django 2.2.20 on 2021-06-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0149_auto_20210621_1926"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="is_active",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddIndex(
            model_name="broadcast",
            index=models.Index(fields=["org", "-created_on", "-id"], name="msgs_broadcasts_org_created_id"),
        ),
        migrations.RunSQL("DROP INDEX msgs_broadcasts_org_created_id_where_active"),
    ]
