# Generated by Django 2.2.20 on 2021-06-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0150_auto_20210624_1931"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="is_active",
            field=models.BooleanField(null=True),
        ),
    ]
