# Generated by Django 2.2.27 on 2022-02-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0155_auto_20210715_1854"),
        ("msgs", "0147_msg_segments"),
    ]

    operations = []
