# Generated by Django 2.2.27 on 2022-03-16 13:38

from django.db import migrations
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0156_merge_20220223_1706"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="text",
            field=temba.utils.models.TranslatableField(max_length=640),
        ),
    ]
