# Generated by Django 2.2.27 on 2022-03-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0157_auto_20220316_1338"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="msg",
            name="segments",
        ),
    ]
