# Generated by Django 2.2.24 on 2022-03-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0157_auto_20220316_1338"),
        ("msgs", "0148_auto_20220216_1947"),
    ]

    operations = []
