# Generated by Django 2.2.24 on 2022-04-01 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0158_merge_20220316_1721"),
        ("msgs", "0158_remove_msg_segments"),
    ]

    operations = []
