# Generated by Django 3.2.9 on 2021-12-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0159_drop_uuid_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="msg",
            name="delete_from_counts",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="msg",
            name="delete_from_counts",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="msg",
            name="failed_reason",
            field=models.CharField(
                choices=[("S", "Suspended"), ("L", "Looping"), ("E", "Error Limit"), ("O", "Too Old")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="msg",
            name="external_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
