# Generated by Django 3.2.9 on 2021-12-03 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0160_auto_20211202_1446"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="msg",
            name="connection",
        ),
    ]
