# Generated by Django 4.0.2 on 2022-02-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0167_remove_delete_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="msg",
            name="delete_from_counts",
        ),
        migrations.RemoveField(
            model_name="msg",
            name="delete_reason",
        ),
    ]
