# Generated by Django 4.0.4 on 2022-05-02 18:22

from django.db import migrations, models

import temba.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0169_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="name",
            field=models.CharField(max_length=64, validators=[temba.utils.fields.NameValidator(64)]),
        ),
    ]
