# Generated by Django 4.0.4 on 2022-05-06 16:18

from uuid import uuid4

from django.db import migrations


def update_deleted_label_names(apps, schema_editor):  # pragma: no cover
    Label = apps.get_model("msgs", "Label")  # noqa

    num_inactive = 0
    for lb in Label.all_objects.filter(is_active=False).exclude(name__startswith="deleted-"):
        lb.name = f"deleted-{uuid4()}-{lb.name}"[:64]
        lb.save(update_fields=("name",))
        num_inactive += 1

    if num_inactive:
        print(f"Updated {num_inactive} deleted label names")


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0170_alter_label_name"),
    ]

    operations = [migrations.RunPython(update_deleted_label_names, reverse)]
