# Generated by Django 4.0.4 on 2022-05-06 17:21

import django.db.models.expressions
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0171_update_deleted_label_names"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="label",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("org"),
                django.db.models.functions.text.Lower("name"),
                name="unique_label_names",
            ),
        ),
    ]
