# Generated by Django 4.0.4 on 2022-05-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0172_label_unique_label_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
    ]
