# Generated by Django 4.0.4 on 2022-05-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0173_label_is_system"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="label",
            managers=[],
        ),
    ]
