# Generated by Django 4.0.4 on 2022-05-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0174_alter_label_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msg",
            name="failed_reason",
            field=models.CharField(
                choices=[
                    ("S", "Workspace suspended"),
                    ("L", "Looping detected"),
                    ("E", "Retry limit reached"),
                    ("O", "Too old to send"),
                    ("D", "No suitable channel found"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
