# Generated by Django 4.0.6 on 2022-07-26 19:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import temba.utils.uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orgs", "0101_remove_org_administrators_remove_org_agents_and_more"),
        ("msgs", "0175_alter_msg_failed_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=temba.utils.uuid.uuid4)),
                ("content_type", models.CharField(max_length=64)),
                ("path", models.CharField(max_length=2048)),
                ("url", models.URLField(db_index=True, max_length=2048)),
                ("is_ready", models.BooleanField(default=False)),
                ("duration", models.IntegerField(default=0)),
                (
                    "relationship",
                    models.CharField(choices=[("T", "Thumbnail"), ("A", "Alternate")], max_length=1, null=True),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                ("org", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="orgs.org")),
                (
                    "original",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="msgs.media",
                    ),
                ),
            ],
        ),
    ]
