# Generated by Django 4.0.6 on 2022-07-27 13:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import temba.utils.uuid


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0101_remove_org_administrators_remove_org_agents_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("msgs", "0175_alter_msg_failed_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=temba.utils.uuid.uuid4)),
                ("url", models.URLField(db_index=True, max_length=2048)),
                ("name", models.CharField(max_length=255)),
                ("paths", models.JSONField(default=dict)),
                ("is_ready", models.BooleanField(default=False)),
                ("duration", models.IntegerField(default=0)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                ("org", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="orgs.org")),
            ],
        ),
    ]
