# Generated by Django 4.0.6 on 2022-07-28 14:43

from django.db import migrations


def populate_media_path(apps, schema_editor):  # pragma: no cover
    Media = apps.get_model("msgs", "Media")
    for media in Media.objects.filter(content_type=None, path=None):
        content_type = list(media.paths.keys())[0]
        path = media.paths[content_type]

        media.content_type = content_type
        media.path = path
        media.save(update_fields=("content_type", "path"))


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0177_media_alternates_media_content_type_media_height_and_more"),
    ]

    operations = [migrations.RunPython(populate_media_path)]
