# Generated by Django 4.0.6 on 2022-07-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0178_populate_media_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="content_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="media",
            name="path",
            field=models.CharField(max_length=2048),
        ),
    ]
