# Generated by Django 4.0.6 on 2022-08-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0181_remove_media_is_ready"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
