# Generated by Django 4.0.6 on 2022-08-03 16:53

from django.db import migrations, models

import temba.utils.uuid


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0182_alter_media_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportmessagestask",
            name="uuid",
            field=models.UUIDField(default=temba.utils.uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="label",
            name="uuid",
            field=models.UUIDField(default=temba.utils.uuid.uuid4, unique=True),
        ),
    ]
