# Generated by Django 4.0.7 on 2022-09-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0187_update_db_triggers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemlabelcount",
            name="label_type",
            field=models.CharField(
                choices=[
                    ("I", "Inbox"),
                    ("W", "Flows"),
                    ("A", "Archived"),
                    ("O", "Outbox"),
                    ("S", "Sent"),
                    ("X", "Failed"),
                    ("E", "Scheduled"),
                ],
                max_length=1,
            ),
        ),
    ]
