# Generated by Django 4.0.7 on 2022-09-13 22:28

from django.db import migrations


def remove_call_counts(apps, schema_editor):  # pragma: no cover
    SystemLabelCount = apps.get_model("msgs", "SystemLabelCount")
    SystemLabelCount.objects.filter(label_type="C").delete()


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0188_alter_systemlabelcount_label_type"),
    ]

    operations = [migrations.RunPython(remove_call_counts, reverse)]
