# Generated by Django 4.0.7 on 2022-09-19 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0189_remove_calls_counts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="msg",
            name="logs",
        ),
    ]
