# Generated by Django 4.0.7 on 2022-09-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0190_remove_msg_logs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportmessagestask",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="exportmessagestask",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
