# Generated by Django 4.0.6 on 2022-10-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0192_exportmessagestask_with_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msg",
            name="failed_reason",
            field=models.CharField(
                choices=[
                    ("S", "Workspace suspended"),
                    ("C", "Contact is no longer active"),
                    ("L", "Looping detected"),
                    ("E", "Retry limit reached"),
                    ("O", "Too old to send"),
                    ("D", "No suitable channel found"),
                    ("R", "Channel removed"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
