# Generated by Django 4.0.7 on 2022-10-21 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0197_remove_broadcast_msgs_broadcasts_org_created_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exportmessagestask",
            name="groups",
        ),
    ]
