# Generated by Django 4.0.7 on 2022-11-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0201_flatten_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="label_type",
            field=models.CharField(max_length=1, null=True),
        ),
    ]
