# Generated by Django 4.0.7 on 2022-12-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0203_alter_msg_status"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="msg",
            index=models.Index(
                condition=models.Q(("direction", "O"), ("next_attempt__isnull", False), ("status__in", ("P", "E"))),
                fields=["next_attempt", "created_on", "id"],
                name="msgs_outgoing_to_retry",
            ),
        ),
        migrations.RemoveIndex(
            model_name="msg",
            name="msgs_next_attempt_out_errored",
        ),
    ]
