# Generated by Django 4.0.8 on 2023-01-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0204_remove_msg_msgs_next_attempt_out_errored_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="translations",
            field=models.JSONField(null=True),
        ),
    ]
