# Generated by Django 4.0.8 on 2023-01-24 16:10

from django.db import migrations

import temba.utils.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("msgs", "0208_populate_bcast_translations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="text",
            field=temba.utils.models.fields.TranslatableField(max_length=640, null=True),
        ),
    ]
