# Generated by Django 4.0.8 on 2023-01-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0208_populate_bcast_translations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="base_language",
            field=models.CharField(max_length=3),
        ),
    ]
