# Generated by Django 4.0.8 on 2023-01-31 21:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("msgs", "0212_msg_locale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="name",
        ),
    ]
