# Generated by Django 4.0.8 on 2023-01-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0213_remove_media_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="query",
            field=models.TextField(null=True),
        ),
    ]
