# Generated by Django 4.0.8 on 2023-02-01 19:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msgs", "0213_remove_media_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="query",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="msg",
            name="quick_replies",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), null=True, size=None
            ),
        ),
    ]
