# Generated by Django 4.0.9 on 2023-02-14 16:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msgs", "0217_remove_broadcast_send_all_remove_broadcast_urns"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="urns",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
    ]
