# Generated by Django 4.0.9 on 2023-02-27 22:05

from django.db import migrations, models

SQL = """
DROP INDEX msgs_msg_visibility_type_created_id_where_inbound;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0224_msg_msgs_api_incoming"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="msg",
            index=models.Index(
                condition=models.Q(("direction", "I"), ("flow__isnull", True), ("status", "H"), ("visibility", "V")),
                fields=["org", "-created_on", "-id"],
                name="msgs_inbox",
            ),
        ),
        migrations.AddIndex(
            model_name="msg",
            index=models.Index(
                condition=models.Q(("direction", "I"), ("flow__isnull", False), ("status", "H"), ("visibility", "V")),
                fields=["org", "-created_on", "-id"],
                name="msgs_flows",
            ),
        ),
        migrations.AddIndex(
            model_name="msg",
            index=models.Index(
                condition=models.Q(("direction", "I"), ("status", "H"), ("visibility", "A")),
                fields=["org", "-created_on", "-id"],
                name="msgs_archived",
            ),
        ),
        migrations.RunSQL(SQL),
    ]
