# Generated by Django 4.1.7 on 2023-03-07 16:48

import django.db.models.deletion
from django.db import migrations, models

import temba.utils.uuid


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0119_squashed"),
        ("msgs", "0227_msg_msgs_by_external_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="org",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="media", to="orgs.org"),
        ),
        migrations.AlterField(
            model_name="media",
            name="uuid",
            field=models.UUIDField(default=temba.utils.uuid.uuid4, unique=True),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(
                condition=models.Q(("original", None)), fields=["org", "-created_on"], name="media_originals_by_org"
            ),
        ),
    ]
