# Generated by Django 4.1.7 on 2023-03-08 22:19

from django.db import migrations

import temba.utils.uuid


def backfill_old_msg_uuids(apps, schema_editor):  # pragma: no cover
    Msg = apps.get_model("msgs", "Msg")

    num_updated = 0
    for msg in Msg.objects.filter(uuid=None):
        msg.uuid = temba.utils.uuid.uuid4()
        msg.save(update_fields=("uuid",))
        num_updated += 1

    if num_updated:
        print(f"Updated {num_updated} msgs without UUIDs")


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("msgs", "0228_alter_media_org_alter_media_uuid_and_more"),
    ]

    operations = [migrations.RunPython(backfill_old_msg_uuids, reverse)]
