# Generated by Django 4.1.7 on 2023-03-16 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msgs", "0230_alter_msg_msg_type_alter_msg_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name="broadcast",
            name="channel",
        ),
        migrations.RemoveField(
            model_name="broadcast",
            name="ticket",
        ),
        migrations.RunSQL("DROP INDEX msgs_broadcast_sending_idx"),
    ]
