# Generated by Django 4.1.7 on 2023-04-26 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0317_alter_flow_base_language"),
        ("tickets", "0052_backfill_ticketcount_by_topic"),
        ("msgs", "0232_msg_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msg",
            name="flow",
            field=models.ForeignKey(
                db_constraint=False,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="flows.flow",
            ),
        ),
        migrations.AlterField(
            model_name="msg",
            name="ticket",
            field=models.ForeignKey(
                db_constraint=False,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="tickets.ticket",
            ),
        ),
    ]
