# Generated by Django 4.1.9 on 2023-05-26 16:33

from django.db import migrations


def remove_archived_label_counts(apps, schema_editor):  # pragma: no cover
    SystemLabelCount = apps.get_model("msgs", "SystemLabelCount")

    while True:
        id_batch = list(SystemLabelCount.objects.filter(is_archived=True)[:1000].values_list("id", flat=True))
        if not id_batch:
            break
        SystemLabelCount.objects.filter(id__in=id_batch).delete()


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):  # pragma: no cover
    dependencies = [
        ("msgs", "0233_alter_msg_flow_alter_msg_ticket"),
    ]

    operations = [migrations.RunPython(remove_archived_label_counts, reverse)]
