# Generated by Django 4.1.9 on 2023-05-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msgs", "0236_update_label_count_db_triggers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemlabelcount",
            name="is_archived",
        ),
        migrations.AlterField(
            model_name="systemlabelcount",
            name="label_type",
            field=models.CharField(
                choices=[
                    ("I", "Inbox"),
                    ("W", "Flows"),
                    ("A", "Archived"),
                    ("O", "Outbox"),
                    ("S", "Sent"),
                    ("X", "Failed"),
                    ("E", "Scheduled"),
                    ("C", "Calls"),
                ],
                max_length=1,
            ),
        ),
    ]
