# Generated by Django 4.2.2 on 2023-07-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msgs", "0244_convert_msg_types"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="msg",
            name="msgs_inbox",
        ),
        migrations.RemoveIndex(
            model_name="msg",
            name="msgs_flows",
        ),
        migrations.RemoveIndex(
            model_name="msg",
            name="msgs_archived",
        ),
        migrations.AddIndex(
            model_name="msg",
            index=models.Index(
                condition=models.Q(
                    ("direction", "I"), ("flow__isnull", True), ("msg_type", "T"), ("status", "H"), ("visibility", "V")
                ),
                fields=["org", "-created_on", "-id"],
                name="msgs_inbox",
            ),
        ),
        migrations.AddIndex(
            model_name="msg",
            index=models.Index(
                condition=models.Q(
                    ("direction", "I"),
                    ("flow__isnull", False),
                    ("msg_type", "T"),
                    ("status", "H"),
                    ("visibility", "V"),
                ),
                fields=["org", "-created_on", "-id"],
                name="msgs_flows",
            ),
        ),
        migrations.AddIndex(
            model_name="msg",
            index=models.Index(
                condition=models.Q(("direction", "I"), ("msg_type", "T"), ("status", "H"), ("visibility", "A")),
                fields=["org", "-created_on", "-id"],
                name="msgs_archived",
            ),
        ),
    ]
