# Generated by Django 4.2.3 on 2023-09-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msgs", "0246_optin_optin_unique_optin_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msg",
            name="msg_type",
            field=models.CharField(
                choices=[("T", "Text Message"), ("O", "Opt-In Message"), ("V", "Voice Message")], max_length=1
            ),
        ),
    ]
