# Generated by Django 4.2.3 on 2023-09-21 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msgs", "0247_alter_msg_msg_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="msg",
            name="optin",
            field=models.ForeignKey(
                db_constraint=False,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="msgs.optin",
            ),
        ),
        migrations.AlterField(
            model_name="msg",
            name="msg_type",
            field=models.CharField(choices=[("T", "Text Message"), ("V", "Voice Message")], max_length=1),
        ),
    ]
