# Generated by Django 4.2.3 on 2023-09-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msgs", "0249_broadcast_optin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msg",
            name="msg_type",
            field=models.CharField(
                choices=[("T", "Text"), ("O", "Opt-In Request"), ("V", "Interactive Voice Response")], max_length=1
            ),
        ),
    ]
