# Generated by Django 4.2.3 on 2023-12-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msgs", "0251_remove_label_folder_remove_label_label_type"),
    ]

    operations = [
        migrations.RunSQL("DROP INDEX msgs_systemlabel_unsquashed;"),
        migrations.AlterIndexTogether(
            name="systemlabelcount",
            index_together=set(),
        ),
        migrations.AddIndex(
            model_name="systemlabelcount",
            index=models.Index(fields=["org", "label_type", "is_squashed"], name="msgs_system_org_id_086711_idx"),
        ),
    ]
