# Generated by Django 5.0.3 on 2024-04-09 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0258_alter_msg_modified_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="msg",
            name="queued_on",
        ),
    ]
