# Generated by Django 5.0.3 on 2024-04-10 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0185_alter_channel_name"),
        ("contacts", "0187_delete_exportcontactstask"),
        ("flows", "0333_delete_exportflowresultstask"),
        ("msgs", "0259_remove_msg_queued_on"),
        ("orgs", "0142_alter_usersettings_user"),
        ("tickets", "0060_delete_exportticketstask"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="msg",
            constraint=models.CheckConstraint(
                check=models.Q(("direction", "I"), ("direction", "O"), _connector="OR"), name="direction_is_in_or_out"
            ),
        ),
        migrations.AddConstraint(
            model_name="msg",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("direction", "O"),
                    models.Q(("channel__isnull", False), ("contact_urn__isnull", False)),
                    _connector="OR",
                ),
                name="incoming_has_channel_and_urn",
            ),
        ),
    ]
