# Generated by Django 5.0.3 on 2024-04-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0260_msg_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="msg",
            name="templating",
            field=models.JSONField(null=True),
        ),
    ]
