# Generated by Django 5.0.4 on 2024-04-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0261_msg_templating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msg",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("H", "Handled"),
                    ("I", "Initializing"),
                    ("Q", "Queued"),
                    ("W", "Wired"),
                    ("S", "Sent"),
                    ("D", "Delivered"),
                    ("R", "Read"),
                    ("E", "Error"),
                    ("F", "Failed"),
                ],
                db_index=True,
                default="P",
                max_length=1,
            ),
        ),
    ]
