# Generated by Django 5.0.4 on 2024-07-01 19:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0264_broadcast_exclusions"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="template_variables",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
    ]
