# Generated by Django 5.0.6 on 2024-07-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("msgs", "0265_broadcast_template_variables")]

    operations = [migrations.AddField(model_name="msg", name="is_android", field=models.BooleanField(null=True))]
