# Generated by Django 5.0.6 on 2024-07-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0266_msg_is_android"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="node_uuid",
            field=models.UUIDField(null=True),
        ),
    ]
