# Generated by Django 5.1 on 2024-09-19 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0269_msg_msgs_outgoing_android_to_fail"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="broadcast",
            name="msgs_broadcasts_queued",
        ),
    ]
