# Generated by Django 5.1 on 2024-09-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0270_remove_broadcast_msgs_broadcasts_queued"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="status",
            field=models.CharField(
                choices=[("Q", "Queued"), ("S", "Sent"), ("C", "Completed"), ("F", "Failed")], default="Q", max_length=1
            ),
        ),
    ]
