# Generated by Django 5.1 on 2024-09-20 16:27

from django.db import migrations, models


def fix_broadcast_statuses(apps, schema_editor):  # pragma: no cover
    Broadcast = apps.get_model("msgs", "Broadcast")
    num_updated = 0

    while True:
        batch_ids = Broadcast.objects.filter(status="S").values_list("id", flat=True)[:5000]
        if not batch_ids:
            break

        Broadcast.objects.filter(id__in=batch_ids).update(status="C")
        num_updated += len(batch_ids)

    if num_updated:
        print(f"Updated {num_updated} broadcasts from status=S to status=C")


class Migration(migrations.Migration):

    dependencies = [("msgs", "0271_alter_broadcast_status")]

    operations = [
        migrations.RunPython(fix_broadcast_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="broadcast",
            name="status",
            field=models.CharField(
                choices=[("Q", "Queued"), ("C", "Completed"), ("F", "Failed"), ("I", "Interrupted")],
                default="Q",
                max_length=1,
            ),
        ),
    ]
