# Generated by Django 5.1.2 on 2024-11-19 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0275_alter_broadcast_status"),
        ("orgs", "0159_usersettings_is_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="created_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="orgs.user"
            ),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="modified_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="orgs.user"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="created_by",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="orgs.user"),
        ),
        migrations.AlterField(
            model_name="msg",
            name="created_by",
            field=models.ForeignKey(
                db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, to="orgs.user"
            ),
        ),
    ]
