# Generated by Django 5.1.2 on 2024-12-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0276_alter_broadcast_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcastmsgcount",
            name="count",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="labelcount",
            name="count",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="systemlabelcount",
            name="count",
            field=models.IntegerField(),
        ),
    ]
