# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0076_install_triggers'),
        ('flows', '0081_install_triggers'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowPathRecentMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_uuid', models.UUIDField(help_text='Which flow node they came from')),
                ('to_uuid', models.UUIDField(null=True, help_text='Which flow node they went to')),
                ('flow', models.ForeignKey(help_text='The flow associated with the messages', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='flows.Flow')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_segments', to='msgs.Msg')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='flowpathrecentmessage',
            unique_together=set([('from_uuid', 'to_uuid', 'message')]),
        ),
    ]
