# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0076_install_triggers'),
        ('flows', '0083_populate_recent_msgs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flowpathrecentmessage',
            unique_together=set([('from_uuid', 'to_uuid', 'message')]),
        ),
    ]
