# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 16:29
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    DROP_SQL = """
    DROP INDEX IF EXISTS flows_flowstep_step_next_left_null_rule;
    DROP INDEX IF EXISTS flows_flowstep_step_next_rule_left;
    """

    dependencies = [
        ('flows', '0084_populate_recent_steps'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='flowstep',
            index_together=set([]),
        ),
        migrations.RunSQL(DROP_SQL)
    ]
