# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0086_is_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='version_number',
            field=models.IntegerField(default=11, help_text='The flow version this definition is in'),
        ),
        migrations.AlterField(
            model_name='flowrevision',
            name='spec_version',
            field=models.IntegerField(default=11, help_text='The flow version this definition is in'),
        ),
    ]
