# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 07:22
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations


SQL = """
-- this is performed in Python-land now
DROP FUNCTION temba_squash_flowruncount(INT, CHAR(1));

DROP FUNCTION temba_squash_flowpathcount(INTEGER, UUID, UUID, TIMESTAMP WITH TIME ZONE);
"""


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0087_fix_open_ended_ruleset_with_timeout'),
    ]

    operations = [
        migrations.RunSQL(SQL)
    ]
