# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0088_drop_squash_functions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportflowresultstask',
            name='is_finished',
            field=models.BooleanField(default=False, help_text='Whether this export has completed'),
        ),
        migrations.AlterField(
            model_name='exportflowresultstask',
            name='org',
            field=models.ForeignKey(help_text='The organization of the user.', on_delete=django.db.models.deletion.CASCADE, related_name='exportflowresultstasks', to='orgs.Org'),
        ),
    ]
