# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 06:57
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Case, Value, When


def populate_export_status(apps, schema_editor):
    ExportFlowResultsTask = apps.get_model('flows', 'ExportFlowResultsTask')
    ExportFlowResultsTask.objects.update(status=Case(When(is_finished=True, then=Value('C')), default=Value('O')))


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0089_baseexporttask_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportflowresultstask',
            name='is_finished',
        ),
    ]
