# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 20:05
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0091_auto_20170228_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowstart',
            name='include_active',
            field=models.BooleanField(default=True, help_text='Include contacts currently active in flows'),
        ),
    ]
