# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 15:25
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0103_auto_20170614_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowstart',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
