# Generated by Django 1.11.2 on 2017-06-22 15:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flows", "0103_auto_20170614_0918")]

    operations = [
        migrations.AddField(model_name="flowstart", name="uuid", field=models.UUIDField(default=uuid.uuid4, null=True))
    ]
