# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0106_auto_20170622_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='ussd_push_enabled',
            field=models.BooleanField(default=False, help_text='Whether USSD Push is enabled for this flow'),
        ),
    ]
