# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0074_channelsession_output'),
        ('flows', '0106_auto_20170622_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowSession',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('channels.channelsession',),
        ),
        migrations.AddField(
            model_name='flow',
            name='feature_class',
            field=models.IntegerField(default=100, help_text='Which class of features are used in this flow'),
        ),
        migrations.AddField(
            model_name='flowrun',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flowrun',
            name='uuid',
            field=models.CharField(db_index=True, default=temba.utils.models.generate_uuid, help_text='The unique identifier for this run', max_length=36, unique=True, verbose_name='Unique Identifier'),
        ),
    ]
