# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0067_auto_20170808_1852'),
        ('orgs', '0036_ensure_anon_user_exists'),
        ('channels', '0074_channel_schemes'),
        ('flows', '0110_auto_20170731_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('F', 'IVR'), ('U', 'USSD')], help_text='What type of session this is', max_length=1)),
                ('channel_session', models.ForeignKey(help_text='The channel session used for IVR and USSD type sessions', null=True, on_delete=django.db.models.deletion.CASCADE, to='channels.ChannelSession')),
                ('contact', models.ForeignKey(help_text='Who this session is with', on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact')),
                ('org', models.ForeignKey(help_text='The organization this session belongs to', on_delete=django.db.models.deletion.CASCADE, to='orgs.Org')),
            ],
        ),
    ]
