# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0067_auto_20170808_1852'),
        ('flows', '0111_auto_20170824_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='group_dependencies',
            field=models.ManyToManyField(blank=True, help_text='Any groups this flow uses', related_name='group_dependencies', to='contacts.ContactGroup', verbose_name='Group Dependencies'),
        ),
    ]
