# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0111_auto_20170628_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='created_on',
            field=models.DateTimeField(help_text='When this log event occurred'),
        ),
    ]
