# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0112_fix_sql_func'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowsession',
            name='output',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='flowsession',
            name='status',
            field=models.CharField(
                choices=[('W', 'Waiting'), ('C', 'Completed'), ('I', 'Interrupted'), ('X', 'Expired'),
                         ('E', 'Errored')], help_text='The status of this session', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='flowrun',
            name='output',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='flow',
            name='feature_flag',
            field=models.BigIntegerField(default=0x7FFFFFFFFFFFFFFF,
                                         help_text='Which features are used in this flow'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='created_on',
            field=models.DateTimeField(help_text='When this log event occurred'),
        ),
    ]
