# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 17:54
from __future__ import unicode_literals

from django.db import migrations
from temba.utils import chunk_list


def migrate_flows_forward(apps, schema_editor):
    from temba.flows.models import Flow
    flow_ids = list(Flow.objects.filter(is_active=True).values_list('id', flat=True))
    total = len(flow_ids)
    for id_batch in chunk_list(flow_ids, 1000):
        print("Updating flows: %d of %d" % (len(id_batch), total))
        for flow in Flow.objects.filter(id__in=id_batch):
            # bug out if we have any dependencies already
            if flow.group_dependencies.all().exists():
                return
            if flow.flow_dependencies.all().exists():
                return
            if flow.field_dependencies.all().exists():
                return
            flow.update(flow.as_json())


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0114_auto_20171020_1747'),
    ]

    operations = [
        migrations.RunPython(migrate_flows_forward)
    ]
