# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-18 17:11
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0119_flowrun_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowCategoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_squashed', models.BooleanField(default=False, help_text='Whether this row was created by squashing')),
                ('node_uuid', models.UUIDField(db_index=True)),
                ('result_key', models.CharField(help_text='The sluggified key for the result', max_length=36)),
                ('result_name', models.CharField(help_text='The result the category belongs to', max_length=36)),
                ('category_name', models.CharField(help_text='The category name for a result', max_length=36)),
                ('count', models.IntegerField(default=0)),
                ('flow', models.ForeignKey(help_text='The flow the result belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='category_counts', to='flows.Flow')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
