# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 16:43
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations, models
import temba.orgs.models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0124_auto_20171107_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionset',
            name='exit_uuid',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='version_number',
            field=models.CharField(default=temba.orgs.models.get_current_export_version, help_text='The flow version this definition is in', max_length=8),
        ),
        migrations.AlterField(
            model_name='flowrevision',
            name='spec_version',
            field=models.CharField(default=temba.orgs.models.get_current_export_version, help_text='The flow version this definition is in', max_length=8),
        ),
    ]
