# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 16:18
from __future__ import absolute_import, division, print_function, unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0129_auto_20171129_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowrun',
            name='submitted_by',
            field=models.ForeignKey(db_index=False, help_text='The user which submitted this flow run', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flowstep',
            name='left_on',
            field=models.DateTimeField(help_text='When the user left this step in the flow', null=True),
        ),
    ]
