# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 17:42
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations, models


def remove_incomplete_path_counts(apps, schema_editor):
    FlowPathCount = apps.get_model('flows', 'FlowPathCount')
    num_deleted, _ = FlowPathCount.objects.filter(to_uuid=None).delete()
    if num_deleted:
        print("Deleted %d incomplete flow path counts" % num_deleted)


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0132_path_trigger_update'),
    ]

    operations = [
        migrations.RunPython(remove_incomplete_path_counts),
        migrations.AlterField(
            model_name='flowpathcount',
            name='to_uuid',
            field=models.UUIDField(help_text='Which flow node they went to'),
        ),
    ]
