# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 19:09
from __future__ import unicode_literals

from django.db import migrations


SQL = """
CREATE INDEX CONCURRENTLY flows_flowrun_current_node_uuid_active_only 
ON flows_flowrun(current_node_uuid)
WHERE is_active = TRUE;"""


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('flows', '0137_populate_run_messages'),
    ]

    operations = [
        migrations.RunSQL(SQL)
    ]
