# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 16:14
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations, transaction
from temba.utils import chunk_list


def populate_recent_runs(FlowPathRecentMessage, FlowPathRecentRun):
    recent_msgs = FlowPathRecentMessage.objects.order_by('id')

    # don't convert any records that have already been added for new runs
    new_for_run = FlowPathRecentRun.objects.order_by('id').first()
    if new_for_run:
        recent_msgs = recent_msgs.filter(created_on__lt=new_for_run.visited_on)

    recent_msgs_count = recent_msgs.count()
    if not recent_msgs_count:
        return

    num_converted = 0
    for recent_msg_batch in chunk_list(recent_msgs.using('direct').iterator(), 1000):
        with transaction.atomic():
            for recent_msg in recent_msg_batch:

                FlowPathRecentRun.objects.create(
                    from_uuid=recent_msg.from_uuid,
                    to_uuid=recent_msg.to_uuid,
                    run=recent_msg.run,
                    visited_on=recent_msg.created_on
                )

            num_converted += len(recent_msg_batch)

        print(" > Converted %d of %d recent messages to recent runs" % (num_converted, recent_msgs_count))


def apply_manual():
    from temba.flows.models import FlowPathRecentMessage, FlowPathRecentRun
    populate_recent_runs(FlowPathRecentMessage, FlowPathRecentRun)


def apply_as_migration(apps, schema_editor):
    FlowPathRecentMessage = apps.get_model('flows', 'FlowPathRecentMessage')
    FlowPathRecentRun = apps.get_model('flows', 'FlowPathRecentRun')
    populate_recent_runs(FlowPathRecentMessage, FlowPathRecentRun)


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0142_flowpathrecentrun'),
    ]

    operations = [
        migrations.RunPython(apply_as_migration)
    ]
