# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 18:59
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0143_populate_recent_runs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowpathrecentmessage',
            name='run',
        ),
        migrations.DeleteModel(
            name='FlowPathRecentMessage',
        ),
    ]
