# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 10:15
from __future__ import unicode_literals

from django.db import migrations
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0145_update_path_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleset',
            name='config',
            field=temba.utils.models.JSONAsTextField(help_text='RuleSet type specific configuration', null=True, verbose_name='Ruleset Configuration'),
        ),
    ]
