# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 12:38
from __future__ import unicode_literals

from django.db import migrations
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0146_auto_20180125_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowstart',
            name='extra',
            field=temba.utils.models.JSONAsTextField(help_text='Any extra parameters to pass to the flow start (json)', null=True),
        ),
    ]
