# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 16:25
from __future__ import unicode_literals

from django.db import migrations
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0147_auto_20180128_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowrun',
            name='results',
            field=temba.utils.models.JSONAsTextField(default=dict, help_text='The results collected during this flow run in JSON format', null=True),
        ),
    ]
