# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 13:37
from __future__ import unicode_literals

from django.db import migrations
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0151_auto_20180129_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowrevision',
            name='definition',
            field=temba.utils.models.JSONAsTextField(help_text='The JSON flow definition'),
        ),
    ]
