# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-21 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0155_remove_flowrun_message_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowpathrecentrun',
            name='step1_uuid',
            field=models.UUIDField(help_text='The UUID of the first step', null=True),
        ),
        migrations.AddField(
            model_name='flowpathrecentrun',
            name='step2_uuid',
            field=models.UUIDField(help_text='The UUID of the second step', null=True),
        ),
    ]
