# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-28 18:33
from __future__ import unicode_literals

from django.db import migrations, models


def remove_stepless_recent_runs(apps, schema_editor):
    FlowPathRecentRun = apps.get_model("flows", "FlowPathRecentRun")
    deleted, objs_count = FlowPathRecentRun.objects.filter(from_step_uuid=None, to_step_uuid=None).delete()
    if deleted:
        print(f"Deleted {deleted} flow path recent runs without step information")


class Migration(migrations.Migration):

    dependencies = [("flows", "0160_auto_20180524_1612")]

    operations = [
        migrations.RunPython(remove_stepless_recent_runs),
        migrations.AlterField(
            model_name="flowpathrecentrun",
            name="from_step_uuid",
            field=models.UUIDField(help_text="The UUID of the first step"),
        ),
        migrations.AlterField(
            model_name="flowpathrecentrun",
            name="to_step_uuid",
            field=models.UUIDField(help_text="The UUID of the second step"),
        ),
    ]
