# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-28 17:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flows", "0161_auto_20180528_1833")]

    operations = [
        migrations.AddField(
            model_name="flowrun",
            name="child_context",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                help_text="Context of the last child subflow triggered by us", null=True
            ),
        ),
        migrations.AddField(
            model_name="flowrun",
            name="parent_context",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                help_text="Context of the parent run that triggered us", null=True
            ),
        ),
        migrations.AlterField(
            model_name="flowrun",
            name="parent",
            field=models.ForeignKey(
                help_text="The parent run that triggered us",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="flows.FlowRun",
            ),
        ),
    ]
