# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-05 15:46
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flows", "0163_backfill_related_run_contexts")]

    operations = [
        migrations.AlterField(
            model_name="actionlog",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="logs", to="flows.FlowRun"
            ),
        ),
        migrations.AlterField(
            model_name="actionset",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="action_sets", to="flows.Flow"
            ),
        ),
        migrations.AlterField(
            model_name="flow",
            name="org",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="flows", to="orgs.Org"),
        ),
        migrations.AlterField(
            model_name="flow",
            name="saved_by",
            field=models.ForeignKey(
                help_text="The user which last saved this flow",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flow_saves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="flowcategorycount",
            name="flow",
            field=models.ForeignKey(
                help_text="The flow the result belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="category_counts",
                to="flows.Flow",
            ),
        ),
        migrations.AlterField(
            model_name="flowlabel",
            name="org",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="orgs.Org"),
        ),
        migrations.AlterField(
            model_name="flowlabel",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="flows.FlowLabel",
                verbose_name="Parent",
            ),
        ),
        migrations.AlterField(
            model_name="flownodecount",
            name="flow",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="flows.Flow"),
        ),
        migrations.AlterField(
            model_name="flowpathcount",
            name="flow",
            field=models.ForeignKey(
                help_text="The flow where the activity occurred",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activity",
                to="flows.Flow",
            ),
        ),
        migrations.AlterField(
            model_name="flowpathrecentrun",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="recent_runs", to="flows.FlowRun"
            ),
        ),
        migrations.AlterField(
            model_name="flowrevision",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="revisions", to="flows.Flow"
            ),
        ),
        migrations.AlterField(
            model_name="flowrun",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                help_text="The session that handled this flow run, only for voice flows",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="channels.ChannelSession",
            ),
        ),
        migrations.AlterField(
            model_name="flowrun",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="runs", to="contacts.Contact"
            ),
        ),
        migrations.AlterField(
            model_name="flowrun",
            name="flow",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="runs", to="flows.Flow"),
        ),
        migrations.AlterField(
            model_name="flowrun",
            name="org",
            field=models.ForeignKey(
                db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name="runs", to="orgs.Org"
            ),
        ),
        migrations.AlterField(
            model_name="flowrun",
            name="parent",
            field=models.ForeignKey(
                help_text="The parent run that triggered us",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="flows.FlowRun",
            ),
        ),
        migrations.AlterField(
            model_name="flowrun",
            name="session",
            field=models.ForeignKey(
                help_text="The session that handled this flow run, only for voice flows",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="flows.FlowSession",
            ),
        ),
        migrations.AlterField(
            model_name="flowrun",
            name="start",
            field=models.ForeignKey(
                blank=True,
                help_text="The FlowStart objects that started this run",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="flows.FlowStart",
            ),
        ),
        migrations.AlterField(
            model_name="flowrun",
            name="submitted_by",
            field=models.ForeignKey(
                db_index=False,
                help_text="The user which submitted this flow run",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="flowruncount",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="counts", to="flows.Flow"
            ),
        ),
        migrations.AlterField(
            model_name="flowsession",
            name="connection",
            field=models.OneToOneField(
                help_text="The channel connection used for flow sessions over IVR or USSD",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="session",
                to="channels.ChannelSession",
            ),
        ),
        migrations.AlterField(
            model_name="flowsession",
            name="contact",
            field=models.ForeignKey(
                help_text="The contact that this session is with",
                on_delete=django.db.models.deletion.PROTECT,
                to="contacts.Contact",
            ),
        ),
        migrations.AlterField(
            model_name="flowsession",
            name="org",
            field=models.ForeignKey(
                help_text="The organization this session belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="orgs.Org",
            ),
        ),
        migrations.AlterField(
            model_name="flowstart",
            name="flow",
            field=models.ForeignKey(
                help_text="The flow that is being started",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="starts",
                to="flows.Flow",
            ),
        ),
        migrations.AlterField(
            model_name="flowstartcount",
            name="start",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="counts", to="flows.FlowStart"
            ),
        ),
        migrations.AlterField(
            model_name="ruleset",
            name="flow",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="rule_sets", to="flows.Flow"
            ),
        ),
    ]
