# Generated by Django 2.0.8 on 2018-08-30 15:34

from django.db import migrations

from temba.utils import chunk_list


def fix_flow_types(apps, schema_editor):
    Flow = apps.get_model("flows", "Flow")

    num_updated = 0
    for batch in chunk_list(Flow.objects.filter(flow_type="F"), 1000):
        Flow.objects.filter(id__in=[f.id for f in batch]).update(flow_type="M")
        num_updated += len(batch)
        print(f" > Updated {num_updated} flows with type F to type M")


class Migration(migrations.Migration):

    dependencies = [("flows", "0175_auto_20180829_1604")]

    operations = [migrations.RunPython(fix_flow_types)]
