# Generated by Django 2.0.8 on 2018-09-26 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flows", "0177_auto_20180905_1602")]

    operations = [
        migrations.AddField(
            model_name="flowsession",
            name="created_on",
            field=models.DateTimeField(help_text="When this session was created", null=True),
        ),
        migrations.AddField(
            model_name="flowsession",
            name="ended_on",
            field=models.DateTimeField(help_text="When this session ended", null=True),
        ),
        migrations.AlterField(
            model_name="flowsession",
            name="created_on",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="When this session was created", null=True
            ),
        ),
    ]
