# Generated by Django 2.0.8 on 2018-10-04 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flows", "0178_auto_20180926_1714")]

    operations = [
        migrations.AddField(
            model_name="flowsession",
            name="current_flow",
            field=models.ForeignKey(
                help_text="The flow of the waiting run",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="flows.Flow",
            ),
        )
    ]
