# Generated by Django 2.0.8 on 2018-10-04 20:15

from django.db import migrations

SQL = """
    -- indexes for fast fetching of unsquashed rows
    CREATE INDEX flows_flowcategorycount_unsquashed
    ON flows_flowcategorycount(flow_id, node_uuid, result_key, result_name, category_name) WHERE NOT is_squashed;

    CREATE INDEX flows_flownodecount_unsquashed
    ON flows_flownodecount(flow_id, node_uuid) WHERE NOT is_squashed;
"""


class Migration(migrations.Migration):

    dependencies = [("flows", "0179_flowsession_current_flow")]

    operations = [migrations.RunSQL(SQL)]
