# Generated by Django 2.0.8 on 2018-10-12 17:10

from django.db import migrations

SQL = """
CREATE INDEX CONCURRENTLY flows_flowsession_timeout
ON flows_flowsession(timeout_on) WHERE timeout_on IS NOT NULL AND status = 'W';
"""


class Migration(migrations.Migration):
    atomic = False

    dependencies = [("flows", "0182_flowrun_parent_uuid")]

    operations = [migrations.RunSQL(SQL)]
