# Generated by Django 2.0.8 on 2018-10-24 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flows", "0184_backfill_flowsession_dates")]

    operations = [
        migrations.AlterField(
            model_name="flowsession",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="When this session was created"),
        )
    ]
