# Generated by Django 2.0.8 on 2018-10-24 14:34

from django.db import migrations

SQL = """
CREATE INDEX CONCURRENTLY flows_flowsession_ended_on_not_null
ON flows_flowsession(ended_on ASC)
WHERE ended_on IS NOT NULL;
"""


class Migration(migrations.Migration):

    atomic = False

    dependencies = [("flows", "0185_auto_20181024_1430")]

    operations = [migrations.RunSQL(SQL)]
