# Generated by Django 2.1.3 on 2018-11-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flows", "0187_fix_expiration_date_for_ivr_and_ussd_runs")]

    operations = [
        migrations.AlterField(
            model_name="flowrun",
            name="delete_reason",
            field=models.CharField(
                choices=[("A", "Archive delete"), ("U", "User delete")],
                help_text="Why the run is being deleted",
                max_length=1,
                null=True,
            ),
        )
    ]
