# Generated by Django 2.1.3 on 2018-12-11 15:22

from django.db import migrations


def create_revisions(apps, schema_editor):
    from temba.flows.models import Flow

    # for each flow without a revision
    for flow in Flow.objects.filter(is_active=True, revisions=None):
        print(f"Creating revision for: {flow.name}")
        flow.update(flow.as_json())


class Migration(migrations.Migration):

    dependencies = [("flows", "0189_flowsession_wait_started_on")]

    operations = [migrations.RunPython(create_revisions)]
