# Generated by Django 2.1.5 on 2019-02-04 18:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flows", "0193_deactivate_ussd")]

    operations = [
        migrations.AddField(
            model_name="flowsession",
            name="session_type",
            field=models.CharField(
                choices=[("M", "Message flow"), ("V", "Phone call flow"), ("S", "Surveyor flow"), ("U", "USSD flow")],
                default="M",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flowsession",
            name="connection",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="session",
                to="channels.ChannelConnection",
            ),
        ),
        migrations.AlterField(
            model_name="flowsession",
            name="contact",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="contacts.Contact"),
        ),
        migrations.AlterField(
            model_name="flowsession", name="created_on", field=models.DateTimeField(default=django.utils.timezone.now)
        ),
        migrations.AlterField(
            model_name="flowsession",
            name="current_flow",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="flows.Flow"),
        ),
        migrations.AlterField(model_name="flowsession", name="ended_on", field=models.DateTimeField(null=True)),
        migrations.AlterField(
            model_name="flowsession",
            name="org",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="orgs.Org"),
        ),
        migrations.AlterField(model_name="flowsession", name="responded", field=models.BooleanField(default=False)),
        migrations.AlterField(
            model_name="flowsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("W", "Waiting"),
                    ("C", "Completed"),
                    ("I", "Interrupted"),
                    ("X", "Expired"),
                    ("F", "Failed"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(model_name="flowsession", name="timeout_on", field=models.DateTimeField(null=True)),
        migrations.AlterField(model_name="flowsession", name="wait_started_on", field=models.DateTimeField(null=True)),
    ]
