# Generated by Django 2.1.5 on 2019-03-22 20:59

from django.db import migrations

import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [("flows", "0194_auto_20190204_1835")]

    operations = [
        migrations.AlterField(
            model_name="flow", name="metadata", field=temba.utils.models.JSONAsTextField(default=dict, null=True)
        )
    ]
