# Generated by Django 2.1.8 on 2019-05-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0131_auto_20190422_2045"),
        ("channels", "0118_auto_20190307_0930"),
        ("flows", "0198_repopulate_flow_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="channel_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="channels.Channel"),
        ),
        migrations.AddField(
            model_name="flow",
            name="label_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="msgs.Label"),
        ),
    ]
