# Generated by Django 2.1.8 on 2019-07-03 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("flows", "0205_auto_20190703_2011")]

    operations = [migrations.RemoveField(model_name="flow", name="flow_server_enabled")]
