# Generated by Django 2.2.4 on 2019-08-14 19:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import temba.utils.json
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [("flows", "0211_populate_session_uuid")]

    operations = [
        migrations.AlterField(
            model_name="flowrun",
            name="child_context",
            field=temba.utils.models.JSONField(encoder=temba.utils.json.TembaEncoder, null=True),
        ),
        migrations.AlterField(
            model_name="flowrun",
            name="connection",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="channels.ChannelConnection",
            ),
        ),
        migrations.AlterField(
            model_name="flowrun", name="created_on", field=models.DateTimeField(default=django.utils.timezone.now)
        ),
        migrations.AlterField(model_name="flowrun", name="current_node_uuid", field=models.UUIDField(null=True)),
        migrations.AlterField(
            model_name="flowrun",
            name="delete_reason",
            field=models.CharField(choices=[("A", "Archive delete"), ("U", "User delete")], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="flowrun",
            name="events",
            field=temba.utils.models.JSONField(encoder=temba.utils.json.TembaEncoder, null=True),
        ),
        migrations.AlterField(
            model_name="flowrun",
            name="exit_type",
            field=models.CharField(
                choices=[("C", "Completed"), ("I", "Interrupted"), ("E", "Expired")], max_length=1, null=True
            ),
        ),
        migrations.AlterField(model_name="flowrun", name="exited_on", field=models.DateTimeField(null=True)),
        migrations.AlterField(model_name="flowrun", name="expires_on", field=models.DateTimeField(null=True)),
        migrations.AlterField(
            model_name="flowrun",
            name="fields",
            field=temba.utils.models.JSONAsTextField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(model_name="flowrun", name="is_active", field=models.BooleanField(default=True)),
        migrations.AlterField(model_name="flowrun", name="modified_on", field=models.DateTimeField(auto_now=True)),
        migrations.AlterField(
            model_name="flowrun",
            name="parent",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="flows.FlowRun"),
        ),
        migrations.AlterField(
            model_name="flowrun",
            name="parent_context",
            field=temba.utils.models.JSONField(encoder=temba.utils.json.TembaEncoder, null=True),
        ),
        migrations.AlterField(
            model_name="flowrun", name="path", field=temba.utils.models.JSONAsTextField(default=list, null=True)
        ),
        migrations.AlterField(model_name="flowrun", name="responded", field=models.BooleanField(default=False)),
        migrations.AlterField(
            model_name="flowrun", name="results", field=temba.utils.models.JSONAsTextField(default=dict, null=True)
        ),
        migrations.AlterField(
            model_name="flowrun",
            name="session",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="runs", to="flows.FlowSession"
            ),
        ),
        migrations.AlterField(
            model_name="flowrun",
            name="start",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="runs", to="flows.FlowStart"
            ),
        ),
        migrations.AlterField(
            model_name="flowrun",
            name="submitted_by",
            field=models.ForeignKey(
                db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(model_name="flowrun", name="timeout_on", field=models.DateTimeField(null=True)),
    ]
