# Generated by Django 2.2.4 on 2019-08-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flows", "0212_auto_20190814_1932")]

    operations = [
        migrations.AddField(model_name="flowrun", name="status", field=models.CharField(max_length=1, null=True))
    ]
