# Generated by Django 2.2.4 on 2019-08-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flows", "0214_populate_run_status")]

    operations = [
        migrations.AlterField(
            model_name="flowrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "Active"),
                    ("W", "Waiting"),
                    ("C", "Completed"),
                    ("I", "Interrupted"),
                    ("X", "Expired"),
                    ("F", "Failed"),
                ],
                max_length=1,
                null=True,
            ),
        )
    ]
