# Generated by Django 2.2.4 on 2019-08-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flows", "0214_populate_run_status")]

    operations = [
        # make FlowSession.uuid non-NULL and unique
        migrations.AlterField(model_name="flowsession", name="uuid", field=models.UUIDField(unique=True)),
        # make FlowRun.status non-NULL
        migrations.AlterField(model_name="flowrun", name="status", field=models.CharField(max_length=1)),
    ]
