# Generated by Django 2.2.4 on 2019-11-12 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flows", "0219_flow_classifier_dependencies")]

    operations = [
        migrations.AlterField(
            model_name="flowsession",
            name="current_flow",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="sessions", to="flows.Flow"
            ),
        ),
        migrations.AlterField(
            model_name="flowsession",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="sessions", to="orgs.Org"
            ),
        ),
    ]
