# Generated by Django 2.1.9 on 2019-11-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("globals", "0001_initial"), ("flows", "0220_auto_20191112_2255")]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="global_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="globals.Global"),
        )
    ]
