# Generated by Django 2.2.4 on 2020-03-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("flows", "0207_auto_20191211_0027"), ("flows", "0225_populate_template_deps")]

    operations = []
