# Generated by Django 2.2.4 on 2020-04-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flows", "0228_auto_20200413_2125")]

    operations = [
        migrations.AddIndex(
            model_name="flowstart",
            index=models.Index(
                condition=models.Q(created_by__isnull=False),
                fields=["org", "-created_on"],
                name="flows_flowstarts_org_created",
            ),
        )
    ]
