# Generated by Django 2.2.4 on 2020-04-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flows", "0231_populate_flowstart_type")]

    operations = [
        migrations.AlterField(
            model_name="flowstart",
            name="start_type",
            field=models.CharField(
                choices=[("M", "Manual"), ("A", "API"), ("F", "Flow Action"), ("T", "Trigger")], max_length=1
            ),
        )
    ]
