# Generated by Django 2.2.4 on 2020-04-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flows", "0233_auto_20200421_2224")]

    operations = [
        migrations.AlterField(
            model_name="flowstart",
            name="start_type",
            field=models.CharField(
                choices=[("M", "Manual"), ("A", "API"), ("Z", "Zapier"), ("F", "Flow Action"), ("T", "Trigger")],
                max_length=1,
            ),
        )
    ]
