# Generated by Django 2.2.4 on 2020-05-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tickets", "0001_initial"), ("flows", "0234_auto_20200427_1944")]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="ticketer_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="tickets.Ticketer"),
        )
    ]
