# Generated by Django 2.2.10 on 2020-10-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0238_flowstart_urns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flow",
            name="expires_after_minutes",
            field=models.IntegerField(
                default=10080, help_text="Minutes of inactivity that will cause expiration from flow"
            ),
        ),
    ]
