# Generated by Django 2.2.10 on 2020-10-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0240_auto_20201015_1515"),
    ]

    operations = [
        migrations.RemoveField(model_name="ruleset", name="flow",),
        migrations.DeleteModel(name="ActionSet",),
        migrations.DeleteModel(name="RuleSet",),
    ]
