# Generated by Django 2.2.10 on 2020-10-29 17:18

from django.db import migrations

SQL = """
DROP INDEX flows_flowrun_null_expired_on;
DROP INDEX flows_flowrun_timeout_active;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0241_auto_20201015_1521"),
    ]

    operations = [
        migrations.RunSQL(SQL),
        migrations.RemoveField(model_name="flowrun", name="timeout_on",),
    ]
