# Generated by Django 2.2.10 on 2020-12-04 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("templates", "0007_squashed"),
        ("flows", "0243_squashed"),
        ("orgs", "0072_squashed"),
        ("channels", "0125_squashed"),
        ("msgs", "0144_squashed"),
        ("contacts", "0129_squashed"),
        ("classifiers", "0004_squashed"),
        ("tickets", "0004_squashed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("globals", "0003_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowstart",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="flow_starts", to="orgs.Org"
            ),
        ),
        migrations.AddField(
            model_name="flowsession",
            name="connection",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="session",
                to="channels.ChannelConnection",
            ),
        ),
        migrations.AddField(
            model_name="flowsession",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="sessions", to="contacts.Contact"
            ),
        ),
        migrations.AddField(
            model_name="flowsession",
            name="current_flow",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="sessions", to="flows.Flow"
            ),
        ),
        migrations.AddField(
            model_name="flowsession",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="sessions", to="orgs.Org"
            ),
        ),
        migrations.AddField(
            model_name="flowruncount",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="exit_counts", to="flows.Flow"
            ),
        ),
        migrations.AddField(
            model_name="flowrun",
            name="connection",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="channels.ChannelConnection",
            ),
        ),
        migrations.AddField(
            model_name="flowrun",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="runs", to="contacts.Contact"
            ),
        ),
        migrations.AddField(
            model_name="flowrun",
            name="flow",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="runs", to="flows.Flow"),
        ),
        migrations.AddField(
            model_name="flowrun",
            name="org",
            field=models.ForeignKey(
                db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name="runs", to="orgs.Org"
            ),
        ),
        migrations.AddField(
            model_name="flowrun",
            name="parent",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="flows.FlowRun"),
        ),
        migrations.AddField(
            model_name="flowrun",
            name="session",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="runs", to="flows.FlowSession"
            ),
        ),
        migrations.AddField(
            model_name="flowrun",
            name="start",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="runs", to="flows.FlowStart"
            ),
        ),
        migrations.AddField(
            model_name="flowrun",
            name="submitted_by",
            field=models.ForeignKey(
                db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="flowrevision",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flows_flowrevision_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flowrevision",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="revisions", to="flows.Flow"
            ),
        ),
        migrations.AddField(
            model_name="flowrevision",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flows_flowrevision_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flowpathrecentrun",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="recent_runs", to="flows.FlowRun"
            ),
        ),
        migrations.AddField(
            model_name="flowpathcount",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="path_counts", to="flows.Flow"
            ),
        ),
        migrations.AddField(
            model_name="flownodecount",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="node_counts", to="flows.Flow"
            ),
        ),
        migrations.AddField(
            model_name="flowlabel",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="flow_labels", to="orgs.Org"
            ),
        ),
        migrations.AddField(
            model_name="flowlabel",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="flows.FlowLabel",
                verbose_name="Parent",
            ),
        ),
        migrations.AddField(
            model_name="flowcategorycount",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="category_counts", to="flows.Flow"
            ),
        ),
        migrations.AddField(
            model_name="flow",
            name="channel_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="channels.Channel"),
        ),
        migrations.AddField(
            model_name="flow",
            name="classifier_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="classifiers.Classifier"),
        ),
        migrations.AddField(
            model_name="flow",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flows_flow_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flow",
            name="field_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="contacts.ContactField"),
        ),
        migrations.AddField(
            model_name="flow",
            name="flow_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="flows.Flow"),
        ),
        migrations.AddField(
            model_name="flow",
            name="global_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="globals.Global"),
        ),
        migrations.AddField(
            model_name="flow",
            name="group_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="contacts.ContactGroup"),
        ),
        migrations.AddField(
            model_name="flow",
            name="label_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="msgs.Label"),
        ),
        migrations.AddField(
            model_name="flow",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Any labels on this flow",
                related_name="flows",
                to="flows.FlowLabel",
                verbose_name="Labels",
            ),
        ),
        migrations.AddField(
            model_name="flow",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flows_flow_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flow",
            name="org",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="flows", to="orgs.Org"),
        ),
        migrations.AddField(
            model_name="flow",
            name="saved_by",
            field=models.ForeignKey(
                help_text="The user which last saved this flow",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flow_saves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flow",
            name="template_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="templates.Template"),
        ),
        migrations.AddField(
            model_name="flow",
            name="ticketer_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="tickets.Ticketer"),
        ),
        migrations.AddField(
            model_name="exportflowresultstask",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flows_exportflowresultstask_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exportflowresultstask",
            name="flows",
            field=models.ManyToManyField(help_text="The flows to export", related_name="exports", to="flows.Flow"),
        ),
        migrations.AddField(
            model_name="exportflowresultstask",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flows_exportflowresultstask_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exportflowresultstask",
            name="org",
            field=models.ForeignKey(
                help_text="The organization of the user.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exportflowresultstasks",
                to="orgs.Org",
            ),
        ),
        migrations.AddIndex(
            model_name="flowstart",
            index=models.Index(
                condition=models.Q(created_by__isnull=False),
                fields=["org", "-created_on"],
                name="flows_flowstarts_org_created",
            ),
        ),
        migrations.AddIndex(
            model_name="flowstart",
            index=models.Index(
                condition=models.Q(created_by__isnull=False),
                fields=["org", "-modified_on"],
                name="flows_flowstarts_org_modified",
            ),
        ),
        migrations.AlterIndexTogether(name="flowruncount", index_together={("flow", "exit_type")}),
        migrations.AddIndex(
            model_name="flowpathrecentrun",
            index=models.Index(fields=["from_uuid", "to_uuid", "-visited_on"], name="flows_flowp_from_uu_f5dc27_idx"),
        ),
        migrations.AlterIndexTogether(
            name="flowpathcount", index_together={("flow", "from_uuid", "to_uuid", "period")}
        ),
        migrations.AlterUniqueTogether(name="flowlabel", unique_together={("name", "parent", "org")}),
    ]
