# Generated by Django 2.2.4 on 2020-12-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0227_squashed_ccl_227_234'),
        ('flows', '0244_squashed'),
    ]

    operations = [
    ]
