# Generated by Django 2.2.10 on 2021-01-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0244_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flow",
            name="flow_type",
            field=models.CharField(
                choices=[("M", "Messaging"), ("V", "Phone Call"), ("B", "Background"), ("S", "Surveyor")],
                default="M",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="flowsession",
            name="session_type",
            field=models.CharField(
                choices=[("M", "Messaging"), ("V", "Phone Call"), ("B", "Background"), ("S", "Surveyor")],
                default="M",
                max_length=1,
            ),
        ),
    ]
