# Generated by Django 2.2.10 on 2021-01-05 14:57

from django.db import migrations, models

SQL = """
----------------------------------------------------------------------
-- Inserts a new flowpathrecentrun
----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION temba_insert_flowpathrecentrun(_from_uuid UUID, _from_step_uuid UUID, _to_uuid UUID, _to_step_uuid UUID, _run_id BIGINT, _visited_on TIMESTAMPTZ) RETURNS VOID AS $$
  BEGIN
    INSERT INTO flows_flowpathrecentrun("from_uuid", "from_step_uuid", "to_uuid", "to_step_uuid", "run_id", "visited_on")
      VALUES(_from_uuid, _from_step_uuid, _to_uuid, _to_step_uuid, _run_id, _visited_on);
  END;
$$ LANGUAGE plpgsql;

DROP FUNCTION temba_insert_flowpathrecentrun(_from_uuid UUID, _from_step_uuid UUID, _to_uuid UUID, _to_step_uuid UUID, _run_id INTEGER, _visited_on TIMESTAMPTZ)
"""


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0244_squashed"),
        ("sql", "0002_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowpathrecentrun", name="id", field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="flowrun", name="id", field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="flowsession", name="id", field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.RunSQL(SQL),
    ]
