# Generated by Django 2.2.10 on 2021-08-04 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0130_auto_20210420_1325"),
        ("flows", "0245_merge_20201214_1542"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowStepReplica",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "step_uuid",
                    models.CharField(
                        db_index=True, help_text="The UUID of the ActionSet or RuleSet for this step", max_length=36
                    ),
                ),
                (
                    "rule_uuid",
                    models.CharField(
                        help_text="For uuid of the rule that matched on this ruleset, null on ActionSets",
                        max_length=36,
                        null=True,
                    ),
                ),
                ("arrived_on", models.DateTimeField(help_text="When the contact arrived at this step in the flow")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="flow_steps", to="contacts.Contact"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="steps", to="flows.FlowRun"
                    ),
                ),
            ],
            options={
                "unique_together": {("run", "contact")},
            },
        ),
    ]
