# Generated by Django 2.2.10 on 2021-01-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0245_auto_20210107_1703"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="flowstart",
            index=models.Index(fields=["org", "start_type", "-created_on"], name="flows_flowstart_org_start_type"),
        ),
    ]
