# Generated by Django 2.2.10 on 2021-03-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0247_auto_20210126_1834"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowrun",
            name="exit_type",
            field=models.CharField(
                choices=[("C", "Completed"), ("I", "Interrupted"), ("E", "Expired"), ("F", "Failed")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flowruncount",
            name="exit_type",
            field=models.CharField(
                choices=[("C", "Completed"), ("I", "Interrupted"), ("E", "Expired"), ("F", "Failed")],
                max_length=1,
                null=True,
            ),
        ),
    ]
