# Generated by Django 2.2.20 on 2021-05-07 20:28

from django.db import migrations


def populate_has_issues(apps, schema_editor):  # pragma: no cover
    Flow = apps.get_model("flows", "Flow")

    num_with = 0
    num_without = 0

    for flow in Flow.objects.filter(has_issues=None).only("id", "has_issues", "metadata"):
        has_issues = len(flow.metadata.get("issues", [])) > 0
        flow.has_issues = has_issues
        flow.save(update_fields=("has_issues",))
        if has_issues:
            num_with += 1
        else:
            num_without += 1

    if num_with or num_without:
        print(f"Updated has_issues for {num_with} flows with issues and {num_without} without issues")


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0250_flow_has_issues"),
    ]

    operations = [migrations.RunPython(populate_has_issues, reverse)]
