# Generated by Django 2.2.20 on 2021-05-12 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0251_populate_flow_has_issues"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flow",
            name="has_issues",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="flow",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="flow",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="flow",
            name="labels",
            field=models.ManyToManyField(related_name="flows", to="flows.FlowLabel"),
        ),
        migrations.AlterField(
            model_name="flow",
            name="saved_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="flow_saves", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="flow",
            name="saved_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="flow",
            name="version_number",
            field=models.CharField(default="11.12", max_length=8),
        ),
    ]
