# Generated by Django 2.2.20 on 2021-05-17 21:40

from django.db import migrations


def cleanup_dependencies(apps, schema_editor):  # pragma: no cover
    Flow = apps.get_model("flows", "Flow")

    for flow in Flow.objects.filter(is_active=False):
        flow.channel_dependencies.clear()
        flow.classifier_dependencies.clear()
        flow.field_dependencies.clear()
        flow.flow_dependencies.clear()
        flow.global_dependencies.clear()
        flow.group_dependencies.clear()
        flow.label_dependencies.clear()
        flow.ticketer_dependencies.clear()
        flow.template_dependencies.clear()


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0252_auto_20210512_1757"),
    ]

    operations = [migrations.RunPython(cleanup_dependencies, reverse)]
