# Generated by Django 2.2.20 on 2021-06-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0253_cleanup_dependencies"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowsession",
            name="output_url",
            field=models.URLField(null=True),
        ),
    ]
