# Generated by Django 2.2.20 on 2021-07-12 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0255_auto_20210609_1852"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowlabel",
            name="name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="flowlabel",
            name="parent",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="children", to="flows.FlowLabel"
            ),
        ),
    ]
