# Generated by Django 2.2.20 on 2021-06-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0255_auto_20210609_1852"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flow",
            name="base_language",
            field=models.CharField(
                default="eng",
                help_text="The authoring language, additional languages can be added later",
                max_length=4,
            ),
        ),
    ]
