# Generated by Django 2.2.20 on 2021-07-14 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0256_auto_20210712_1723"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flow",
            options={"ordering": ("-modified_on",), "verbose_name": "Flow", "verbose_name_plural": "Flows"},
        ),
    ]
