# Generated by Django 2.2.27 on 2022-02-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0251_auto_20220216_1405"),
        ("flows", "0258_auto_20210714_2158"),
    ]

    operations = []
