# Generated by Django 3.2.6 on 2021-08-25 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tickets", "0019_auto_20210818_1603"),
        ("flows", "0258_auto_20210714_2158"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="topic_dependencies",
            field=models.ManyToManyField(related_name="dependent_topics", to="tickets.Topic"),
        ),
        migrations.AddField(
            model_name="flow",
            name="user_dependencies",
            field=models.ManyToManyField(related_name="dependent_users", to=settings.AUTH_USER_MODEL),
        ),
    ]
