# Generated by Django 3.2.9 on 2021-12-20 13:10

from django.db import migrations, models

SQL = """
CREATE OR REPLACE FUNCTION temba_insert_flowpathrecentrun(_from_uuid UUID, _from_step_uuid UUID, _to_uuid UUID, _to_step_uuid UUID, _run_id BIGINT, _visited_on TIMESTAMPTZ) RETURNS VOID AS $$
  BEGIN
    INSERT INTO flows_flowpathrecentrun("from_uuid", "from_step_uuid", "to_uuid", "to_step_uuid", "run_id", "visited_on")
      VALUES(_from_uuid, _from_step_uuid, _to_uuid, _to_step_uuid, _run_id, _visited_on);
  END;
$$ LANGUAGE plpgsql;"""


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0259_auto_20210825_1438"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowrun",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
