# Generated by Django 3.2.9 on 2021-12-20 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0259_auto_20210825_1438"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowrun",
            name="parent",
        ),
    ]
