# Generated by Django 2.2.24 on 2022-03-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0259_merge_20220223_1705"),
        ("flows", "0251_auto_20220216_1405"),
    ]

    operations = []
