# Generated by Django 3.2.9 on 2022-01-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0261_alter_flowrun_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowsession",
            name="wait_expires_on",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddIndex(
            model_name="flowsession",
            index=models.Index(
                condition=models.Q(("session_type", "M"), ("status", "W"), ("wait_expires_on__isnull", False)),
                fields=["wait_expires_on"],
                name="flows_session_message_expires",
            ),
        ),
        migrations.AddIndex(
            model_name="flowsession",
            index=models.Index(
                condition=models.Q(("session_type", "V"), ("status", "W"), ("wait_expires_on__isnull", False)),
                fields=["wait_expires_on"],
                name="flows_session_voice_expires",
            ),
        ),
    ]
