# Generated by Django 3.2.9 on 2022-01-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0264_populate_session_wait_expires"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowrun",
            name="events",
        ),
        migrations.DeleteModel(
            name="FlowPathRecentRun",
        ),
    ]
