# Generated by Django 3.2.9 on 2022-01-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0264_populate_session_wait_expires"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowsession",
            name="wait_resume_on_expire",
            field=models.BooleanField(null=True),
        ),
    ]
