# Generated by Django 3.2.9 on 2022-01-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0268_populate_wait_resume_on_expire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowsession",
            name="wait_resume_on_expire",
            field=models.BooleanField(),
        ),
    ]
