# Generated by Django 4.0.2 on 2022-03-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0274_replace_exit_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowrun",
            name="is_active",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
