# Generated by Django 4.0.2 on 2022-03-01 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0275_alter_flowrun_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowrun",
            name="delete_reason",
        ),
        migrations.RemoveField(
            model_name="flowrun",
            name="exit_type",
        ),
        migrations.RemoveField(
            model_name="flowrun",
            name="is_active",
        ),
    ]
