# Generated by Django 4.0.3 on 2022-04-11 20:02

from uuid import uuid4

from django.db import migrations


def update_deleted_flow_names(apps, schema_editor):  # pragma: no cover
    Flow = apps.get_model("flows", "Flow")

    num_updated = 0
    for flow in Flow.objects.filter(is_active=False).exclude(name__startswith="deleted-"):
        flow.name = f"deleted-{uuid4()}-{flow.name}"[:64]
        flow.save(update_fields=("name",))
        num_updated += 1

    if num_updated:
        print(f"Updated {num_updated} names of deleted flows")


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0280_alter_flowrun_contact_and_more"),
    ]

    operations = [migrations.RunPython(update_deleted_flow_names, reverse)]
