# Generated by Django 4.0.4 on 2022-04-28 15:12

import django.db.models.expressions
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0283_unique_flow_names"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="flow",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("org"),
                django.db.models.functions.text.Lower("name"),
                name="unique_flow_names",
            ),
        ),
    ]
