# Generated by Django 4.0.4 on 2022-04-28 21:46

from django.db import migrations
from django.db.models import Q


def clean_name(original: str) -> str:
    return original.strip().replace('"', "'").replace("\\", "/").replace("\0", "")


def fix_invalid_flow_names(apps, schema_editor):
    Flow = apps.get_model("flows", "Flow")

    for flow in Flow.objects.filter(Q(name__icontains='"') | Q(name__icontains="\\")):
        old_name, new_name = flow.name, clean_name(flow.name)

        flow.name = new_name
        flow.save(update_fields=("name",))

        print(f" > flow {flow.uuid} '{old_name}' renamed to '{new_name}'")


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0284_flow_unique_flow_names"),
    ]

    operations = [migrations.RunPython(fix_invalid_flow_names, reverse)]
