# Generated by Django 4.0.4 on 2022-05-04 15:53

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import temba.utils.fields
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("flows", "0286_alter_flow_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="flowlabel",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="flowlabel",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_creations",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flowlabel",
            name="created_on",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                help_text="When this item was originally created",
            ),
        ),
        migrations.AddField(
            model_name="flowlabel",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this item is active, use this instead of deleting"
            ),
        ),
        migrations.AddField(
            model_name="flowlabel",
            name="modified_by",
            field=models.ForeignKey(
                default=1,
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flowlabel",
            name="modified_on",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                help_text="When this item was last modified",
            ),
        ),
        migrations.AlterField(
            model_name="flowlabel",
            name="name",
            field=models.CharField(max_length=64, validators=[temba.utils.fields.NameValidator(64)]),
        ),
        migrations.AlterField(
            model_name="flowlabel",
            name="uuid",
            field=models.CharField(
                db_index=True,
                default=temba.utils.models.generate_uuid,
                help_text="The unique identifier for this object",
                max_length=36,
                unique=True,
                verbose_name="Unique Identifier",
            ),
        ),
        migrations.AddConstraint(
            model_name="flowlabel",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("org"),
                django.db.models.functions.text.Lower("name"),
                name="unique_flowlabel_names",
            ),
        ),
    ]
