# Generated by Django 4.0.4 on 2022-06-15 14:15

from django.db import migrations
from django.utils import timezone

STATUS_ACTIVE = "A"
STATUS_WAITING = "W"
STATUS_FAILED = "F"


def fail_ghost_runs(apps, schema_editor):  # pragma: no cover
    FlowRun = apps.get_model("flows", "FlowRun")

    num_failed = 0
    while True:
        batch = list(FlowRun.objects.filter(session=None, status__in=(STATUS_ACTIVE, STATUS_WAITING)).only("id")[:100])
        if not batch:
            break

        now = timezone.now()
        FlowRun.objects.filter(id__in=[r.id for r in batch]).update(
            status=STATUS_FAILED, modified_on=now, exited_on=now
        )

        num_failed += len(batch)
        print(f"Failed {num_failed} active/waiting runs without a session")


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0288_flowlabel_is_system"),
    ]

    operations = [migrations.RunPython(fail_ghost_runs, reverse)]
