# Generated by Django 4.0.6 on 2022-07-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0292_ensure_session_ended_on"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="flowsession",
            constraint=models.CheckConstraint(
                check=models.Q(("status", "W"), ("ended_on__isnull", False), _connector="OR"),
                name="flows_session_non_waiting_has_ended_on",
            ),
        ),
    ]
