# Generated by Django 4.0.6 on 2022-07-21 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0039_ticket_opened_by_ticket_opened_in"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("flows", "0292_ensure_session_ended_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flow",
            name="topic_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="tickets.topic"),
        ),
        migrations.AlterField(
            model_name="flow",
            name="user_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to=settings.AUTH_USER_MODEL),
        ),
    ]
