# Generated by Django 4.0.6 on 2022-08-03 16:53

from django.db import migrations, models

import temba.utils.uuid


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0294_flowrun_flows_run_inactive_has_exited_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportflowresultstask",
            name="uuid",
            field=models.UUIDField(default=temba.utils.uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="flowlabel",
            name="uuid",
            field=models.UUIDField(default=temba.utils.uuid.uuid4, unique=True),
        ),
    ]
