# Generated by Django 4.0.7 on 2022-09-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0296_flowsession_call_flowstart_calls"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportflowresultstask",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="exportflowresultstask",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
