# Generated by Django 4.0.7 on 2022-10-17 20:16

from django.db import migrations

SQL = """
----------------------------------------------------------------------
-- Handles changes to a flow session's status
----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION temba_flowsession_status_change() RETURNS TRIGGER AS $$
BEGIN
  -- restrict changes
  IF OLD.status != 'W' AND NEW.status = 'W' THEN RAISE EXCEPTION 'Cannot restart an exited flow session'; END IF;

  RETURN NULL;
END;
$$ LANGUAGE plpgsql;


CREATE TRIGGER temba_flowsession_status_change
    AFTER UPDATE OF status ON flows_flowsession
    FOR EACH ROW EXECUTE PROCEDURE temba_flowsession_status_change();
"""


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0298_exportflowresultstask_with_fields"),
    ]

    operations = [migrations.RunSQL(SQL)]
