# Generated by Django 4.0.7 on 2022-12-06 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0302_flatten_flow_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowRunStatusCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("is_squashed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Active"),
                            ("W", "Waiting"),
                            ("C", "Completed"),
                            ("I", "Interrupted"),
                            ("X", "Expired"),
                            ("F", "Failed"),
                        ],
                        max_length=1,
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="status_counts", to="flows.flow"
                    ),
                ),
            ],
            options={
                "index_together": {("flow", "status")},
            },
        ),
    ]
