# Generated by Django 4.0.8 on 2023-01-11 15:35

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import temba.orgs.models
import temba.utils.fields
import temba.utils.json
import temba.utils.models.base
import temba.utils.models.fields
import temba.utils.uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExportFlowResultsTask",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active, use this instead of deleting"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was originally created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was last modified",
                    ),
                ),
                ("uuid", models.UUIDField(default=temba.utils.uuid.uuid4, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Pending"), ("O", "Processing"), ("C", "Complete"), ("F", "Failed")],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(null=True)),
                (
                    "config",
                    temba.utils.models.fields.JSONAsTextField(
                        default=dict, help_text="Any configuration options for this flow export", null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Flow",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active, use this instead of deleting"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was originally created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was last modified",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        db_index=True,
                        default=temba.utils.models.base.generate_uuid,
                        help_text="The unique identifier for this object",
                        max_length=36,
                        unique=True,
                        verbose_name="Unique Identifier",
                    ),
                ),
                ("name", models.CharField(max_length=64, validators=[temba.utils.fields.NameValidator(64)])),
                ("is_system", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "flow_type",
                    models.CharField(
                        choices=[("M", "Messaging"), ("V", "Phone Call"), ("B", "Background"), ("S", "Surveyor")],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "ignore_triggers",
                    models.BooleanField(default=False, help_text="Ignore keyword triggers while in this flow."),
                ),
                (
                    "expires_after_minutes",
                    models.IntegerField(
                        default=10080, help_text="Minutes of inactivity that will cause expiration from flow."
                    ),
                ),
                (
                    "base_language",
                    models.CharField(
                        default="und",
                        help_text="The authoring language, additional languages can be added later.",
                        max_length=4,
                    ),
                ),
                ("version_number", models.CharField(default="0.0.0", max_length=8)),
                ("metadata", temba.utils.models.fields.JSONAsTextField(default=dict, null=True)),
                ("has_issues", models.BooleanField(default=False)),
                ("saved_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Flow",
                "verbose_name_plural": "Flows",
                "ordering": ("-modified_on",),
            },
            bases=(models.Model, temba.orgs.models.DependencyMixin),
        ),
        migrations.CreateModel(
            name="FlowCategoryCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("is_squashed", models.BooleanField(default=False)),
                ("node_uuid", models.UUIDField(db_index=True)),
                ("result_key", models.CharField(max_length=128)),
                ("result_name", models.CharField(max_length=128)),
                ("category_name", models.CharField(max_length=128)),
                ("count", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FlowLabel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active, use this instead of deleting"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was originally created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was last modified",
                    ),
                ),
                ("uuid", models.UUIDField(default=temba.utils.uuid.uuid4, unique=True)),
                ("name", models.CharField(max_length=64, validators=[temba.utils.fields.NameValidator(64)])),
                ("is_system", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="FlowNodeCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("is_squashed", models.BooleanField(default=False)),
                ("node_uuid", models.UUIDField(db_index=True)),
                ("count", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FlowPathCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("is_squashed", models.BooleanField(default=False)),
                ("from_uuid", models.UUIDField()),
                ("to_uuid", models.UUIDField()),
                ("period", models.DateTimeField()),
                ("count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="FlowRevision",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active, use this instead of deleting"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was originally created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was last modified",
                    ),
                ),
                (
                    "definition",
                    temba.utils.models.fields.JSONAsTextField(default=dict, help_text="The JSON flow definition"),
                ),
                (
                    "spec_version",
                    models.CharField(default="11.12", help_text="The flow version this definition is in", max_length=8),
                ),
                ("revision", models.IntegerField(help_text="Revision number for this definition", null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FlowRun",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=temba.utils.uuid.uuid4, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Active"),
                            ("W", "Waiting"),
                            ("C", "Completed"),
                            ("I", "Interrupted"),
                            ("X", "Expired"),
                            ("F", "Failed"),
                        ],
                        max_length=1,
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("exited_on", models.DateTimeField(null=True)),
                ("responded", models.BooleanField(default=False)),
                ("results", temba.utils.models.fields.JSONAsTextField(default=dict, null=True)),
                ("path", temba.utils.models.fields.JSONAsTextField(default=list, null=True)),
                ("current_node_uuid", models.UUIDField(null=True)),
                ("delete_from_results", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FlowRunStatusCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("is_squashed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Active"),
                            ("W", "Waiting"),
                            ("C", "Completed"),
                            ("I", "Interrupted"),
                            ("X", "Expired"),
                            ("F", "Failed"),
                        ],
                        max_length=1,
                    ),
                ),
                ("count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="FlowSession",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("W", "Waiting"),
                            ("C", "Completed"),
                            ("I", "Interrupted"),
                            ("X", "Expired"),
                            ("F", "Failed"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[("M", "Messaging"), ("V", "Phone Call"), ("B", "Background"), ("S", "Surveyor")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("responded", models.BooleanField(default=False)),
                ("output", temba.utils.models.fields.JSONAsTextField(default=dict, null=True)),
                ("output_url", models.URLField(max_length=2048, null=True)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_on", models.DateTimeField(null=True)),
                ("wait_started_on", models.DateTimeField(null=True)),
                ("timeout_on", models.DateTimeField(null=True)),
                ("wait_expires_on", models.DateTimeField(null=True)),
                ("wait_resume_on_expire", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="FlowStart",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=temba.utils.uuid.uuid4, unique=True)),
                (
                    "start_type",
                    models.CharField(
                        choices=[
                            ("M", "Manual"),
                            ("A", "API"),
                            ("Z", "Zapier"),
                            ("F", "Flow Action"),
                            ("T", "Trigger"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "urns",
                    django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
                ),
                ("query", models.TextField(null=True)),
                ("restart_participants", models.BooleanField(default=True)),
                ("include_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Pending"), ("S", "Starting"), ("C", "Complete"), ("F", "Failed")],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("extra", temba.utils.models.fields.JSONAsTextField(default=dict, null=True)),
                (
                    "parent_summary",
                    temba.utils.models.fields.JSONField(
                        decoder=temba.utils.json.TembaDecoder, encoder=temba.utils.json.TembaEncoder, null=True
                    ),
                ),
                (
                    "session_history",
                    temba.utils.models.fields.JSONField(
                        decoder=temba.utils.json.TembaDecoder, encoder=temba.utils.json.TembaEncoder, null=True
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("modified_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("contact_count", models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FlowStartCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("is_squashed", models.BooleanField(default=False)),
                ("count", models.IntegerField(default=0)),
                (
                    "start",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="counts", to="flows.flowstart"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
