# Generated by Django 4.1.7 on 2023-05-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0317_alter_flow_base_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowstart",
            name="exclusions",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="flowstart",
            name="exclusions",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="flowstart",
            name="include_active",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="flowstart",
            name="restart_participants",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name="flowstart",
            name="params",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="flowstart",
            name="parent_summary",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="flowstart",
            name="session_history",
            field=models.JSONField(null=True),
        ),
    ]
