# Generated by Django 4.2.3 on 2023-09-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msgs", "0250_alter_msg_msg_type"),
        ("flows", "0320_update_db_triggers"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="optin_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="msgs.optin"),
        ),
    ]
