# Generated by Django 4.2.3 on 2023-12-11 20:49

from django.db import migrations, models

SQL = """
DROP INDEX flows_flowcategorycount_unsquashed;
DROP INDEX flows_flownodecount_unsquashed;
DROP INDEX flows_flowpathcount_unsquashed;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0324_index_cleanup"),
    ]

    operations = [
        migrations.RunSQL(SQL),
        migrations.AlterIndexTogether(
            name="flowpathcount",
            index_together=set(),
        ),
        migrations.AddIndex(
            model_name="flowcategorycount",
            index=models.Index(
                condition=models.Q(("is_squashed", False)),
                fields=["flow", "node_uuid", "result_key", "result_name", "category_name"],
                name="flowcategorycounts_unsquashed",
            ),
        ),
        migrations.AddIndex(
            model_name="flownodecount",
            index=models.Index(
                condition=models.Q(("is_squashed", False)),
                fields=["flow", "node_uuid"],
                name="flownodecounts_unsquashed",
            ),
        ),
        migrations.AddIndex(
            model_name="flowpathcount",
            index=models.Index(
                condition=models.Q(("is_squashed", False)),
                fields=["flow", "from_uuid", "to_uuid", "period"],
                name="flowpathcounts_unsquashed",
            ),
        ),
    ]
