# Generated by Django 4.2.8 on 2023-12-12 18:24

from django.db import migrations, models

SQL = """
DROP INDEX flows_flowrun_flow_modified_id;
DROP INDEX flows_flowrun_flow_modified_id_where_responded;
DROP INDEX flows_flowrun_org_modified_id;
DROP INDEX flows_flowrun_org_modified_id_where_responded;
DROP INDEX flows_flowsession_ended_on_not_null;
DROP INDEX flows_flowsession_timeout;
DROP INDEX flows_flowsession_waiting;
"""


class Migration(migrations.Migration):
    """
    Migration just moves indexes into Django and renames them, and is equivalent to...

    ALTER INDEX flows_flowrun_flow_modified_id RENAME TO flowruns_api_by_flow;
    ALTER INDEX flows_flowrun_flow_modified_id_where_responded RENAME TO flowruns_api_responded_by_flow;
    ALTER INDEX flows_flowrun_org_modified_id RENAME TO flowruns_api_by_org;
    ALTER INDEX flows_flowrun_org_modified_id_where_responded RENAME TO flowruns_api_responded_by_org;
    ALTER INDEX flows_flowsession_ended_on_not_null RENAME TO flowsessions_ended;
    ALTER INDEX flows_flowsession_timeout RENAME TO flowsessions_timed_out;
    ALTER INDEX flows_flowsession_waiting RENAME TO flowsessions_contact_waiting;
    """

    dependencies = [("flows", "0325_index_cleanup")]

    operations = [
        migrations.AddIndex(
            model_name="flowrun",
            index=models.Index(fields=["flow", "-modified_on", "-id"], name="flowruns_api_by_flow"),
        ),
        migrations.AddIndex(
            model_name="flowrun",
            index=models.Index(
                condition=models.Q(("responded", True)),
                fields=["flow", "-modified_on", "-id"],
                name="flowruns_api_responded_by_flow",
            ),
        ),
        migrations.AddIndex(
            model_name="flowrun",
            index=models.Index(fields=["org", "-modified_on", "-id"], name="flowruns_api_by_org"),
        ),
        migrations.AddIndex(
            model_name="flowrun",
            index=models.Index(
                condition=models.Q(("responded", True)),
                fields=["org", "-modified_on", "-id"],
                name="flowruns_api_responded_by_org",
            ),
        ),
        migrations.AddIndex(
            model_name="flowsession",
            index=models.Index(
                condition=models.Q(("status", "W")), fields=["contact_id"], name="flowsessions_contact_waiting"
            ),
        ),
        migrations.AddIndex(
            model_name="flowsession",
            index=models.Index(
                condition=models.Q(("status", "W"), ("timeout_on__isnull", False)),
                fields=["timeout_on"],
                name="flowsessions_timed_out",
            ),
        ),
        migrations.AddIndex(
            model_name="flowsession",
            index=models.Index(
                condition=models.Q(("ended_on__isnull", False)), fields=["ended_on"], name="flowsessions_ended"
            ),
        ),
        migrations.RunSQL(SQL),
    ]
