# Generated by Django 4.2.8 on 2024-01-05 15:09

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orgs", "0133_squashed"),
        ("globals", "0011_squashed"),
        ("templates", "0020_squashed"),
        ("ivr", "0028_squashed"),
        ("classifiers", "0013_squashed"),
        ("tickets", "0057_squashed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("channels", "0182_squashed"),
        ("flows", "0329_squashed"),
        ("contacts", "0184_squashed"),
        ("msgs", "0253_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowstart",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flow_starts",
                to="orgs.org",
            ),
        ),
        migrations.AddField(
            model_name="flowsession",
            name="call",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="session",
                to="ivr.call",
            ),
        ),
        migrations.AddField(
            model_name="flowsession",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="flowsession",
            name="current_flow",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="flows.flow",
            ),
        ),
        migrations.AddField(
            model_name="flowsession",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="orgs.org",
            ),
        ),
        migrations.AddField(
            model_name="flowrunstatuscount",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="status_counts",
                to="flows.flow",
            ),
        ),
        migrations.AddField(
            model_name="flowrun",
            name="contact",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="flowrun",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="flows.flow",
            ),
        ),
        migrations.AddField(
            model_name="flowrun",
            name="org",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="orgs.org",
            ),
        ),
        migrations.AddField(
            model_name="flowrun",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="flows.flowsession",
            ),
        ),
        migrations.AddField(
            model_name="flowrun",
            name="start",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="flows.flowstart",
            ),
        ),
        migrations.AddField(
            model_name="flowrun",
            name="submitted_by",
            field=models.ForeignKey(
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flowrevision",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revisions",
                to="orgs.user",
            ),
        ),
        migrations.AddField(
            model_name="flowrevision",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revisions",
                to="flows.flow",
            ),
        ),
        migrations.AddField(
            model_name="flowpathcount",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="path_counts",
                to="flows.flow",
            ),
        ),
        migrations.AddField(
            model_name="flownodecount",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="node_counts",
                to="flows.flow",
            ),
        ),
        migrations.AddField(
            model_name="flowlabel",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flowlabel",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flowlabel",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flow_labels",
                to="orgs.org",
            ),
        ),
        migrations.AddField(
            model_name="flowcategorycount",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="category_counts",
                to="flows.flow",
            ),
        ),
        migrations.AddField(
            model_name="flow",
            name="channel_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="channels.channel"),
        ),
        migrations.AddField(
            model_name="flow",
            name="classifier_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="classifiers.classifier"),
        ),
        migrations.AddField(
            model_name="flow",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flow",
            name="field_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="contacts.contactfield"),
        ),
        migrations.AddField(
            model_name="flow",
            name="flow_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="flows.flow"),
        ),
        migrations.AddField(
            model_name="flow",
            name="global_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="globals.global"),
        ),
        migrations.AddField(
            model_name="flow",
            name="group_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="contacts.contactgroup"),
        ),
        migrations.AddField(
            model_name="flow",
            name="label_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="msgs.label"),
        ),
        migrations.AddField(
            model_name="flow",
            name="labels",
            field=models.ManyToManyField(related_name="flows", to="flows.flowlabel"),
        ),
        migrations.AddField(
            model_name="flow",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flow",
            name="optin_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="msgs.optin"),
        ),
        migrations.AddField(
            model_name="flow",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flows",
                to="orgs.org",
            ),
        ),
        migrations.AddField(
            model_name="flow",
            name="saved_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flow_saves",
                to="orgs.user",
            ),
        ),
        migrations.AddField(
            model_name="flow",
            name="template_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="templates.template"),
        ),
        migrations.AddField(
            model_name="flow",
            name="topic_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="tickets.topic"),
        ),
        migrations.AddField(
            model_name="flow",
            name="user_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="orgs.user"),
        ),
        migrations.AddField(
            model_name="exportflowresultstask",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exportflowresultstask",
            name="flows",
            field=models.ManyToManyField(help_text="The flows to export", related_name="exports", to="flows.flow"),
        ),
        migrations.AddField(
            model_name="exportflowresultstask",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exportflowresultstask",
            name="org",
            field=models.ForeignKey(
                help_text="The organization of the user.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="orgs.org",
            ),
        ),
        migrations.AddField(
            model_name="exportflowresultstask",
            name="with_fields",
            field=models.ManyToManyField(related_name="%(class)s_exports", to="contacts.contactfield"),
        ),
        migrations.AddField(
            model_name="exportflowresultstask",
            name="with_groups",
            field=models.ManyToManyField(related_name="%(class)s_exports", to="contacts.contactgroup"),
        ),
        migrations.AddIndex(
            model_name="flowstartcount",
            index=models.Index(
                condition=models.Q(("is_squashed", False)),
                fields=["start"],
                name="flowstartcounts_unsquashed",
            ),
        ),
        migrations.AddIndex(
            model_name="flowstart",
            index=models.Index(
                condition=models.Q(("created_by__isnull", False)),
                fields=["org", "-created_on"],
                name="flows_flowstarts_org_created",
            ),
        ),
        migrations.AddIndex(
            model_name="flowstart",
            index=models.Index(
                condition=models.Q(("created_by__isnull", False)),
                fields=["org", "-modified_on"],
                name="flows_flowstarts_org_modified",
            ),
        ),
        migrations.AddIndex(
            model_name="flowstart",
            index=models.Index(
                fields=["org", "start_type", "-created_on"],
                name="flows_flowstart_org_start_type",
            ),
        ),
        migrations.AddIndex(
            model_name="flowsession",
            index=models.Index(
                condition=models.Q(("status", "W")),
                fields=["contact_id"],
                name="flowsessions_contact_waiting",
            ),
        ),
        migrations.AddIndex(
            model_name="flowsession",
            index=models.Index(
                condition=models.Q(("status", "W"), ("timeout_on__isnull", False)),
                fields=["timeout_on"],
                name="flowsessions_timed_out",
            ),
        ),
        migrations.AddIndex(
            model_name="flowsession",
            index=models.Index(
                condition=models.Q(("ended_on__isnull", False)),
                fields=["ended_on"],
                name="flowsessions_ended",
            ),
        ),
        migrations.AddIndex(
            model_name="flowsession",
            index=models.Index(
                condition=models.Q(
                    ("session_type", "M"),
                    ("status", "W"),
                    ("wait_expires_on__isnull", False),
                ),
                fields=["wait_expires_on"],
                name="flows_session_message_expires",
            ),
        ),
        migrations.AddIndex(
            model_name="flowsession",
            index=models.Index(
                condition=models.Q(
                    ("session_type", "V"),
                    ("status", "W"),
                    ("wait_expires_on__isnull", False),
                ),
                fields=["wait_expires_on"],
                name="flows_session_voice_expires",
            ),
        ),
        migrations.AddConstraint(
            model_name="flowsession",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("status", "W"), _negated=True),
                    models.Q(
                        ("wait_expires_on__isnull", False),
                        ("wait_started_on__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="flows_session_waiting_has_started_and_expires",
            ),
        ),
        migrations.AddConstraint(
            model_name="flowsession",
            constraint=models.CheckConstraint(
                check=models.Q(("status", "W"), ("ended_on__isnull", False), _connector="OR"),
                name="flows_session_non_waiting_has_ended_on",
            ),
        ),
        migrations.AddConstraint(
            model_name="flowsession",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("output__isnull", False),
                    ("output_url__isnull", False),
                    _connector="OR",
                ),
                name="flows_session_has_output_or_url",
            ),
        ),
        migrations.AddIndex(
            model_name="flowrunstatuscount",
            index=models.Index(fields=["flow", "status"], name="flows_flowr_flow_id_35baeb_idx"),
        ),
        migrations.AddIndex(
            model_name="flowrunstatuscount",
            index=models.Index(
                condition=models.Q(("is_squashed", False)),
                fields=["flow", "status"],
                name="flowrun_count_unsquashed",
            ),
        ),
        migrations.AddIndex(
            model_name="flowrun",
            index=models.Index(fields=["flow", "-modified_on", "-id"], name="flowruns_api_by_flow"),
        ),
        migrations.AddIndex(
            model_name="flowrun",
            index=models.Index(
                condition=models.Q(("responded", True)),
                fields=["flow", "-modified_on", "-id"],
                name="flowruns_api_responded_by_flow",
            ),
        ),
        migrations.AddIndex(
            model_name="flowrun",
            index=models.Index(fields=["org", "-modified_on", "-id"], name="flowruns_api_by_org"),
        ),
        migrations.AddIndex(
            model_name="flowrun",
            index=models.Index(
                condition=models.Q(("responded", True)),
                fields=["org", "-modified_on", "-id"],
                name="flowruns_api_responded_by_org",
            ),
        ),
        migrations.AddIndex(
            model_name="flowrun",
            index=models.Index(
                condition=models.Q(("status__in", ("A", "W"))),
                fields=["org", "current_node_uuid"],
                include=("contact",),
                name="flows_flowrun_contacts_at_node",
            ),
        ),
        migrations.AddIndex(
            model_name="flowrun",
            index=models.Index(
                fields=["contact"],
                include=("flow",),
                name="flows_flowrun_contact_inc_flow",
            ),
        ),
        migrations.AddConstraint(
            model_name="flowrun",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("status__in", ("A", "W")), _negated=True),
                    ("session__isnull", False),
                    _connector="OR",
                ),
                name="flows_run_active_or_waiting_has_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="flowrun",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("status__in", ("A", "W")),
                    ("exited_on__isnull", False),
                    _connector="OR",
                ),
                name="flows_run_inactive_has_exited_on",
            ),
        ),
        migrations.AddIndex(
            model_name="flowpathcount",
            index=models.Index(
                condition=models.Q(("is_squashed", False)),
                fields=["flow", "from_uuid", "to_uuid", "period"],
                name="flowpathcounts_unsquashed",
            ),
        ),
        migrations.AddIndex(
            model_name="flownodecount",
            index=models.Index(
                condition=models.Q(("is_squashed", False)),
                fields=["flow", "node_uuid"],
                name="flownodecounts_unsquashed",
            ),
        ),
        migrations.AddConstraint(
            model_name="flowlabel",
            constraint=models.UniqueConstraint(
                models.F("org"),
                django.db.models.functions.text.Lower("name"),
                name="unique_flowlabel_names",
            ),
        ),
        migrations.AddIndex(
            model_name="flowcategorycount",
            index=models.Index(
                condition=models.Q(("is_squashed", False)),
                fields=[
                    "flow",
                    "node_uuid",
                    "result_key",
                    "result_name",
                    "category_name",
                ],
                name="flowcategorycounts_unsquashed",
            ),
        ),
        migrations.AddConstraint(
            model_name="flow",
            constraint=models.UniqueConstraint(
                models.F("org"),
                django.db.models.functions.text.Lower("name"),
                name="unique_flow_names",
            ),
        ),
    ]
