# Generated by Django 5.0.3 on 2024-04-12 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0333_delete_exportflowresultstask"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowrun",
            name="submitted_by",
        ),
    ]
