# Generated by Django 5.1 on 2024-09-17 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0334_remove_flowrun_submitted_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="flowstart",
            name="modified_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="flowstart",
            name="created_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="flowstart",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("S", "Starting"), ("C", "Complete"), ("F", "Failed"), ("I", "Interrupted")],
                default="P",
                max_length=1,
            ),
        ),
    ]
