# Generated by Django 5.1 on 2024-09-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0335_flowstart_modified_by_alter_flowstart_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowstart",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("S", "Started"), ("C", "Completed"), ("F", "Failed"), ("I", "Interrupted")],
                default="P",
                max_length=1,
            ),
        ),
    ]
