# Generated by Django 5.1.2 on 2024-11-20 21:35

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0337_alter_flowstart_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowActivityCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("is_squashed", models.BooleanField(default=False)),
                ("scope", models.CharField(max_length=128)),
                ("count", models.IntegerField(default=0)),
                (
                    "flow",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="counts",
                        to="flows.flow",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        models.F("flow"),
                        django.contrib.postgres.indexes.OpClass("scope", name="varchar_pattern_ops"),
                        name="flowactivitycount_flow_scope",
                    ),
                    models.Index(
                        condition=models.Q(("is_squashed", False)),
                        fields=["flow", "scope"],
                        name="flowactivitycount_unsquashed",
                    ),
                ],
            },
        ),
    ]
