# Generated by Django 5.1.2 on 2024-11-21 17:54

from django.db import migrations

SQL = """
----------------------------------------------------------------------
-- Handles deletion of flow runs
----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION temba_flowrun_delete() RETURNS TRIGGER AS $$
DECLARE
    p INT;
    _path_json JSONB;
    _path_len INT;
BEGIN
    -- if this is a user delete then remove from results
    IF OLD.delete_from_results THEN
        PERFORM temba_update_category_counts(OLD.flow_id, NULL, OLD.results::json);
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;"""


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0338_flowactivitycount"),
        ("sql", "0006_squashed"),
    ]

    operations = [migrations.RunSQL(SQL)]
