# Generated by Django 5.1.2 on 2024-12-03 15:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0346_update_triggers"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowrun",
            name="path_nodes",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name="flowrun",
            name="path_times",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), null=True, size=None),
        ),
    ]
