# Generated by Django 2.1.8 on 2019-07-01 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orgs", "0001_initial"), ("locations", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="boundaryalias",
            name="org",
            field=models.ForeignKey(
                help_text="The org that owns this alias", on_delete=django.db.models.deletion.PROTECT, to="orgs.Org"
            ),
        )
    ]
