# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:24
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('locations', '0007_reset_2'),
    ]

    operations = [
        migrations.RunSQL(
            'CREATE INDEX CONCURRENTLY locations_adminboundary_name on locations_adminboundary(upper("name"))'),
        migrations.RunSQL(
            'CREATE INDEX CONCURRENTLY locations_boundaryalias_name on locations_boundaryalias(upper("name"))')
    ]
