# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-08 15:51
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_add_path_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminboundary',
            name='path',
            field=models.CharField(help_text='The full path name for this location', max_length=768),
        ),
    ]
