# Generated by Django 2.2.4 on 2020-03-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("locations", "0018_boundaryalias_org")]

    operations = [migrations.RemoveField(model_name="adminboundary", name="geometry")]
