# Generated by Django 2.2.10 on 2020-12-04 17:21

import mptt.fields

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0020_squashed"),
        ("orgs", "0072_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="boundaryalias",
            name="org",
            field=models.ForeignKey(
                help_text="The org that owns this alias", on_delete=django.db.models.deletion.PROTECT, to="orgs.Org"
            ),
        ),
        migrations.AddField(
            model_name="adminboundary",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="The parent to this political boundary if any",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="locations.AdminBoundary",
            ),
        ),
    ]
