# Generated by Django 3.2.6 on 2021-08-19 16:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orgs", "0088_auto_20210715_1825"),
        ("tickets", "0018_auto_20210803_2002"),
        ("msgs", "0156_auto_20210722_1429"),
        ("contacts", "0142_auto_20210803_2000"),
        ("flows", "0258_auto_20210714_2158"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=16)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="logs", to="msgs.broadcast"
                    ),
                ),
                (
                    "contact_export",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs",
                        to="contacts.exportcontactstask",
                    ),
                ),
                (
                    "contact_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="logs", to="contacts.contactimport"
                    ),
                ),
                (
                    "flow_start",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="logs", to="flows.flowstart"
                    ),
                ),
                (
                    "messages_export",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="logs", to="msgs.exportmessagestask"
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="logs", to="orgs.org"),
                ),
                (
                    "results_export",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs",
                        to="flows.exportflowresultstask",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="logs", to="tickets.ticket"
                    ),
                ),
                (
                    "ticket_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="logs", to="tickets.ticketevent"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="notifications.log",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="notifications", to="orgs.org"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
