# Generated by Django 3.2.8 on 2021-10-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_notificationcount"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="email_status",
            field=models.CharField(
                choices=[("P", "Pending"), ("S", "Sent"), ("N", "None")], default="N", max_length=1
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                condition=models.Q(("email_status", "P")), fields=["created_on"], name="notifications_email_pending"
            ),
        ),
    ]
