# Generated by Django 3.2.8 on 2021-11-12 18:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0259_auto_20210825_1438"),
        ("orgs", "0089_auto_20211111_1917"),
        ("notifications", "0005_auto_20211007_1713"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(max_length=16),
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_type", models.CharField(max_length=16)),
                ("started_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_on", models.DateTimeField(null=True)),
                (
                    "flow",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidents",
                        to="flows.flow",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="incidents", to="orgs.org"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="notification",
            name="incident",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notifications",
                to="notifications.incident",
            ),
        ),
    ]
