# Generated by Django 3.2.8 on 2021-11-16 20:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0259_auto_20210825_1438"),
        ("orgs", "0089_auto_20211111_1917"),
        ("notifications", "0005_auto_20211007_1713"),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_type", models.CharField(max_length=16)),
                ("scope", models.CharField(max_length=36)),
                ("started_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_on", models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="notification",
            name="notifications_unseen_of_type",
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(max_length=16),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                condition=models.Q(("is_seen", False)),
                fields=["org", "notification_type", "user"],
                name="notifications_unseen_of_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_seen", False)),
                fields=("org", "notification_type", "scope", "user"),
                name="notifications_unseen_scoped",
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="flow",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="incidents", to="flows.flow"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="incidents", to="orgs.org"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="incident",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notifications",
                to="notifications.incident",
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                condition=models.Q(("ended_on", None)), fields=["org", "-started_on"], name="incidents_org_ongoing"
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                condition=models.Q(("ended_on__isnull", False)),
                fields=["org", "-started_on"],
                name="incidents_org_ended",
            ),
        ),
        migrations.AddConstraint(
            model_name="incident",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_on", None)),
                fields=("org", "incident_type", "scope"),
                name="incidents_ongoing_scoped",
            ),
        ),
    ]
