# Generated by Django 3.2.8 on 2021-11-16 22:25

from django.db import migrations


def remove_alert_notifications(apps, schema_editor):  # pragma: no cover
    # channel:alert is no longer a notification type (replaced by incident:started)
    Notification = apps.get_model("notifications", "Notification")
    Notification.objects.filter(notification_type="channel:alert").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_auto_20211116_2221"),
    ]

    operations = [migrations.RunPython(remove_alert_notifications)]
