# Generated by Django 4.0.6 on 2022-09-15 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0040_exportticketstask"),
        ("notifications", "0008_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="ticket_export",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notifications",
                to="tickets.exportticketstask",
            ),
        ),
    ]
