# Generated by Django 4.1.7 on 2023-05-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0011_squashed"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_org_id_17c9ee_idx",
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["org", "user", "-created_on", "-id"], name="notificatio_org_id_f9db19_idx"),
        ),
    ]
