# Generated by Django 4.2.3 on 2023-11-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0012_remove_notification_notificatio_org_id_17c9ee_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="medium",
            field=models.CharField(max_length=2, null=True),
        ),
    ]
