# Generated by Django 4.2.3 on 2023-11-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0014_backfill_medium"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_org_id_f9db19_idx",
        ),
        migrations.AlterField(
            model_name="notification",
            name="medium",
            field=models.CharField(max_length=2),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                condition=models.Q(("medium__contains", "U")),
                fields=["org", "user", "-created_on", "-id"],
                name="notifications_user_ui",
            ),
        ),
    ]
