# Generated by Django 4.2.8 on 2024-01-05 15:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_type", models.CharField(max_length=20)),
                ("scope", models.CharField(max_length=36)),
                ("started_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_on", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("notification_type", models.CharField(max_length=16)),
                ("medium", models.CharField(max_length=2)),
                ("scope", models.CharField(max_length=36)),
                ("is_seen", models.BooleanField(default=False)),
                (
                    "email_status",
                    models.CharField(
                        choices=[("P", "Pending"), ("S", "Sent"), ("N", "None")],
                        default="N",
                        max_length=1,
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="NotificationCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
                ),
                ("is_squashed", models.BooleanField(default=False)),
                ("count", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
