# Generated by Django 4.2.8 on 2024-01-17 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0135_export"),
        ("notifications", "0018_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="export",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="notifications", to="orgs.export"
            ),
        ),
    ]
