# Generated by Django 4.2.8 on 2024-01-29 15:00

from datetime import timedelta

from django.db import migrations
from django.utils import timezone


def mark_old_seen(apps, schema_editor):  # pragma: no cover
    Notification = apps.get_model("notifications", "Notification")
    three_weeks_ago = timezone.now() - timedelta(days=21)
    old_unseen = Notification.objects.filter(created_on__lt=three_weeks_ago, is_seen=False)
    num_updated = 0

    while True:
        batch_ids = list(old_unseen.values_list("id", flat=True)[:1000])
        if not batch_ids:
            break

        Notification.objects.filter(id__in=batch_ids).update(is_seen=True)
        num_updated += len(batch_ids)

    if num_updated:
        print(f"Marked {num_updated} old notifications as seen")


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):
    dependencies = [("notifications", "0019_notification_export")]

    operations = [migrations.RunPython(mark_old_seen, reverse)]
