# Generated by Django 4.2.8 on 2024-03-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0020_mark_old_notifications_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="incident_type",
            field=models.CharField(max_length=32),
        ),
    ]
