# Generated by Django 5.0.3 on 2024-04-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0022_remove_notification_contact_export_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="email_address",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
