# Generated by Django 5.1.2 on 2024-11-05 16:22

from django.db import migrations, transaction


def backfill_item_counts(apps, schema_editor):  # pragma: no cover
    Org = apps.get_model("orgs", "Org")

    for org in Org.objects.all():
        user_ids = org.notifications.values_list("user_id", flat=True).distinct()

        for user_id in user_ids:
            with transaction.atomic():
                seen_count = org.notifications.filter(user_id=user_id, medium__contains="U", is_seen=True).count()
                unseen_count = org.notifications.filter(user_id=user_id, medium__contains="U", is_seen=False).count()

                org.counts.filter(scope__startswith=f"notifications:{user_id}:").delete()
                org.counts.create(scope=f"notifications:{user_id}:S", count=seen_count, is_squashed=True)
                org.counts.create(scope=f"notifications:{user_id}:U", count=unseen_count, is_squashed=True)


class Migration(migrations.Migration):

    dependencies = [("notifications", "0025_update_triggers")]

    operations = [migrations.RunPython(backfill_item_counts, migrations.RunPython.noop)]
