# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-16 20:43
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.auth.models import User
from django.db import migrations


def ensure_anon_user_exists(apps, schema_editor):
    if not User.objects.filter(username=settings.ANONYMOUS_USER_NAME).exists():  # pragma: no cover
        user = User(username=settings.ANONYMOUS_USER_NAME)
        user.set_unusable_password()
        user.save()


class Migration(migrations.Migration):

    dependencies = [("auth_tweaks", "0001_initial")]

    operations = [migrations.RunPython(ensure_anon_user_exists)]
