# Generated by Django 2.2.10 on 2020-11-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("globals", "0003_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="global",
            name="value",
            field=models.TextField(max_length=10000),
        ),
    ]
