# Generated by Django 4.0.4 on 2022-05-11 22:08

from django.db import migrations, models

import temba.utils.uuid


class Migration(migrations.Migration):

    dependencies = [
        ("globals", "0007_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="global",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="global",
            name="uuid",
            field=models.UUIDField(default=temba.utils.uuid.uuid4, unique=True),
        ),
    ]
