# Generated by Django 4.2.8 on 2024-01-05 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orgs", "0133_squashed"),
        ("globals", "0011_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="global",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="globals",
                to="orgs.org",
            ),
        ),
    ]
