# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 08:30
from __future__ import unicode_literals

from django.db import migrations, models
from temba.sql import InstallSQL


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0049_install_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactgroupcount',
            name='is_squashed',
            field=models.BooleanField(default=False, help_text='Whether this row was created by squashing'),
        ),
        InstallSQL('0050_contacts')
    ]
