# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0051_auto_20170208_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacturn',
            name='auth_token',
            field=models.TextField(help_text='The token used on channels with two identifiers', null=True),
        ),
    ]
