# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 12:16
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('contacts', '0056_exportcontactstask_search'),
    ]

    operations = [
        migrations.RunSQL("CREATE INDEX CONCURRENTLY contacts_contact_name "
                          "ON contacts_contact (org_id, UPPER(name));"),
        migrations.RunSQL("CREATE INDEX CONCURRENTLY contacts_contacturn_path "
                          "ON contacts_contacturn (org_id, UPPER(path), contact_id);")
    ]
