# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 18:52
from __future__ import absolute_import, division, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0036_ensure_anon_user_exists'),
        ('contacts', '0066_auto_20170804_2110'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contacturn',
            unique_together=set([('identity', 'org')]),
        ),
        migrations.RemoveField(
            model_name='contacturn',
            name='urn',
        ),
    ]
