# Generated by Django 1.11.6 on 2018-03-27 19:39

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    INDEX_SQL = """
            CREATE INDEX CONCURRENTLY IF NOT EXISTS contacts_contact_modified_on_non_test ON contacts_contact(modified_on) WHERE is_test = FALSE;
        """

    dependencies = [("contacts", "0074_create_fields_index")]

    operations = [migrations.RunSQL(INDEX_SQL, "")]
