# Generated by Django 1.11.6 on 2018-04-27 16:25

from django.db import migrations


FUNCTION_SQL = """
CREATE OR REPLACE FUNCTION
  extract_jsonb_keys(_jsonb JSONB)
RETURNS TEXT[] AS $$
BEGIN
  RETURN ARRAY(SELECT * FROM JSONB_OBJECT_KEYS(_jsonb));
END;
$$ IMMUTABLE LANGUAGE plpgsql;
"""

CREATE_SQL = """
CREATE INDEX CONCURRENTLY IF NOT EXISTS contact_fields_keys_idx ON contacts_contact USING GIN(extract_jsonb_keys(fields));
"""

DROP_SQL = """
DROP INDEX CONCURRENTLY IF EXISTS contacts_fields_idx;
"""


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('contacts', '0077_auto_20180418_1807'),
    ]

    operations = [
        migrations.RunSQL(FUNCTION_SQL),
        migrations.RunSQL(CREATE_SQL),
        migrations.RunSQL(DROP_SQL),
    ]
