# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-03 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0078_create_field_key_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactfield',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
