# Generated by Django 1.11.6 on 2018-05-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("contacts", "0079_auto_20180502_1624")]

    operations = [
        migrations.AddField(model_name="contactfield", name="priority", field=models.PositiveIntegerField(default=0))
    ]
