# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-14 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("contacts", "0081_auto_20180602_2316")]

    operations = [
        migrations.AddField(
            model_name="exportcontactstask",
            name="group_memberships",
            field=models.ManyToManyField(to="contacts.ContactGroup"),
        )
    ]
