# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-16 17:03
from __future__ import unicode_literals

from django.db import migrations

SQL = """
CREATE OR REPLACE FUNCTION
  extract_jsonb_keys(_jsonb JSONB)
RETURNS TEXT[] AS $$
BEGIN
  RETURN ARRAY(SELECT * FROM JSONB_OBJECT_KEYS(_jsonb));
END;
$$ IMMUTABLE LANGUAGE plpgsql;

CREATE INDEX IF NOT EXISTS contact_fields_keys_idx ON contacts_contact USING GIN(extract_jsonb_keys(fields));

CREATE INDEX IF NOT EXISTS contacts_contact_modified_on_non_test ON contacts_contact(modified_on) WHERE is_test = FALSE;

CREATE INDEX contacts_contact_name ON contacts_contact (org_id, UPPER(name));

CREATE INDEX contacts_contact_org_modified_id_where_nontest_active
ON contacts_contact (org_id, modified_on DESC, id DESC)
WHERE is_test = false AND is_active = true;

CREATE INDEX contacts_contact_org_modified_id_where_nontest_inactive
ON contacts_contact (org_id, modified_on DESC, id DESC)
WHERE is_test = false AND is_active = false;

-- index for fast fetching of unsquashed rows
CREATE INDEX contacts_contactgroupcount_unsquashed
ON contacts_contactgroupcount(group_id) WHERE NOT is_squashed;

CREATE INDEX contacts_contacturn_org_scheme_display ON contacts_contacturn (org_id, scheme, display)WHERE display IS NOT NULL;

CREATE INDEX contacts_contacturn_path ON contacts_contacturn (org_id, UPPER(path), contact_id);

CREATE INDEX org_test_contacts
ON contacts_contact (org_id) WHERE is_test = TRUE;
"""


class Migration(migrations.Migration):

    dependencies = [("contacts", "0084_initial")]

    operations = [migrations.RunSQL(SQL)]
