# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-16 17:03
from __future__ import unicode_literals

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import temba.utils.models

SQL = """
CREATE OR REPLACE FUNCTION
  extract_jsonb_keys(_jsonb JSONB)
RETURNS TEXT[] AS $$
BEGIN
  RETURN ARRAY(SELECT * FROM JSONB_OBJECT_KEYS(_jsonb));
END;
$$ IMMUTABLE LANGUAGE plpgsql;

CREATE INDEX IF NOT EXISTS contact_fields_keys_idx ON contacts_contact USING GIN(extract_jsonb_keys(fields));
CREATE INDEX IF NOT EXISTS contacts_contact_modified_on_non_test ON contacts_contact(modified_on) WHERE is_test = FALSE;

"""


class Migration(migrations.Migration):

    dependencies = [("contacts", "0084_initial")]

    operations = [
        migrations.AddField(
            model_name='Contact',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                help_text="The fields set for this contact, keyed by UUID", null=True, verbose_name="Fields"
            ),
        ),
        migrations.AddField(
            model_name='ContactField',
            name='priority',
            field= models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ExportContactsTask',
            name='group_memberships',
            field= models.ManyToManyField(to="contacts.ContactGroup")
        ),
        migrations.RunSQL(SQL)]
