# Generated by Django 2.0.8 on 2018-09-28 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("contacts", "0091_auto_20180905_1602")]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contacts_contact_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
