# Generated by Django 2.1.5 on 2019-01-31 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("contacts", "0092_auto_20180928_2054")]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which created this item",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contacts_contact_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
