# Generated by Django 2.1.5 on 2019-02-04 19:44

from django.db import migrations


def remove_test_contacts(apps, schema_editor):
    Contact = apps.get_model("contacts", "Contact")

    num_deleted = 0
    for test_contact in Contact.objects.filter(is_test=True):
        for test_run in test_contact.runs.order_by("id"):
            if test_run.connection:
                test_run.connection.delete()

            test_run.webhook_events.all().delete()
            test_run.logs.all.delete()
            test_run.delete()

        test_contact.webhook_results.all().delete()
        test_contact.urns.all().delete()
        test_contact.delete()
        num_deleted += 1

    if num_deleted:
        print(f"Deleted {num_deleted} test contacts")


class Migration(migrations.Migration):

    dependencies = [("contacts", "0093_auto_20190131_1116")]

    operations = [migrations.RunPython(remove_test_contacts)]
