# Generated by Django 2.1.5 on 2019-02-12 20:38

from django.db import migrations

CREATE1 = """
CREATE INDEX CONCURRENTLY contacts_contact_org_modified_id_active
ON contacts_contact (org_id, modified_on DESC, id DESC)
WHERE is_active = true;
"""

CREATE2 = """
CREATE INDEX CONCURRENTLY contacts_contact_org_modified_id_inactive
ON contacts_contact (org_id, modified_on DESC, id DESC)
WHERE is_active = false;
"""

DROP1 = "DROP INDEX CONCURRENTLY org_test_contacts;"
DROP2 = "DROP INDEX CONCURRENTLY contacts_contact_org_modified_id_where_nontest_active;"
DROP3 = "DROP INDEX CONCURRENTLY contacts_contact_org_modified_id_where_nontest_inactive;"


class Migration(migrations.Migration):

    atomic = False

    dependencies = [("contacts", "0095_no_more_is_test")]

    operations = [
        migrations.RunSQL(CREATE1),
        migrations.RunSQL(CREATE2),
        migrations.RunSQL(DROP1),
        migrations.RunSQL(DROP2),
        migrations.RunSQL(DROP3),
    ]
