# Generated by Django 2.1.5 on 2019-02-14 20:02

from django.db import migrations

CREATE_SQL = """
CREATE INDEX CONCURRENTLY contacts_contact_modified_on ON contacts_contact(modified_on);
"""

DROP_SQL = """
DROP INDEX CONCURRENTLY contacts_contact_modified_on_non_test;
"""


class Migration(migrations.Migration):

    atomic = False

    dependencies = [("contacts", "0096_indexes_without_is_test")]

    operations = [migrations.RunSQL(CREATE_SQL), migrations.RunSQL(DROP_SQL)]
