# Generated by Django 2.1.8 on 2019-05-15 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import temba.utils.json
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [("contacts", "0098_auto_20190402_1309")]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contacts_contact_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="fields",
            field=temba.utils.models.JSONField(encoder=temba.utils.json.TembaEncoder, null=True),
        ),
        migrations.AlterField(model_name="contact", name="is_blocked", field=models.BooleanField(default=False)),
        migrations.AlterField(model_name="contact", name="is_stopped", field=models.BooleanField(default=False)),
        migrations.AlterField(model_name="contact", name="is_test", field=models.BooleanField(default=False)),
        migrations.AlterField(
            model_name="contact",
            name="modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contacts_contact_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="contacts", to="orgs.Org"
            ),
        ),
    ]
