# Generated by Django 2.1.8 on 2019-06-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("contacts", "0099_auto_20190515_1550")]

    operations = [
        migrations.AlterField(
            model_name="contact", name="is_test", field=models.BooleanField(default=False, null=True)
        )
    ]
