# Generated by Django 2.1.8 on 2019-07-02 20:10
#
# This is a dummy migration which will be implemented in 5.1
#

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("contacts", "0101_initial")]

    operations = []
