# Generated by Django 2.1.8 on 2019-07-01 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("channels", "0119_initial"), ("contacts", "0101_initial")]

    operations = [
        migrations.AddField(
            model_name="contacturn",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                help_text="The preferred channel for this URN",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="channels.Channel",
            ),
        )
    ]
