# Generated by Django 2.2.4 on 2019-11-12 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("contacts", "0104_remove_contact_is_test")]

    operations = [
        migrations.AlterField(
            model_name="contacturn",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                help_text="The preferred channel for this URN",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="urns",
                to="channels.Channel",
            ),
        ),
        migrations.AlterField(
            model_name="contacturn",
            name="org",
            field=models.ForeignKey(
                help_text="The organization for this URN, can be null",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="urns",
                to="orgs.Org",
            ),
        ),
    ]
