# Generated by Django 2.2.4 on 2020-04-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("contacts", "0106_contact_is_paused")]

    operations = [migrations.AlterField(model_name="contact", name="is_paused", field=models.BooleanField(null=True))]
