# Generated by Django 2.2.10 on 2020-07-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0108_remove_contact_is_paused"),
    ]

    operations = [
        migrations.AddField(model_name="contact", name="last_seen_on", field=models.DateTimeField(null=True),),
    ]
