# Generated by Django 2.2.10 on 2020-08-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0116_update_sysgroup_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactgroup",
            name="group_type",
            field=models.CharField(
                choices=[
                    ("A", "All Contacts"),
                    ("B", "Blocked Contacts"),
                    ("S", "Stopped Contacts"),
                    ("V", "Archived Contacts"),
                    ("U", "User Defined Groups"),
                ],
                default="U",
                help_text="What type of group it is, either user defined or one of our system groups",
                max_length=1,
            ),
        ),
    ]
