# Generated by Django 2.2.10 on 2020-08-24 21:01

from django.db import migrations

GROUP_TYPE_ARCHIVED = "V"


def add_archived_sys_group(apps, schema_editor):  # pragma: no cover
    Org = apps.get_model("orgs", "Org")
    for org in Org.objects.all():
        if not org.all_groups.filter(group_type=GROUP_TYPE_ARCHIVED).exists():
            org.all_groups.create(
                name="Archived Contacts",
                group_type=GROUP_TYPE_ARCHIVED,
                created_by=org.created_by,
                modified_by=org.modified_by,
            )


def reverse(apps, schema_editor):  # pragma: no cover
    ContactGroup = apps.get_model("contacts", "ContactGroup")
    ContactGroup.all_groups.filter(group_type=GROUP_TYPE_ARCHIVED).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0117_auto_20200824_2036"),
    ]

    operations = [migrations.RunPython(add_archived_sys_group, reverse)]
