# Generated by Django 2.2.10 on 2020-10-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0125_auto_20201020_2005"),
    ]

    operations = [
        migrations.AlterField(model_name="contacturn", name="priority", field=models.IntegerField(default=1000),),
    ]
