# Generated by Django 2.2.10 on 2020-12-04 17:21

import uuid

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import temba.contacts.models
import temba.utils.json
import temba.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active, use this instead of deleting"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was originally created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was last modified",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        db_index=True,
                        default=temba.utils.models.generate_uuid,
                        help_text="The unique identifier for this object",
                        max_length=36,
                        unique=True,
                        verbose_name="Unique Identifier",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="The name of this contact",
                        max_length=128,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="The preferred language for this contact",
                        max_length=3,
                        null=True,
                        verbose_name="Language",
                    ),
                ),
                ("fields", temba.utils.models.JSONField(encoder=temba.utils.json.TembaEncoder, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "Active"), ("B", "Blocked"), ("S", "Stopped"), ("V", "Archived")],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("last_seen_on", models.DateTimeField(null=True)),
            ],
            options={"abstract": False},
            bases=(temba.utils.models.RequireUpdateFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ContactField",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active, use this instead of deleting"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was originally created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was last modified",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("label", models.CharField(max_length=36, verbose_name="Label")),
                ("key", models.CharField(max_length=36)),
                ("field_type", models.CharField(choices=[("S", "System"), ("U", "User")], default="U", max_length=1)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("T", "Text"),
                            ("N", "Number"),
                            ("D", "Date & Time"),
                            ("S", "State"),
                            ("I", "District"),
                            ("W", "Ward"),
                        ],
                        default="T",
                        max_length=1,
                        verbose_name="Field Type",
                    ),
                ),
                ("show_in_table", models.BooleanField(default=False)),
                ("priority", models.PositiveIntegerField(default=0)),
            ],
            options={"abstract": False},
            managers=[("all_fields", django.db.models.manager.Manager())],
        ),
        migrations.CreateModel(
            name="ContactGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active, use this instead of deleting"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was originally created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was last modified",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        db_index=True,
                        default=temba.utils.models.generate_uuid,
                        help_text="The unique identifier for this object",
                        max_length=36,
                        unique=True,
                        verbose_name="Unique Identifier",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="The name of this contact group", max_length=64, verbose_name="Name"),
                ),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("A", "Active"),
                            ("B", "Blocked"),
                            ("S", "Stopped"),
                            ("V", "Archived"),
                            ("U", "User Defined Groups"),
                        ],
                        default="U",
                        max_length=1,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("I", "Initializing"), ("V", "Evaluating"), ("R", "Ready")], default="I", max_length=1
                    ),
                ),
                (
                    "query",
                    models.TextField(help_text="The membership query for this group", null=True, verbose_name="Query"),
                ),
            ],
            options={"abstract": False},
            managers=[("all_groups", django.db.models.manager.Manager())],
        ),
        migrations.CreateModel(
            name="ContactGroupCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_squashed",
                    models.BooleanField(default=False, help_text="Whether this row was created by squashing"),
                ),
                ("count", models.IntegerField(default=0)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ContactImport",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active, use this instead of deleting"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was originally created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was last modified",
                    ),
                ),
                ("file", models.FileField(upload_to=temba.contacts.models.get_import_upload_path)),
                ("original_filename", models.TextField()),
                ("mappings", django.contrib.postgres.fields.jsonb.JSONField()),
                ("num_records", models.IntegerField()),
                ("started_on", models.DateTimeField(null=True)),
                (
                    "headers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255), null=True, size=None
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ContactImportBatch",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Pending"), ("O", "Processing"), ("C", "Complete"), ("F", "Failed")],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("specs", django.contrib.postgres.fields.jsonb.JSONField()),
                ("record_start", models.IntegerField()),
                ("record_end", models.IntegerField()),
                ("num_created", models.IntegerField(default=0)),
                ("num_updated", models.IntegerField(default=0)),
                ("num_errored", models.IntegerField(default=0)),
                ("errors", django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ("finished_on", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContactURN",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("identity", models.CharField(max_length=255)),
                ("scheme", models.CharField(max_length=128)),
                ("path", models.CharField(max_length=255)),
                ("display", models.CharField(max_length=255, null=True)),
                ("priority", models.IntegerField(default=1000)),
                ("auth", models.TextField(null=True)),
            ],
            options={"ordering": ("-priority", "id")},
        ),
        migrations.CreateModel(
            name="ExportContactsTask",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active, use this instead of deleting"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was originally created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was last modified",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        db_index=True,
                        default=temba.utils.models.generate_uuid,
                        help_text="The unique identifier for this object",
                        max_length=36,
                        unique=True,
                        verbose_name="Unique Identifier",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Pending"), ("O", "Processing"), ("C", "Complete"), ("F", "Failed")],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("search", models.TextField(blank=True, help_text="The search query", null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user which originally created this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contacts_exportcontactstask_creations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="The unique group to export",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exports",
                        to="contacts.ContactGroup",
                    ),
                ),
                ("group_memberships", models.ManyToManyField(to="contacts.ContactGroup")),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="The user which last modified this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contacts_exportcontactstask_modifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
