# Generated by Django 2.2.10 on 2021-04-20 13:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0129_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactimportbatch",
            name="blocked_uuids",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="contactimportbatch",
            name="num_blocked",
            field=models.IntegerField(default=0),
        ),
    ]
