# Generated by Django 2.2.10 on 2021-01-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0129_squashed"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="contacturn",
            constraint=models.CheckConstraint(
                check=models.Q(models.Q(("scheme", ""), ("path", ""), _connector="OR"), _negated=True),
                name="non_empty_scheme_and_path",
            ),
        ),
    ]
