# Generated by Django 2.2.10 on 2021-05-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0131_contactimport_group_name'),
        ('contacts', '0130_auto_20210420_1325'),
    ]

    operations = [
    ]
