# Generated by Django 2.2.20 on 2021-06-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0131_contactimport_group_name"),
        ("sql", "0002_squashed"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["org", "-modified_on"], name="contacts_contact_org_modified"),
        ),
        migrations.RunSQL("DROP INDEX contacts_contact_name;"),
    ]
