# Generated by Django 2.2.10 on 2021-09-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0131_auto_20210924_1402"),
        ("contacts", "0131_contactimport_num_duplicates"),
    ]

    operations = []
