# Generated by Django 2.2.10 on 2021-10-05 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0132_merge_20210930_1614"),
        ("contacts", "0132_auto_20210924_0448"),
    ]

    operations = []
