# Generated by Django 2.2.24 on 2021-10-13 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0133_merge_20211005_0212"),
        ("contacts", "0132_merge_20210517_1335"),
    ]

    operations = []
