# Generated by Django 2.2.20 on 2021-07-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0135_auto_20210712_1845"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactgroupcount",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="contactgroupcount",
            name="is_squashed",
            field=models.BooleanField(default=False),
        ),
    ]
