# Generated by Django 2.2.20 on 2021-07-14 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0135_auto_20210712_1845"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactgroup",
            options={"verbose_name": "Group", "verbose_name_plural": "Groups"},
        ),
    ]
