# Generated by Django 2.2.27 on 2022-02-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0134_merge_20211013_2232"),
        ("contacts", "0138_auto_20210720_2022"),
    ]

    operations = []
