# Generated by Django 2.2.20 on 2021-07-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0138_auto_20210720_2022"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="ticket_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="ticket_count",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
