# Generated by Django 3.2.6 on 2021-08-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0141_populate_ticket_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactimport",
            name="mappings",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="contactimportbatch",
            name="errors",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="contactimportbatch",
            name="specs",
            field=models.JSONField(),
        ),
    ]
