# Generated by Django 4.0.2 on 2022-02-02 15:59

import django.db.models.expressions
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0146_unique_group_names"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="contactgroup",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("org"),
                django.db.models.functions.text.Lower("name"),
                name="unique_contact_group_names",
            ),
        ),
    ]
