# Generated by Django 4.0.2 on 2022-02-07 15:41

from django.db import migrations


def remove_inactive_from_groups(apps, schema_editor):  # pragma: no cover
    ContactGroup = apps.get_model("contacts", "ContactGroup")

    bad_memberships = ContactGroup.contacts.through.objects.exclude(contact__status="A").filter(
        contactgroup__group_type="U"
    )
    num_deleted = 0

    while True:
        batch = list(bad_memberships[:500])
        if not batch:
            break

        ContactGroup.contacts.through.objects.filter(id__in=[m.id for m in batch]).delete()
        num_deleted += len(batch)

        print(f"Deleted {num_deleted} bad group memberships for inactive contacts")


def reverse(apps, schema_editor):  # pragma: no cover
    pass


def apply_manual():  # pragma: no cover
    from django.apps import apps

    remove_inactive_from_groups(apps, schema_editor=None)


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0147_contactgroup_unique_contact_group_names"),
    ]

    operations = [migrations.RunPython(remove_inactive_from_groups, reverse)]
