# Generated by Django 4.0.3 on 2022-03-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0153_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactgroup",
            name="is_system",
            field=models.BooleanField(null=True),
        ),
    ]
