# Generated by Django 4.0.3 on 2022-03-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0155_populate_is_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactgroup",
            name="group_type",
            field=models.CharField(
                choices=[
                    ("A", "Active"),
                    ("B", "Blocked"),
                    ("S", "Stopped"),
                    ("V", "Archived"),
                    ("M", "Manual"),
                    ("Q", "Smart"),
                ],
                default="M",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="contactgroup",
            name="is_system",
            field=models.BooleanField(),
        ),
    ]
