# Generated by Django 4.0.3 on 2022-03-28 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0094_alter_org_parent"),
        ("contacts", "0157_update_group_type"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="contactgroup",
            managers=[],
        ),
        migrations.AlterField(
            model_name="contactgroup",
            name="contacts",
            field=models.ManyToManyField(related_name="groups", to="contacts.contact"),
        ),
        migrations.AlterField(
            model_name="contactgroup",
            name="org",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="groups", to="orgs.org"),
        ),
    ]
