# Generated by Django 4.0.3 on 2022-04-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0159_open_tickets_sys_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactfield",
            name="is_system",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="contactfield",
            name="name",
            field=models.CharField(max_length=36, null=True),
        ),
    ]
