# Generated by Django 4.0.3 on 2022-04-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0161_populate_field_name_and_is_system"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactfield",
            name="field_type",
        ),
        migrations.RemoveField(
            model_name="contactfield",
            name="label",
        ),
    ]
