# Generated by Django 4.0.3 on 2022-04-18 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0162_alter_contactfield_field_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactfield",
            name="field_type",
        ),
        migrations.RemoveField(
            model_name="contactfield",
            name="label",
        ),
    ]
