# Generated by Django 4.0.3 on 2022-04-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0164_remove_contactfield_field_type_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="contactfield",
            managers=[],
        ),
    ]
