# Generated by Django 4.0.4 on 2022-04-28 21:46

from django.db import migrations
from django.db.models import Q


def clean_name(original: str) -> str:  # pragma: no cover
    return original.strip().replace('"', "'").replace("\\", "/").replace("\0", "")


def fix_invalid_group_names(apps, schema_editor):  # pragma: no cover
    ContactGroup = apps.get_model("contacts", "ContactGroup")

    for group in ContactGroup.objects.filter(Q(name__icontains='"') | Q(name__icontains="\\")):
        old_name, new_name = group.name, clean_name(group.name)

        group.name = new_name
        group.save(update_fields=("name",))

        print(f" > group {group.uuid} '{old_name}' renamed to '{new_name}'")


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0165_alter_contactfield_managers"),
    ]

    operations = [migrations.RunPython(fix_invalid_group_names, reverse)]
