# Generated by Django 4.0.6 on 2022-08-03 16:53

from django.db import migrations, models

import temba.utils.uuid


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0167_alter_contactgroup_is_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportcontactstask",
            name="uuid",
            field=models.UUIDField(default=temba.utils.uuid.uuid4, unique=True),
        ),
    ]
