# Generated by Django 4.0.8 on 2023-01-18 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contacts", "0171_squashed"),
        ("sql", "0005_squashed"),
    ]

    operations = [
        migrations.RunSQL("DROP INDEX IF EXISTS contact_fields_keys_idx"),
        migrations.AlterField(
            model_name="contact",
            name="created_by",
            field=models.ForeignKey(
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                related_name="+",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="modified_by",
            field=models.ForeignKey(
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                related_name="+",
            ),
        ),
    ]
