# Generated by Django 4.1.9 on 2023-06-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0172_remove_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactfield",
            name="agent_access",
            field=models.CharField(choices=[("N", "Hidden"), ("V", "View"), ("E", "Edit")], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="contactfield",
            name="agent_access",
            field=models.CharField(
                choices=[("N", "Hidden"), ("V", "View"), ("E", "Edit")], default="V", max_length=1, null=True
            ),
        ),
    ]
