# Generated by Django 4.1.9 on 2023-06-08 21:22

from django.db import migrations

ACCESS_VIEW = "V"


def backfill_field_access(apps, schema_editor):  # pragma: no cover
    ContactField = apps.get_model("contacts", "ContactField")
    num_updated = 0

    while True:
        id_batch = list(ContactField.objects.filter(agent_access=None).values_list("id", flat=True)[:1000])
        if not id_batch:
            break

        ContactField.objects.filter(id__in=id_batch).update(agent_access=ACCESS_VIEW)
        num_updated += len(id_batch)

    if num_updated:
        print(f"Updated {num_updated} contact fields without default agent access")


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):
    atomic = False

    dependencies = [("contacts", "0173_contactfield_agent_access")]

    operations = [migrations.RunPython(backfill_field_access, reverse)]
