# Generated by Django 4.1.9 on 2023-06-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0174_backfill_field_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactfield",
            name="agent_access",
            field=models.CharField(choices=[("N", "Hidden"), ("V", "View"), ("E", "Edit")], default="V", max_length=1),
        ),
    ]
