# Generated by Django 4.2.3 on 2023-09-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0176_remove_contacturn_non_empty_scheme_and_path_and_more"),
    ]

    operations = [
        migrations.AddField(model_name="contacturn", name="auth_tokens", field=models.JSONField(null=True)),
    ]
