# Generated by Django 4.2.3 on 2023-09-06 20:11

from django.db import migrations


def populate_urn_auth_tokens(apps, schema_editor):  # pragma: no cover
    ContactURN = apps.get_model("contacts", "ContactURN")

    num_updated = 0
    for urn in ContactURN.objects.exclude(auth=None):
        urn.auth_tokens = {"default": urn.auth}
        urn.save(update_fields=("auth_tokens",))
        num_updated += 1

    if num_updated:
        print(f"Updated {num_updated} urns with auth values")


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):
    dependencies = [("contacts", "0177_contacturn_auth_tokens")]

    operations = [migrations.RunPython(populate_urn_auth_tokens, reverse)]
