# Generated by Django 4.2.3 on 2023-09-12 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0178_populate_urn_auth_tokens"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contacturn",
            name="auth",
        ),
    ]
