# Generated by Django 4.2.8 on 2023-12-12 20:08

import django.db.models.functions.text
from django.db import migrations, models

SQL = """
DROP INDEX contacts_contact_modified_on;
DROP INDEX contacts_contact_org_modified_id_active;
DROP INDEX contacts_contact_org_modified_id_inactive;
DROP INDEX contacts_contacturn_org_scheme_display;
DROP INDEX contacts_contacturn_path;
"""


class Migration(migrations.Migration):
    """
    Migration just moves indexes into Django and renames them, and is equivalent to...

    ALTER INDEX contacts_contact_modified_on RENAME TO contacts_modified;
    ALTER INDEX contacts_contact_org_modified_id_active RENAME TO contacts_by_org;
    ALTER INDEX contacts_contact_org_modified_id_inactive RENAME TO contacts_by_org_deleted;
    ALTER INDEX contacts_contacturn_path RENAME TO contacturns_by_path;
    """

    dependencies = [("contacts", "0181_index_cleanup")]

    operations = [
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                condition=models.Q(("is_active", True)), fields=["org", "-modified_on", "-id"], name="contacts_by_org"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                condition=models.Q(("is_active", False)),
                fields=["org", "-modified_on", "-id"],
                name="contacts_by_org_deleted",
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["modified_on"], name="contacts_modified"),
        ),
        migrations.AddIndex(
            model_name="contacturn",
            index=models.Index(
                models.F("org"),
                django.db.models.functions.text.Upper("path"),
                models.F("contact"),
                name="contacturns_by_path",
            ),
        ),
        migrations.RunSQL(SQL),
    ]
