# Generated by Django 4.2.8 on 2024-01-05 15:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import temba.contacts.models
import temba.orgs.models
import temba.utils.fields
import temba.utils.json
import temba.utils.models.base
import temba.utils.models.fields
import temba.utils.uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this item is active, use this instead of deleting",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was originally created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was last modified",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        db_index=True,
                        default=temba.utils.models.base.generate_uuid,
                        help_text="The unique identifier for this object",
                        max_length=36,
                        unique=True,
                        verbose_name="Unique Identifier",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=128, null=True, verbose_name="Name"),
                ),
                (
                    "language",
                    models.CharField(blank=True, max_length=3, null=True, verbose_name="Language"),
                ),
                (
                    "fields",
                    temba.utils.models.fields.JSONField(
                        decoder=temba.utils.json.TembaDecoder,
                        encoder=temba.utils.json.TembaEncoder,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Active"),
                            ("B", "Blocked"),
                            ("S", "Stopped"),
                            ("V", "Archived"),
                        ],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("ticket_count", models.IntegerField(default=0)),
                ("last_seen_on", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContactField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this item is active, use this instead of deleting",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was originally created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was last modified",
                    ),
                ),
                ("uuid", models.UUIDField(default=temba.utils.uuid.uuid4, unique=True)),
                ("key", models.CharField(max_length=36)),
                ("name", models.CharField(max_length=36)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("T", "Text"),
                            ("N", "Number"),
                            ("D", "Date & Time"),
                            ("S", "State"),
                            ("I", "District"),
                            ("W", "Ward"),
                        ],
                        default="T",
                        max_length=1,
                    ),
                ),
                ("is_system", models.BooleanField()),
                ("show_in_table", models.BooleanField(default=False)),
                ("priority", models.PositiveIntegerField(default=0)),
                (
                    "agent_access",
                    models.CharField(
                        choices=[("N", "Hidden"), ("V", "View"), ("E", "Edit")],
                        default="V",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, temba.orgs.models.DependencyMixin),
        ),
        migrations.CreateModel(
            name="ContactGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this item is active, use this instead of deleting",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was originally created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was last modified",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        db_index=True,
                        default=temba.utils.models.base.generate_uuid,
                        help_text="The unique identifier for this object",
                        max_length=36,
                        unique=True,
                        verbose_name="Unique Identifier",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=64, validators=[temba.utils.fields.NameValidator(64)]),
                ),
                ("is_system", models.BooleanField(default=False)),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("A", "Active"),
                            ("B", "Blocked"),
                            ("S", "Stopped"),
                            ("V", "Archived"),
                            ("M", "Manual"),
                            ("Q", "Smart"),
                        ],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("I", "Initializing"),
                            ("V", "Evaluating"),
                            ("R", "Ready"),
                        ],
                        default="I",
                        max_length=1,
                    ),
                ),
                ("query", models.TextField(null=True)),
            ],
            options={
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
            },
            bases=(models.Model, temba.orgs.models.DependencyMixin),
        ),
        migrations.CreateModel(
            name="ContactGroupCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
                ),
                ("is_squashed", models.BooleanField(default=False)),
                ("count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ContactImport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this item is active, use this instead of deleting",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was originally created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was last modified",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=temba.contacts.models.get_import_upload_path),
                ),
                ("original_filename", models.TextField()),
                ("mappings", models.JSONField()),
                ("num_records", models.IntegerField()),
                ("group_name", models.CharField(max_length=64, null=True)),
                ("started_on", models.DateTimeField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("O", "Processing"),
                            ("C", "Complete"),
                            ("F", "Failed"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("finished_on", models.DateTimeField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactImportBatch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("O", "Processing"),
                            ("C", "Complete"),
                            ("F", "Failed"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("specs", models.JSONField()),
                ("record_start", models.IntegerField()),
                ("record_end", models.IntegerField()),
                ("num_created", models.IntegerField(default=0)),
                ("num_updated", models.IntegerField(default=0)),
                ("num_errored", models.IntegerField(default=0)),
                ("errors", models.JSONField(default=list)),
                ("finished_on", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContactURN",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identity", models.CharField(max_length=255)),
                ("scheme", models.CharField(max_length=128)),
                ("path", models.CharField(max_length=255)),
                ("display", models.CharField(max_length=255, null=True)),
                ("priority", models.IntegerField(default=1000)),
                ("auth_tokens", models.JSONField(null=True)),
            ],
            options={
                "ordering": ("-priority", "id"),
            },
        ),
        migrations.CreateModel(
            name="ExportContactsTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this item is active, use this instead of deleting",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was originally created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was last modified",
                    ),
                ),
                ("uuid", models.UUIDField(default=temba.utils.uuid.uuid4, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("O", "Processing"),
                            ("C", "Complete"),
                            ("F", "Failed"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                (
                    "search",
                    models.TextField(blank=True, help_text="The search query", null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user which originally created this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="The unique group to export",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exports",
                        to="contacts.contactgroup",
                    ),
                ),
                (
                    "group_memberships",
                    models.ManyToManyField(to="contacts.contactgroup"),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="The user which last modified this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_modifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
