# Generated by Django 5.0.4 on 2024-05-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0187_delete_exportcontactstask"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactfield",
            name="is_proxy",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="contactfield",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
    ]
