# Generated by Django 5.0.6 on 2024-07-10 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0189_backfill_proxy_fields"),
        ("flows", "0334_remove_flowrun_submitted_by"),
        ("orgs", "0144_alter_usersettings_email_verification_secret"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.CheckConstraint(
                check=models.Q(("status__in", ("A", "B", "S", "V"))), name="contact_status_valid"
            ),
        ),
    ]
