# Generated by Django 5.0.7 on 2024-07-29 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0190_contact_contact_status_valid"),
        ("orgs", "0144_alter_usersettings_email_verification_secret"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactNote",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(max_length=10000)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="notes", to="contacts.contact"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="contact_notes", to="orgs.user"
                    ),
                ),
            ],
        ),
    ]
