# Generated by Django 5.1.2 on 2024-12-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0193_fix_status_group_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactgroupcount",
            name="count",
            field=models.IntegerField(),
        ),
    ]
