# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-15 20:40
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("policies", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="consent",
            name="policy",
            field=models.ForeignKey(
                help_text="The policy the user is consenting to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="policies",
                to="policies.Policy",
            ),
        ),
        migrations.AlterField(
            model_name="consent",
            name="user",
            field=models.ForeignKey(
                help_text="The user consenting to this policy",
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="policies_policy_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="policies_policy_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
