# Generated by Django 2.2.10 on 2020-09-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="policy_type",
            field=models.CharField(
                choices=[
                    ("privacy", "Privacy Policy"),
                    ("content", "Content Guidelines"),
                    ("tos", "Terms of Service"),
                    ("cookie", "Cookie Policy"),
                ],
                help_text="Choose the type of policy",
                max_length=16,
            ),
        ),
    ]
