# Generated by Django 2.2.4 on 2019-10-14 17:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("orgs", "0058_auto_20190723_2129"), ("classifiers", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="HTTPLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "log_type",
                    models.CharField(
                        choices=[("intents_synced", "Intents Synced"), ("classifier_called", "Classifier Called")],
                        max_length=32,
                    ),
                ),
                ("url", models.URLField()),
                ("request", models.TextField()),
                ("response", models.TextField(null=True)),
                ("is_error", models.BooleanField()),
                ("request_time", models.IntegerField()),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "classifier",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="http_logs",
                        to="classifiers.Classifier",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="http_logs", to="orgs.Org"
                    ),
                ),
            ],
            options={"index_together": {("classifier", "created_on")}},
        )
    ]
