# Generated by Django 2.2.4 on 2019-11-22 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("channels", "0121_auto_20191112_1938"), ("request_logs", "0002_auto_20191016_2238")]

    operations = [
        migrations.AddField(
            model_name="httplog",
            name="channel",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="http_logs", to="channels.Channel"
            ),
        ),
        migrations.AlterField(
            model_name="httplog",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("intents_synced", "Intents Synced"),
                    ("classifier_called", "Classifier Called"),
                    ("airtime_transferred", "Airtime Transferred"),
                    ("whatsapp_templates_synced", "Whatsapp Templates Synced"),
                ],
                max_length=32,
            ),
        ),
    ]
