# Generated by Django 2.2.4 on 2020-03-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("request_logs", "0004_auto_20191128_2125")]

    operations = [
        migrations.AlterField(
            model_name="httplog",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("intents_synced", "Intents Synced"),
                    ("classifier_called", "Classifier Called"),
                    ("airtime_transferred", "Airtime Transferred"),
                    ("whatsapp_templates_synced", "WhatsApp Templates Synced"),
                    ("whatsapp_tokens_synced", "WhatsApp Tokens Synced"),
                    ("whatsapp_contacts_refreshed", "WhatsApp Contacts Refreshed"),
                ],
                max_length=32,
            ),
        )
    ]
