# Generated by Django 2.2.4 on 2020-04-23 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tickets", "0001_initial"), ("request_logs", "0005_auto_20200304_2055")]

    operations = [
        migrations.AddField(
            model_name="httplog",
            name="ticketer",
            field=models.ForeignKey(
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="http_logs",
                to="tickets.Ticketer",
            ),
        ),
        migrations.AlterField(
            model_name="httplog",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("intents_synced", "Intents Synced"),
                    ("classifier_called", "Classifier Called"),
                    ("ticketer_called", "Ticketing Service Called"),
                    ("airtime_transferred", "Airtime Transferred"),
                    ("whatsapp_templates_synced", "WhatsApp Templates Synced"),
                    ("whatsapp_tokens_synced", "WhatsApp Tokens Synced"),
                    ("whatsapp_contacts_refreshed", "WhatsApp Contacts Refreshed"),
                ],
                max_length=32,
            ),
        ),
    ]
