# Generated by Django 2.2.20 on 2021-06-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request_logs", "0008_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="httplog",
            name="url",
            field=models.URLField(max_length=2048),
        ),
    ]
