# Generated by Django 2.2.27 on 2022-02-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request_logs", "0009_auto_20210903_1133"),
        ("request_logs", "0009_resize_url_field"),
    ]

    operations = []
