# Generated by Django 3.2.7 on 2021-09-21 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0259_auto_20210825_1438"),
        ("request_logs", "0009_resize_url_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="httplog",
            name="flow",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="http_logs", to="flows.flow"
            ),
        ),
        migrations.AddField(
            model_name="httplog",
            name="status_code",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="httplog",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("webhook_called", "Webhook Called"),
                    ("intents_synced", "Intents Synced"),
                    ("classifier_called", "Classifier Called"),
                    ("ticketer_called", "Ticketing Service Called"),
                    ("airtime_transferred", "Airtime Transferred"),
                    ("whatsapp_templates_synced", "WhatsApp Templates Synced"),
                    ("whatsapp_tokens_synced", "WhatsApp Tokens Synced"),
                    ("whatsapp_contacts_refreshed", "WhatsApp Contacts Refreshed"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="httplog",
            index=models.Index(
                condition=models.Q(("flow__isnull", False)),
                fields=["org", "-created_on"],
                name="httplog_org_flows_only",
            ),
        ),
    ]
