# Generated by Django 3.2.7 on 2021-09-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request_logs", "0010_auto_20210921_1508"),
    ]

    operations = [
        migrations.AddField(
            model_name="httplog",
            name="num_retries",
            field=models.IntegerField(null=True),
        ),
    ]
