# Generated by Django 3.2.7 on 2021-09-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request_logs", "0012_alter_httplog_log_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="httplog",
            name="num_retries",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="httplog",
            name="status_code",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
