# Generated by Django 4.2.8 on 2024-01-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request_logs", "0015_squashed"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="httplog",
            name="request_log_tickete_abc69b_idx",
        ),
        migrations.RemoveField(
            model_name="httplog",
            name="ticketer",
        ),
        migrations.AlterField(
            model_name="httplog",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("webhook_called", "Webhook Called"),
                    ("intents_synced", "Intents Synced"),
                    ("classifier_called", "Classifier Called"),
                    ("airtime_transferred", "Airtime Transferred"),
                    ("whatsapp_templates_synced", "WhatsApp Templates Synced"),
                    ("whatsapp_tokens_synced", "WhatsApp Tokens Synced"),
                    ("whatsapp_contacts_refreshed", "WhatsApp Contacts Refreshed"),
                    ("whataspp_check_health", "WhatsApp Health Check"),
                ],
                max_length=32,
            ),
        ),
    ]
