# Generated by Django 2.2.10 on 2021-07-26 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import temba.utils.json
import temba.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orgs", "0074_auto_20210630_1156"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active, use this instead of deleting"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was originally created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was last modified",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="The name title or this report", max_length=64, verbose_name="Title"),
                ),
                (
                    "description",
                    models.TextField(help_text="The full description for the report", verbose_name="Description"),
                ),
                (
                    "config",
                    temba.utils.models.JSONField(
                        encoder=temba.utils.json.TembaEncoder,
                        help_text="The JSON encoded configurations for this report",
                        null=True,
                        verbose_name="Configuration",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, help_text="Whether this report is currently published"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user which originally created this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports_report_creations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="The user which last modified this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports_report_modifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("org", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="orgs.Org")),
            ],
            options={
                "unique_together": {("org", "title")},
            },
        ),
    ]
