# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 22:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0029_reset_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='When this item was originally created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='When this item was last modified')),
                ('title', models.CharField(help_text='The name title or this report', max_length=64, verbose_name='Title')),
                ('description', models.TextField(help_text='The full description for the report', verbose_name='Description')),
                ('config', models.TextField(help_text='The JSON encoded configurations for this report', null=True, verbose_name='Configuration')),
                ('is_published', models.BooleanField(default=False, help_text='Whether this report is currently published')),
                ('created_by', models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.CASCADE, related_name='reports_report_creations', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.CASCADE, related_name='reports_report_modifications', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Org')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set([('org', 'title')]),
        ),
    ]
