# Generated by Django 2.2.10 on 2021-08-05 16:00

from django.db import migrations, models
import django.db.models.deletion
import temba.utils.json
import temba.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0245_merge_20201214_1542"),
        ("reports", "0002_auto_20210729_2212"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowResultsAggregation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", temba.utils.models.JSONField(default=dict, encoder=temba.utils.json.TembaEncoder)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "flow",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="aggregated_results", to="flows.Flow"
                    ),
                ),
            ],
        ),
    ]
