# Generated by Django 2.2.10 on 2021-08-10 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0074_auto_20210630_1156"),
        ("flows", "0245_merge_20201214_1542"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0003_flowresultsaggregation"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FlowResultsAggregation",
            new_name="CollectedFlowResultsData",
        ),
        migrations.CreateModel(
            name="DataCollectionProcess",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "start_type",
                    models.CharField(choices=[("A", "Automatically"), ("M", "Manually")], default="A", max_length=1),
                ),
                ("started_on", models.DateTimeField(auto_now_add=True)),
                ("completed_on", models.DateTimeField(blank=True, null=True)),
                ("flows_total", models.PositiveIntegerField(default=0)),
                ("flows_skipped", models.PositiveIntegerField(default=0)),
                ("flows_processed", models.PositiveIntegerField(default=0)),
                (
                    "related_org",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="orgs.Org"),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
