# Generated by Django 2.2.10 on 2021-08-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_auto_20210812_1352"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collectedflowresultsdata",
            options={"ordering": ["-last_updated", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="datacollectionprocess",
            options={"ordering": ["-started_on", "-id"]},
        ),
        migrations.AddField(
            model_name="datacollectionprocess",
            name="flows_failed",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
