# Generated by Django 2.2.4 on 2020-04-16 17:35

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tickets", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="ticket", name="subject", field=models.TextField(default=""), preserve_default=False
        ),
        migrations.AddField(model_name="ticketingservice", name="uuid", field=models.UUIDField(default=uuid.uuid4)),
        migrations.AlterField(
            model_name="ticketingservice", name="service_type", field=models.CharField(max_length=16)
        ),
    ]
