# Generated by Django 2.2.4 on 2020-04-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tickets", "0002_auto_20200416_1735")]

    operations = [
        migrations.AddField(
            model_name="ticketingservice",
            name="name",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        )
    ]
