# Generated by Django 2.2.4 on 2020-06-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tickets", "0002_auto_20200515_2216")]

    operations = [
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["ticketer", "external_id"], name="tickets_ticketer_external_id"),
        )
    ]
