# Generated by Django 2.2.20 on 2021-06-14 18:37

from django.db import migrations

TYPE_OPENED = "O"
TYPE_CLOSED = "C"


def backfill_ticket_events(apps, schema_editor):  # pragma: no cover
    Ticket = apps.get_model("tickets", "Ticket")

    for ticket in Ticket.objects.all():
        if not ticket.events.filter(event_type=TYPE_OPENED).exists():
            ticket.events.create(org_id=ticket.org_id, event_type=TYPE_OPENED, created_on=ticket.opened_on)

        if ticket.closed_on and not ticket.events.filter(event_type=TYPE_CLOSED).exists():
            ticket.events.create(org_id=ticket.org_id, event_type=TYPE_CLOSED, created_on=ticket.closed_on)


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0006_auto_20210609_1913"),
    ]

    operations = [migrations.RunPython(backfill_ticket_events, reverse)]
