# Generated by Django 2.2.20 on 2021-06-17 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0009_backfill_event_contact"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ticket",
            name="tickets_org_open",
        ),
        migrations.RemoveIndex(
            model_name="ticket",
            name="tickets_org_closed",
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                condition=models.Q(status="O"), fields=["org", "-last_activity_on", "-id"], name="tickets_org_open"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                condition=models.Q(status="C"), fields=["org", "-last_activity_on", "-id"], name="tickets_org_closed"
            ),
        ),
        migrations.AlterField(
            model_name="ticketevent",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="ticket_events", to="contacts.Contact"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketevent",
            index=models.Index(fields=["contact", "created_on"], name="ticketevents_contact_created"),
        ),
    ]
