# Generated by Django 2.2.20 on 2021-07-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0014_populate_ticket_counts"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ticketcount",
            index=models.Index(
                condition=models.Q(is_squashed=False),
                fields=["org", "assignee", "status"],
                name="ticket_count_unsquashed",
            ),
        ),
    ]
