# Generated by Django 3.2.6 on 2021-08-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0017_update_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="config",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="ticketer",
            name="config",
            field=models.JSONField(),
        ),
    ]
