# Generated by Django 3.2.6 on 2021-08-25 21:04

from django.db import migrations


def create_default_topics(apps, schema_editor):  # pragma: no cover
    Org = apps.get_model("orgs", "Org")

    for org in Org.objects.all():
        if not org.topics.filter(is_default=True).exists():
            org.topics.create(name="General", is_default=True, created_by=org.created_by, modified_by=org.modified_by)


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0019_auto_20210818_1603"),
    ]

    operations = [migrations.RunPython(create_default_topics, reverse)]
