# Generated by Django 3.2.6 on 2021-08-25 22:48

from django.db import migrations


def assign_default_topic(apps, schema_editor):  # pragma: no cover
    Org = apps.get_model("orgs", "Org")

    for org in Org.objects.exclude(tickets=None):
        default_topic = org.topics.get(is_default=True)
        org.tickets.filter(topic=None).update(topic=default_topic)


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0020_create_default_topics"),
    ]

    operations = [migrations.RunPython(assign_default_topic, reverse)]
