# Generated by Django 3.2.6 on 2021-08-26 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0021_assign_default_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketevent",
            name="topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ticket_events",
                to="tickets.topic",
            ),
        ),
        migrations.AlterField(
            model_name="ticketevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("O", "Opened"),
                    ("A", "Assigned"),
                    ("N", "Note Added"),
                    ("T", "Topic Changed"),
                    ("C", "Closed"),
                    ("R", "Reopened"),
                ],
                max_length=1,
            ),
        ),
    ]
