# Generated by Django 3.2.6 on 2021-08-26 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0021_assign_default_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="tickets", to="tickets.topic"
            ),
        ),
    ]
