# Generated by Django 3.2.7 on 2021-09-15 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0023_auto_20210910_2118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="tickets", to="tickets.topic"
            ),
        ),
    ]
