# Generated by Django 3.2.7 on 2021-10-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0024_alter_ticket_topic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="subject",
        ),
    ]
