# Generated by Django 4.0.4 on 2022-05-03 18:00

from django.db import migrations, models

import temba.utils.fields
import temba.utils.uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0028_alter_topic_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketer",
            name="name",
            field=models.CharField(max_length=64, validators=[temba.utils.fields.NameValidator(64)]),
        ),
        migrations.AlterField(
            model_name="ticketer",
            name="uuid",
            field=models.UUIDField(default=temba.utils.uuid.uuid4, unique=True),
        ),
    ]
