# Generated by Django 4.0.4 on 2022-05-05 14:16

import django.db.models.expressions
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0029_alter_ticketer_name_alter_ticketer_uuid"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="topic",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("org"),
                django.db.models.functions.text.Lower("name"),
                name="unique_topic_names",
            ),
        ),
    ]
