# Generated by Django 4.0.4 on 2022-05-10 14:48

from django.db import migrations


def populate_is_system(apps, schema_editor):  # pragma: no cover
    Ticketer = apps.get_model("tickets", "Ticketer")
    Topic = apps.get_model("tickets", "Topic")

    Ticketer.objects.filter(ticketer_type="internal").update(is_system=True)
    Topic.objects.filter(is_default=True).update(is_system=True)


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0032_team_is_system_ticketer_is_system_topic_is_system"),
    ]

    operations = [migrations.RunPython(populate_is_system)]
