# Generated by Django 4.0.4 on 2022-05-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0034_backfill_ticket_daily_counts"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="replied_on",
            field=models.DateTimeField(null=True),
        ),
    ]
