# Generated by Django 4.0.6 on 2022-07-18 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0101_remove_org_administrators_remove_org_agents_and_more"),
        ("flows", "0291_flowrun_flows_run_active_or_waiting_has_session"),
        ("tickets", "0038_remove_ticket_tickets_ticketer_external_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="opened_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="opened_tickets", to="orgs.user"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="opened_in",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="opened_tickets", to="flows.flow"
            ),
        ),
    ]
