# Generated by Django 4.0.7 on 2022-10-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0169_alter_contact_language_alter_contact_name"),
        ("tickets", "0042_exportticketstask_with_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportticketstask",
            name="with_groups",
            field=models.ManyToManyField(related_name="%(class)s_exports", to="contacts.contactgroup"),
        ),
    ]
