# Generated by Django 4.0.9 on 2023-02-23 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0119_squashed"),
        ("contacts", "0172_remove_indexes"),
        ("tickets", "0045_fix_api_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="contact",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="contacts.contact",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="org",
            field=models.ForeignKey(
                db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name="tickets", to="orgs.org"
            ),
        ),
    ]
