# Generated by Django 4.1.7 on 2023-04-20 17:17

from django.db import migrations, models

SQL = """
----------------------------------------------------------------------
-- Inserts a new ticketcount row with the given values
----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION temba_insert_ticketcount(_org_id INTEGER, _assignee_id INTEGER, status CHAR(1), _count INT) RETURNS VOID AS $$
DECLARE
    scope TEXT;
BEGIN
    scope := format('assignee:%s', coalesce(_assignee_id, 0));

    INSERT INTO tickets_ticketcount("org_id", "scope", "assignee_id", "status", "count", "is_squashed")
    VALUES(_org_id, scope, _assignee_id, status, _count, FALSE);
END;
$$ LANGUAGE plpgsql;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0046_alter_ticket_contact_alter_ticket_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcount",
            name="scope",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.RunSQL(SQL),
    ]
