# Generated by Django 4.1.7 on 2023-04-20 19:01

from django.db import migrations


def backfill_ticketcount_scope(apps, schema_editor):  # pragma: no cover
    TicketCount = apps.get_model("tickets", "TicketCount")

    for tc in TicketCount.objects.filter(scope=None):
        tc.scope = f"assignee:{tc.assignee_id or 0}"
        tc.save(update_fields=("scope",))


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0047_ticketcount_scope"),
    ]

    operations = [migrations.RunPython(backfill_ticketcount_scope, reverse)]
