# Generated by Django 4.1.7 on 2023-04-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0048_backfill_ticketcount_scope"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ticketcount",
            name="tickets_tic_org_id_6e466a_idx",
        ),
        migrations.RemoveIndex(
            model_name="ticketcount",
            name="ticket_count_unsquashed",
        ),
        migrations.AlterField(
            model_name="ticketcount",
            name="scope",
            field=models.CharField(max_length=32),
        ),
        migrations.AddIndex(
            model_name="ticketcount",
            index=models.Index(fields=["org", "scope", "status"], name="tickets_tic_org_id_415b13_idx"),
        ),
        migrations.AddIndex(
            model_name="ticketcount",
            index=models.Index(
                condition=models.Q(("is_squashed", False)),
                fields=["org", "scope", "status"],
                name="ticket_count_unsquashed",
            ),
        ),
    ]
