# Generated by Django 4.1.7 on 2023-04-20 20:54

from django.db import migrations

SQL = """
----------------------------------------------------------------------
-- Inserts a new ticketcount row with the given values
----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION temba_insert_ticketcount(_org_id INTEGER, _assignee_id INTEGER, status CHAR(1), _count INT) RETURNS VOID AS $$
DECLARE
    scope TEXT;
BEGIN
    scope := format('assignee:%s', coalesce(_assignee_id, 0));

    INSERT INTO tickets_ticketcount("org_id", "scope", "status", "count", "is_squashed") VALUES(_org_id, scope, status, _count, FALSE);
END;
$$ LANGUAGE plpgsql;
"""


class Migration(migrations.Migration):
    dependencies = [("tickets", "0049_remove_ticketcount_tickets_tic_org_id_6e466a_idx_and_more")]

    operations = [migrations.RunSQL(SQL)]
