# Generated by Django 4.2.3 on 2023-10-13 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("tickets", "0052_backfill_ticketcount_by_topic")]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="ticketer",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="tickets", to="tickets.ticketer"
            ),
        ),
    ]
