# Generated by Django 4.2.8 on 2024-01-02 19:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("tickets", "0053_alter_ticket_ticketer")]

    operations = [
        migrations.RemoveIndex(model_name="ticket", name="tickets_ticketer_external_id"),
    ]
