# Generated by Django 4.2.8 on 2024-01-03 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0054_remove_ticket_tickets_ticketer_external_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="config",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="external_id",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="ticketer",
        ),
    ]
