# Generated by Django 4.2.8 on 2024-01-03 20:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0327_remove_flow_ticketer_dependencies"),
        ("request_logs", "0016_remove_httplog_request_log_tickete_abc69b_idx_and_more"),
        ("tickets", "0055_remove_ticket_config_remove_ticket_external_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ticketer",
        ),
    ]
