# Generated by Django 5.0.7 on 2024-08-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0060_delete_exportticketstask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="body",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="ticketevent",
            name="note",
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
