# Generated by Django 5.0.8 on 2024-08-08 14:58

from django.db import migrations


def move_body_to_open_note(apps, schema_editor):
    Ticket = apps.get_model("tickets", "Ticket")

    num_updated = 0

    while True:
        batch = list(Ticket.objects.exclude(body=None).exclude(body="")[:1000])
        if not batch:
            break

        for ticket in batch:
            ticket.events.filter(event_type="O").update(note=ticket.body)

        Ticket.objects.filter(id__in=[t.id for t in batch]).update(body=None)
        num_updated += len(batch)

        print(f" > Updated {num_updated} tickets")


class Migration(migrations.Migration):

    dependencies = [("tickets", "0061_alter_ticket_body_alter_ticketevent_note")]

    operations = [migrations.RunPython(move_body_to_open_note, migrations.RunPython.noop)]
