# Generated by Django 5.1.2 on 2024-10-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tickets", "0064_shortcut")]

    operations = [
        migrations.AddField(model_name="team", name="all_topics", field=models.BooleanField(default=False)),
    ]
