# Generated by Django 5.1.2 on 2024-10-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0065_team_all_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortcut",
            name="text",
            field=models.TextField(max_length=10000),
        ),
    ]
