# Generated by Django 5.1.2 on 2024-10-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0066_alter_shortcut_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
