# Generated by Django 2.1.8 on 2019-07-01 22:25

import os

from django.db import migrations
from django.db.migrations import RunSQL


class InstallSQL(RunSQL):
    """
    Migration that reads the SQL from the named file and runs it as a RunSQL migration
    """

    def __init__(self, filename):
        # build the full path to our filename
        sql_path = os.path.join(os.path.dirname(__file__), "%s.sql" % filename)
        with open(sql_path) as sql_file:
            sql = sql_file.read()

        super().__init__(sql)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_initial"),
        ("campaigns", "0030_initial"),
        ("channels", "0120_channellog_msg"),
        ("contacts", "0102_contacturn_channel"),
        ("flows", "0204_flowstart_campaign_event"),
        ("locations", "0018_boundaryalias_org"),
        ("msgs", "0132_initial"),
        ("orgs", "0055_initial"),
    ]

    operations = [InstallSQL("initial_functions"), InstallSQL("initial_indexes"), InstallSQL("initial_triggers")]
