# Generated by Django 2.1.8 on 2019-07-01 22:25

from django.db import migrations

from . import InstallSQL


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_initial"),
        ("campaigns", "0030_initial"),
        ("channels", "0120_channellog_msg"),
        ("contacts", "0102_contacturn_channel"),
        ("flows", "0204_flowstart_campaign_event"),
        ("locations", "0018_boundaryalias_org"),
        ("msgs", "0132_initial"),
        ("orgs", "0055_initial"),
    ]

    operations = [InstallSQL("0001_functions"), InstallSQL("0001_indexes"), InstallSQL("0001_triggers")]
