# Generated by Django 2.2.10 on 2020-12-04 17:21

from django.db import migrations

from . import InstallSQL


class Migration(migrations.Migration):

    dependencies = []

    operations = [InstallSQL("0002_functions"), InstallSQL("0002_indexes"), InstallSQL("0002_triggers")]
