# Generated by Django 4.0.8 on 2023-01-11 15:35

from django.db import migrations

from . import InstallSQL


class Migration(migrations.Migration):

    dependencies = []

    operations = [InstallSQL("0005_functions"), InstallSQL("0005_indexes"), InstallSQL("0005_triggers")]
