# Generated by Django 4.0.8 on 2023-01-11 15:35

from django.db import migrations

from . import InstallSQL


class Migration(migrations.Migration):
    dependencies = [("contacts", "0171_squashed"), ("msgs", "0206_squashed"), ("notifications", "0011_squashed")]

    operations = [InstallSQL("0005_functions"), InstallSQL("0005_indexes"), InstallSQL("0005_triggers")]
