# Generated by Django 4.2.8 on 2024-01-05 15:09

from django.db import migrations

from . import InstallSQL


class Migration(migrations.Migration):
    dependencies = []

    operations = [InstallSQL("0006_functions"), InstallSQL("0006_triggers")]
