# Generated by Django 2.2.4 on 2020-06-29 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("flows", "0231_auto_20200622_1053"), ("links", "0002_auto_20200123_1321")]

    operations = [
        migrations.AddField(
            model_name="link",
            name="related_flow",
            field=models.ForeignKey(
                default=None,
                help_text="Make this link related to a specific flow. (leave empty to make related to all flows)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_links",
                to="flows.Flow",
            ),
        )
    ]
