# Generated by Django 2.2.10 on 2021-08-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0003_link_related_flow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link",
            name="clicks_count",
        ),
    ]
