# Generated by Django 2.1.8 on 2019-07-01 20:59

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [("channels", "0120_channellog_msg")]

    operations = [
        migrations.CreateModel(
            name="IVRCall", fields=[], options={"proxy": True, "indexes": []}, bases=("channels.channelconnection",)
        )
    ]
