# Generated by Django 2.2.10 on 2020-12-04 17:21

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channels", "0124_squashed"),
    ]

    operations = [
        migrations.CreateModel(
            name="IVRCall",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": []},
            bases=("channels.channelconnection",),
        ),
    ]
