# Generated by Django 4.1.9 on 2023-05-29 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("ivr", "0024_count_db_triggers")]

    operations = [
        migrations.AlterField(
            model_name="call",
            name="org",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="calls", to="orgs.org"),
        ),
    ]
