# Generated by Django 4.2.3 on 2023-09-11 21:32

from django.db import migrations, transaction


def backfill_call_counts(apps, schema_editor):
    """
    This migration rebuilds call counts across all orgs, addressing the problem in 0026 which is that it only updated
    counts for orgs with IVR calls - but there were label_type=C counts already in the database for many orgs from back
    when that meant something else.
    """

    Org = apps.get_model("orgs", "Org")
    SystemLabelCount = apps.get_model("msgs", "SystemLabelCount")

    for org in Org.objects.all():
        with transaction.atomic():
            org.system_labels.filter(label_type="C").delete()

            call_count = org.calls.count()

            SystemLabelCount.objects.create(org=org, label_type="C", count=call_count, is_squashed=True)

        print(f"Backfilled call count for org '{org.name}' (calls={call_count})")


def reverse(apps, schema_editor):
    pass


def apply_manual():  # pragma: no cover
    from django.apps import apps

    backfill_call_counts(apps, None)


class Migration(migrations.Migration):
    dependencies = [("ivr", "0026_backfill_call_counts")]

    operations = [migrations.RunPython(backfill_call_counts, reverse)]
