# Generated by Django 2.2.4 on 2020-05-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("migrator", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="migrationtask",
            name="migration_org",
            field=models.PositiveIntegerField(
                default=1, help_text="The organization ID on live server that is being migrated", verbose_name="Org ID"
            ),
            preserve_default=False,
        )
    ]
