# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-15 20:40
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("triggers", "0010_auto_20170509_1506")]

    operations = [
        migrations.AlterField(
            model_name="trigger",
            name="channel",
            field=models.ForeignKey(
                help_text="The associated channel",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="triggers",
                to="channels.Channel",
                verbose_name="Channel",
            ),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="triggers_trigger_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="flow",
            field=models.ForeignKey(
                help_text="Which flow will be started",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="triggers",
                to="flows.Flow",
                verbose_name="Flow",
            ),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="triggers_trigger_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="org",
            field=models.ForeignKey(
                help_text="The organization this trigger belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                to="orgs.Org",
                verbose_name="Org",
            ),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="schedule",
            field=models.OneToOneField(
                blank=True,
                help_text="Our recurring schedule",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trigger",
                to="schedules.Schedule",
                verbose_name="Schedule",
            ),
        ),
    ]
