# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-10 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0011_auto_20171010_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='nlu_data',
            field=models.TextField(help_text='Intents, accurancy, bots, somethings that will be used to nlu', null=True, verbose_name='Nlu Data'),
        ),
    ]
