# Generated by Django 2.2.20 on 2021-06-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triggers", "0020_auto_20210615_1748"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trigger",
            name="trigger_type",
            field=models.CharField(default="K", max_length=1),
        ),
    ]
