# Generated by Django 4.0.7 on 2022-09-19 19:54

from django.db import migrations
from django.utils import timezone


def delete_bad_missed_call_triggers(apps, schema_editor):  # pragma: no cover
    Trigger = apps.get_model("triggers", "Trigger")

    num_deleted = (
        Trigger.objects.filter(trigger_type="M", is_active=True)
        .exclude(flow__flow_type="M")
        .update(is_active=False, modified_on=timezone.now())
    )

    print(f"Deleted {num_deleted} missed-call triggers attached to non-message flows")


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("triggers", "0024_alter_trigger_options"),
    ]

    operations = [migrations.RunPython(delete_bad_missed_call_triggers, reverse)]
