# Generated by Django 4.1.7 on 2023-04-18 17:43

from django.db import migrations
from django.utils import timezone

TYPE_KEYWORD = "K"
MATCH_FIRST_WORD = "F"


def fix_and_archive_broken_keyword_triggers(apps, schema_editor):  # pragma: no cover
    Trigger = apps.get_model("triggers", "Trigger")
    num_fixed = 0

    for trigger in Trigger.objects.filter(trigger_type=TYPE_KEYWORD, match_type=None):
        trigger.match_type = MATCH_FIRST_WORD
        trigger.is_archived = True
        trigger.modified_on = timezone.now()
        trigger.save(update_fields=("match_type", "is_archived", "modified_on"))
        num_fixed += 1

    if num_fixed:
        print(f"Fixed and archived {num_fixed} keyword triggers")


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):
    dependencies = [("triggers", "0028_alter_trigger_channel_alter_trigger_flow_and_more")]

    operations = [migrations.RunPython(fix_and_archive_broken_keyword_triggers, reverse)]
