# Generated by Django 4.2.3 on 2023-10-12 20:41

from django.db import migrations


def migrate_keyword_triggers(apps, schema_editor):  # pragma: no cover
    Trigger = apps.get_model("triggers", "Trigger")

    num_updated = 0
    for trigger in Trigger.objects.filter(trigger_type="K"):
        trigger.keywords = [trigger.keyword]
        trigger.save(update_fields=("keywords",))
        num_updated += 1

    if num_updated:
        print(f"Updated {num_updated} keyword triggers")


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):
    dependencies = [("triggers", "0030_trigger_keywords")]

    operations = [migrations.RunPython(migrate_keyword_triggers, reverse)]
