# Generated by Django 4.2.3 on 2023-10-17 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("triggers", "0031_migrate_keyword_triggers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trigger",
            name="keyword",
        ),
    ]
