# Generated by Django 4.2.3 on 2023-10-23 17:06

from django.db import migrations
from django.db.models import Count


def backfill_trigger_priority(apps, schema_editor):  # pragma: no cover
    Trigger = apps.get_model("triggers", "Trigger")

    triggers = (
        Trigger.objects.all().annotate(num_groups=Count("groups")).annotate(num_exclude_groups=Count("exclude_groups"))
    )

    num_updated = 0

    for trigger in triggers:
        priority = 0
        if trigger.channel_id:
            priority += 4
        if trigger.num_groups:
            priority += 2
        if trigger.num_exclude_groups:
            priority += 1

        trigger.priority = priority
        trigger.save(update_fields=("priority",))
        num_updated += 1

    if num_updated:
        print(f"Updated priority on {num_updated} triggers")


def reverse(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):
    dependencies = [("triggers", "0034_trigger_priority")]

    operations = [migrations.RunPython(backfill_trigger_priority, reverse)]
