# Generated by Django 4.2.3 on 2023-11-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("triggers", "0037_delete_scheduleless_schedules"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="trigger",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("trigger_type", "S"), _negated=True), ("schedule__isnull", False), _connector="OR"
                ),
                name="triggers_scheduled_trigger_has_schedule",
            ),
        ),
    ]
