# Generated by Django 2.1.5 on 2019-01-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("ussd", "0003_initial")]

    operations = [migrations.DeleteModel(name="USSDSession")]
